### ISSUE TITLE
Unable to create a Safe through a Safe

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#1330]
## Bug description

It's not possible to create a Safe when connected to a Safe in both the old and new creation flow.

## Steps to reproduce

 1. Connect to the UI with a Safe via WalletConnect.
 2. Attempt to create a Safe.

## Expected result

The Safe is created, in the same manner a transaction would happen when interacting with a "nested Safe".

## Obtained result

The creation transaction fails with a `safeTxGas` error.

## Notes

This could more than likely affect transaction caching. We need to consider the queuing of transactions in the parent Safe as well.

## Screenshots

![image](https://user-images.githubusercontent.com/20442784/206443088-fdef15a1-cbfb-4715-901a-c79d65811f6c.png)

## Links

- [Discussion thread here](https://5afe.slack.com/archives/C03DAGWJCR5/p1670500767168049)

**Comment by katspaugh** [comment]
Please give it another try.

**Comment by francovenica** [comment]
It half works.

The safe creation flow gets stuck even after executing the tx in the safe-as-owner, but the safe is actually created just fine.

Safe created:
gor:0xD5F62387CE9B971D19AB8925553DbB7343486E74
Safe owner and tx of the creation:
https://app.safe.global/gor:0x24F8542Da0C5f267c177a224270442C73804EE80/transactions/tx?id=multisig_0x24F8542Da0C5f267c177a224270442C73804EE80_0xfcf954f4bbb3118bfe16eecba8f469514e7dd6ef8d28de2fea4b30b6469b837d

Gets stuck in the safe creation
![image](https://user-images.githubusercontent.com/4503659/212228889-3637fec6-ba70-4a3f-8c9b-ba58437628f3.png)

**Comment by liliya-soroka** [comment]
re-checked 14.02.2024 
The status is not updated even if the owner-safe is 1/1 and executes safe creation immediately.
Also, retry will return an error, as the safe is created 
https://github.com/safe-global/safe-wallet-web/assets/338622/98b08d85-54db-41f9-9285-d0a457d79159

**Comment by jmealy** [comment]
I wasn't able to reproduce this. Creating the safe worked fine when using the connected wallet of the parent safe, but fails when you try to relay the creation transaction in the parent safe.

AFAIU this is expected and @schmanu is looking into it (https://5afe.slack.com/archives/C03DAGWJCR5/p1721048653147209?thread_ts=1721034333.979979&cid=C03DAGWJCR5)

@liliya-soroka could you check again?

**Comment by katspaugh** [comment]
I'll close this one and make a separate issue for relaying.
