### ISSUE TITLE
No time out without manual page refreshing during safe creation 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#1355]
Regression for the 1.2.0 release candidate
        3. Hola team! For this [ticket](https://github.com/safe-global/web-core/pull/1293) regarding timeouts on safe creation the expected result is shown to me after 6,5 minutes on the case that I reload the page:

<img width="832" alt="Screenshot 2022-12-12 at 17 17 55" src="https://user-images.githubusercontent.com/92332710/207097426-a3b3d92e-188d-4f29-a46b-0c94f301e7cd.png">

but unfortunately on the case that I don't perform a manual page reload it will be stuck on this screen forever (I have waited for 20 minutes in chrome)

<img width="468" alt="Screenshot 2022-12-12 at 17 05 01" src="https://user-images.githubusercontent.com/92332710/207094743-8a38c591-b739-4a7c-acc0-644de01d6191.png">

_Originally posted by @JagoFigueroa in https://github.com/safe-global/web-core/issues/1341#issuecomment-1346821979_

**Comment by usame-algan** [comment]
This is an unintended side-effect that was introduced with #1223. Good news is that it eventually times out after around 30 minutes or ~100 blocks which is probably the default value of the provider. So far I haven't found a way to overwrite that.

![Image](https://user-images.githubusercontent.com/5880855/207317994-ebad49bc-f728-4219-9674-594dc4dcb780.png)

A possible solution would be to still run the watcher and do a `Promise.race`

**Comment by DiogoSoaress** [comment]
Been looking at this bug together with Usame and we think it can be addressed separate from the Release.

Would it be acceptable to fix during next Sprint? @JagoFigueroa @liliya-soroka

**Comment by JagoFigueroa** [comment]
Sure señor!

**Comment by schmanu** [comment]
I looked through the ticket and reproduced it and do not like the current way we handle timeouts:
Currently the Retry-button will create a new transaction with a **new nonce** in your connected wallet. Meaning the "retried" transaction can only be executed **after** the previous (pending) one.
For a transaction with extremely low gas price this might never execute. Thus the retried transaction will also timeout.
OR if both transactions eventually go through the user will accidentally create 2 Safes.

Instead we should suggest to **speed up** the **existing transaction** or the retry button should reuse the last nonce, which is the same as "Speeding up" the transaction.

I also find the text a bit misleading `Please cancel the process or retry the transaction.` 
This kinda implies that cancel will actually cancel the process while in fact the transaction will stay pending and might even still get executed. I think we should educate the user more here or give better options on what can be done:
1. Wait until the transaction eventually gets executed
2. OR Speed up the transaction / resubmit with higher gas price and same nonce
3. OR Cancel the transaction in your connected wallet

What do you think?

**Comment by usame-algan** [comment]
> Instead we should suggest to speed up the existing transaction or the retry button should reuse the last nonce, which is the same as "Speeding up" the transaction.

Agreed, we should not give the option to cancel or retry for a new transaction if the existing one times out. I will create a new ticket to rework this.

**Comment by liliya-soroka** [comment]
Fixed in the https://github.com/safe-global/safe-wallet-web/issues/2878 
The current timeout is 60sec instead of 20-30 mints
