### ISSUE TITLE
[mobile-web] Submitting a tx, redirects to App Store and not Metamask

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-wallet-web#1384]
## Description
When trying to confirm a tx, I am redirected to the App Store entry and not Metamask itself

## Environment
 - Browsers: Firefox, Safari
 - Wallet: MetaMask
 - Chain: Görli
 - iOS: 16.1

## Steps to reproduce
 1. Open https://apps.safe.global in Firefox on iOS
 2. Add Safe
 3. Connect to Metamask account
 4. Goto queue
 5. Select tx that needs confirmation
 6. Hit Confirm
 7. Hit Submit

## Expected result

Metamask opens and asks me to sign a tx

## Obtained result

https://user-images.githubusercontent.com/246473/208075510-ef641108-cd95-4654-b9f4-8127c2142194.mov

## Additional info

Clicking on "Open" just opens Metamask without asking me to sign.

**Comment by mikhailxyz** [comment]
I use snapshot with argent quite often and they don't have this problem. They do have other though like lost signing requests 😂 

https://user-images.githubusercontent.com/16622558/208082639-5e3b6a7e-3321-4f4f-a6f6-4dc0210b3a98.mov

**Comment by katspaugh** [comment]
It's either WC or iOS itself. As Dirk said, sometimes when you tap the "Open" button in the banner on top, Safari "remembers" this choice for a while, and opens the app directly. But this is not always working.
