### ISSUE TITLE
[Safe Apps] Accepting permissions from different paths in the safe domain replace the current selection in the storage

### ISSUE THREAD

**Issue by yagopv** [safe-global/safe-wallet-web#1416]
## Bug description
Currently when you accept permissions from an app whose domain is a subpath from an already accepted one, the selection is replaced instead merged

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any

## Steps to reproduce
 1. Open a Safe App asking for permissions (https://pr615--safereactapps.review-react-hr.5afe.dev/tx-builder) and accept them
 2. Open another Safe App asking for a different set of permissions (https://pr615--safereactapps.review-react-hr.5afe.dev/wallet-connect) and in the same domain and accept them
 3. Open first app (1.) again

## Expected result
If the permissions are already accepted for the domain, no dialog is showed

## Obtained result
The Safe App is asking again for permissions and It shouldn't. The new permissions should be merged instead replaced 

## Testing tips
All Safe apps permissions, Browser + Safe ones (requestAddressBook) should work by domain so the comparisons and the permissions accepted can affect several apps in subpaths from the same domain. To QA this we should verify the permission system behave like this in

1) Browser permissions
2) Safe permissions (safe-test-app)
3) Custom app warning

**Comment by liliya-soroka** [comment]
still relevant 14.02.2024

**Comment by katspaugh** [comment]
Closing as wontfix, we have only 1 app that uses permissions – CSV Airdrop.
