### ISSUE TITLE
[Ledger/Trezor] No option to load more addresses

### ISSUE THREAD

**Issue by JagoFigueroa** [safe-global/safe-wallet-web#1424]
## Bug description
Related to this [support ticket](https://github.com/5afe/safe-support/issues/102) it is not possible to load more addresses after the initial load is performed for these wallets.

## Environment
 - Browser: Chrome
 - Wallet: Ledger & Trezor
 - Chain: Ethereum mainnet

## Steps to reproduce
 Connect both a Trezor & Ledger to the web interface and perform a initial scan of accounts.

## Obtained result
A maximum of 6 addresses are loaded.

## Expected result
Allow to load more addresses as in the legacy interface

**Comment by iamacook** [comment]
This is related to onboard itself. I have spoken with Blocknative and they are actively looking into it.

**Comment by MorpheusNetwork** [comment]
Hi @iamacook have you received any updates from Blocknative? Thanks!

**Comment by iamacook** [comment]
@MorpheusNetwork, does checking "Show Empty Addresses" in the top left of the address selection modal solve this for you?

**Comment by MorpheusNetwork** [comment]
Please note @iamacook I am not the original reporter of this issue.

There are multiple, duplicate reports of this same issue.

Please also see: https://github.com/5afe/safe-support/issues/178#issue-1677571827

"Show Empty Addresses" is selected in the screenshot.
However, it is reporting that, "10 total addresses found".

Trezor wallets can generate unlimited wallet addresses. If, "Show Empty Addresses" is selected, the user should be able to "view more" to view more than 10 wallet addresses.

Currently it seems there is no option to view more than 10 wallets.

**Comment by Adamj1232** [comment]
@MorpheusNetwork thanks for raising this issue! 
Currently the a default threshold of 5 **consecutively** empty addresses will return the list of wallet addresses for hardware wallets. 
It is also valuable to note that in more recent versions of web3-onboard/core the "Display Empty Addresses" selection is `on` by default.
I have a [PR in review](https://github.com/blocknative/web3-onboard/pull/1715) by the web3-onboard team to parameterize this value so the dev, (Safe in this case) can set that value to whatever number is preferred. 
Most applications do not need more than that number but it does make sense in Safe's case to allow this number to be configurable. If you have any concerns with this approach please let us know.

**Comment by MorpheusNetwork** [comment]
Hello @Adamj1232 
Yes that appears to be one potential solution.

As a comparison, in MyCrypto a user can press, "More" to display the next set of 5 wallets addresses without any limits or restrictions.

Here is a sample screenshot from the MyCrypto website:
https://support.mycrypto.com/static/a094d3d4371e11ad4b63ec7c4f51adf8/d26aa/address-list.png

**Comment by Adamj1232** [comment]
@MorpheusNetwork we will let the dapp devs control this for now and will discuss designs for adding a feature like MyCrypto in the future if still needed. With this upcoming change the Safe team can set to the consecutive empty addresses prop to 10 or 20 and give a list as large as their users need without the wait of our designers getting involved and reworking the UI for desktop/mobile
