### ISSUE TITLE
Connecting to metamask after a fresh browser start

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-wallet-web#1474]
## Bug description
After a fresh browser start / after fully restarting the browser it is not possible to connect to MetaMask.
Only after refreshing the page the state updates and shows the connected wallet.
This does not happen in Firefox.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Görli
 - This happens in staging and prod

## Steps to reproduce
 1. Fully close and restart the Chrome browser
 2. Open `app.safe.global`
 3. Click "Connect Wallet" and select MetaMask
 4. Metamask pops up as expected
 5. Now Quite the browser without interacting with the metamask popup
 6. Start over by starting the browser again
 7. Open the app, Click "Connect wallet" and select MetaMask
 8. It shows "Connecting" in the dialog but metamask does not pop up.
 9. After manually opening metamask and unlocking it it still does not show as connected.
 10. After refreshing the browser it shows the connected wallet.

## Expected result
It should open the metamask extension after selecting metamask and show the connected wallet if unlocked.

## Obtained result
It is stuck in the "Connecting" state and does not open MetaMask

## Analysis
This seems to be a bug in the MetaMask Extension. 
If the browser is in the buggy state `window.ethereum.request({ method: 'eth_requestAccounts' })` remains pending forever and never resolves. 
I tested this by executing this in the browser console while metamask wasn't connecting properly:
```js
window.ethereum.request({ method: 'eth_requestAccounts' }).then(console.log).catch(console.error)
```

When executing the same script after refreshing it opens up the metamask extension as expected.

## Screenshots
https://user-images.githubusercontent.com/2670790/210242677-bc609df9-9eb7-4799-871e-a312e7194d78.mov

**Comment by katspaugh** [comment]
Maybe as a workaround we could refresh the page if MM isn't resolving `eth_requestAccounts` for X seconds?

Btw what about a page reload makes it work? Is this related to how extensions work?

**Comment by katspaugh** [comment]
26.06.2023 update: it's still an issue.

**Comment by katspaugh** [comment]
I haven't had this bug in a while. Looks like it got fixed.
