### ISSUE TITLE
[Sidebar, Mobile view] Safe address overlapped by current balance

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#1492]
## Bug description
In the mobile view, for added safes in the sidebar, if the balance is too long or has too many decimals it overlaps the safe address

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Gnosis chain
 - Env: https://app.safe.global/gno:0xB8d760a90a5ed54D3c2b3EFC231277e99188642A/home

## Steps to reproduce
 1. Go to the app and add the safe given above (it has a balance with a lot of decimals)
 2. After adding the safe open the sidebar

## Expected result
The address should't overlapp with the balance

## Obtained result
The address is overlapped by the balance

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/210896547-b4cdee9f-f768-47aa-8095-aa5c39063236.png)

**Comment by 0xOptimism** [comment]
Should we remove some decimals in that case?

**Comment by katspaugh** [comment]
Probably rounding the amount would be a solution.

**Comment by DiogoSoaress** [comment]
@usame-algan the new Design from https://github.com/safe-global/web-core/pull/1556 should be considered while fixing this bug.

**Comment by 0xOptimism** [comment]
> Probably rounding the amount would be a solution.

Would be nice to have at least 2-3 decimals and a tooltip on hover to show the total amount maybe could be useful.
