### ISSUE TITLE
Network is not unselected in the header after select network drop-down is closed

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#1546]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Click on the networks in the header
 2. select network
 Current result: The networks drop-down is closed, but the network section is still highlighted 
It should be back to the white colour automatically after the network is selected , without additional click on the screen

## Expected result
It should be back to the white colour automatically after the network is selected , without additional click on the screen

## Obtained result
https://drive.google.com/file/d/1Ikh6XD-DEcG0Wm24GcPdCPDPi0brvOdN/view?usp=share_link

[Screen Recording 2023-01-16 at 14.10.55.webm](https://user-images.githubusercontent.com/5880855/221567483-b5865cd4-f19e-4875-b6fc-883247f04616.webm)

## Screenshots
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/338622/212685933-062e4794-5c13-4cce-9f2f-be3a9b6a70fa.png">

**Comment by yash251** [comment]
The drive link is private. Please provide public access

**Comment by usame-algan** [comment]
@yash251 I added the video to the description

**Comment by qqqzhch** [comment]
I did try it and the problem is still there, I will try to fix it

**Comment by qqqzhch** [comment]
I tried a few things I thought of, but none of them were very successful.
I'm not very familiar with mui, so I couldn't find any relevant configuration for unfocusing
Is there a correct way to fix this focus state?

**Comment by katspaugh** [comment]
I think it's quite tricky indeed. The focus needs to be visible when using the keyboard for accessibility reasons, but we don't want it when clicking with a mouse. 

Perhaps it's better to pick some other issue if you want to contribute. I've removed the "good first issue" label.
Thanks for looking into it.
