### ISSUE TITLE
Non-owner spending limit beneficiary buttons

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#1617]
## What is the feature about

As non-owner speding limit beneficiaries [can execute transactions](https://github.com/safe-global/web-core/pull/1572), some extra buttons in the asset table/transaction details would be beneficial (as suggested [here](https://github.com/safe-global/web-core/pull/1572#issuecomment-1409611070)).

## The list of requirements

1. Add "Send" button next to assets in the asset table.
2. Add "Send again" button to historical transactions.

Note: tracking should also be included.

**Comment by katspaugh** [comment]
The regular Send/New tx buttons now work for spending limit users.
