### ISSUE TITLE
Hideable balances

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#1635]
## What is the feature about

Many wallets allow for balances to be hidden/blurred to prevent others from seeing them. We should include a setting, or sidebar toggle to show/hide balances. We could also show balances on hover if they are hidden.

## The list of requirements

- Include setting/toggle to show/hide balances
- Create balance rendering component that responds to the setting
- Use balance component in all places balances are shown

## Designs/sketches

tbd

**Comment by vdoflip** [comment]
This is a very simple yet very critical feature when using Safe in public or not very private environments.  the **Total asset value** header shows the amount in a very big size and this can be a problem.



Why was it archived/discarded?

**Comment by katspaugh** [comment]
I closed it because it wasn’t prioritized. @kirkkonen should we look into this?
