### ISSUE TITLE
[removeOwner] Confusing method signature in Transaction Details

### ISSUE THREAD

**Issue by Sednaoui** [safe-global/safe-wallet-web#1639]
## Bug description
When removing or replacing an owner from safe account from the settings tab, the UI in the collapsable **_Transaction Details_** card shows the wrong old and new address.  

## Environment
 - Browser: any
 - Wallet: any
 - Chain: optimism (I don't think it's related to a specific chain, but I was on Optimism)

## Steps to reproduce
1. Go to a safe you own on https://app.safe.global (I tried with a multisig of 3 with threshold 2)
2. Got to settings. On the setup tab, remove owner A from, sign. 
3. Ask the owner to review the transaction of `removeOwner`
4. Click on transaction details to expand the card
5. Notice that the old owner address/ nickname and the new owner /nickname (in case of replace) are not the correct. 

## Expected result
The same information displayed in the transaction review and simulation should be shown in the transaction details.
## Obtained result
Incorrect address of old owner and new owner

**Comment by katspaugh** [comment]
I wasn't able to reproduce this, @liliya-soroka could you try?

**Comment by liliya-soroka** [comment]
I can not reproduce the issue either neither on Goerli nor on Optimism :

**Comment by katspaugh** [comment]
I'm a bit confused about this bug report, too. It says it's about removing an owner, but also mentions that it "shows the wrong old and new address". Is it about _replacing_ or _removing_ an owner?

**Comment by Sednaoui** [comment]
Hello, sorry for the confusing. I have looked again and the issue is not a frontend one. While I personally know the safe contracts well, I got confused while rotating owners as it happened in a very urgent matter. The confusions lies in how the inputs variables are called in the contract. 

The example of remove owner is the following:  

Title: Remove Owner: 

`prevOwner(address)`

with

`owner(address) `

`prevOwner` sounds like Previous Owner (to be removed), but as you know it does refer to the Owner that pointed to the address to be removed

`owner` sounds like the new Owner, given the context of the title remove owner with previous owner, but it does refers to the new owner to be removed.  

I can understand that the transaction detail card should show exactly which methods are being called. Maybe there could be an information bubble next to the input variable, describing the real meaning of it.   

![Screenshot from 2023-02-06 13-10-17](https://user-images.githubusercontent.com/7014833/216970145-2584eaaa-604b-401e-9a7c-39133e900370.png)

**Comment by katspaugh** [comment]
Oh, I see now. Good point about the argument naming being somewhat confusing.
It might be worth writing a help article about this, e.g. "How removing an owner works on the contract level", and linking it in that dialog.
I'll mark this as an enhancement since it works as intended. Cheers!

**Comment by iamacook** [comment]
For reference, [here](https://ethereum.stackexchange.com/a/121948/87368)'s an explanation of how the owners linked list works.
