### ISSUE TITLE
Add more ENS support for Safes: multichain ENS support and reverse name lookups

### ISSUE THREAD

**Issue by ademidun** [safe-global/safe-wallet-web#1642]
1. Currently, users can enter an ens address when loading a Safe, however, there's 2 limitations:
   1. ENS lookup is only available when loading Ethereum Mainnet Safes, however, we should add support for other chains that are supported by ENS
    2. once they enter their ENS it shows their full checksum address, it should show the ENS name instead just like it does for their EOA wallet

Example:

[This Safe](https://app.safe.global/eth:0xCF60916b6CB4753f58533808fA610FcbD4098Ec0/home) belongs to the ENS, [multisig.ens.eth](https://etherscan.io/enslookup-search?search=multisig.ens.eth)

See:
- [Not an ENS](https://docs.google.com/document/d/1ktKbDR7Gob_FI5CX94rhaxbN7rS3t4AdMNLIcBWfIk8/edit#)
- [ENSIP-11: EVM compatible Chain Address Resolution](https://docs.ens.domains/ens-improvement-proposals/ensip-11-evmchain-address-resolution)

> To make ENS multicoin addresses fully useful, the integration with wallets are necessary.
> This is the ideal flow we would like more wallets to integrate
> 
> 1. Check if the EVM chain is supported by address-encoder
> 2. If supported, resolve with the coinType(derived from the chainId)
> 

Fun fact: This issue was inspired by running into Makoto from ENS at a Starkware co-working space in Tel Aviv.

## Screenshots

<img width="1463" alt="Screen Shot 2023-02-05 at 10 30 04 AM" src="https://user-images.githubusercontent.com/9806858/216809272-a8c5af65-d079-4078-9990-c7871972c552.png">

<img width="850" alt="Screen Shot 2023-02-05 at 10 20 10 AM" src="https://user-images.githubusercontent.com/9806858/216809030-44d06085-0fca-4c29-a9d3-c6e4cdd0809c.png">

<img width="792" alt="Screen Shot 2023-02-05 at 10 20 04 AM" src="https://user-images.githubusercontent.com/9806858/216809029-57893ff3-f219-4e87-9729-2d368527cd94.png">

**Comment by katspaugh** [comment]
The ENS support per chain is togglable in the config service. However, ENS is actually deployed only on mainnet (and testnets).

Even if we resolved ENS names on other chains, they'd still point to Ethereum mainnet addresses. This would work for EoAs but not for smart contracts. The same address on different chains doesn't necessarily point to a contract controlled by the same ENS user.
 
It's possible, however, to detect contract addresses. See [this post](https://medium.com/the-ethereum-name-service/how-to-support-ens-for-multi-chain-dapps-b0a7ff043d77) for details.

[A previous discussion](709) on this topic.

**Comment by ademidun** [comment]
@makoto can you please give your opinion on this?

**Comment by mikhailxyz** [comment]
There's multichain address resolution: https://docs.ens.domains/ens-improvement-proposals/ensip-9-multichain-address-resolution

**Comment by makoto** [comment]
> This would work for EoAs but not for smart contracts.

exactly. We propose that you lookup the multichain resolution which @mikhailxyz just pointed out

**Comment by katspaugh** [comment]
This is being discussed in the product team. New user stories will be written. Closing this feature request in the meanwhile.
