### ISSUE TITLE
[Nested Safe][Spending limits] Send funds form is not closed when safe is used as beneficiary

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#1653]
## Bug description
Send funds form is not closed when safe is used as beneficiary (both cases as an owner and as non-owner)

## Environment
 - Browser: Chrome/FF
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. create a spending limits a safeA as beneficiary for the safe B
 2. connect safe A as a wallet to the safe B using wallet connect safe app in the safe A
 3. open send funds -> select allowed token according to the spending limit
 4. submit tx in the safe B
 5. Tx appears as WC tx in the safe A
 6. confirm and execute tx in the safe A
Current result: Send funds modal is not reacted on tx creation in the safeA via WC

Note: this does not happen with direct EOA connection.

## Expected result
Close spend funds modal for the spending limits case as we do for the usual Send funds and show a notification

**Comment by liliya-soroka** [comment]
Updated ( 14.02.2024):
- works as expected if a spending tx is confirmed&executed  by the beneficiary safe right away 
- doesn't work if the sign and execute operations are separated in the beneficiary safe

**Comment by francovenica** [comment]
It works fine now.
Whatever it is with immediate execution or sign first execute later, in both cases the benefitiary tx removes the send funds from view
