### ISSUE TITLE
Add Safe Apps icon that opens the sidebar

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#1697]
## What is the feature about

Adding a new info icon to the Safe Apps card that opens the Safe Apps sidebar.

When a Safe App is opened we display the sidebar, but sequential opens should not. The sidebar is only then accessible via a new info icon.

Note: Remember that all the disclaimer information and terms was moved to the sidebar and this is why we didn’t add the info icon when we implemented this. So it should need to behave differently if the user already accessed apps or not, or that specific app or a different app.

## The list of requirements

- [x] Add cache for a Safe Apps having been opened
- [x] Add new info icon to Safe Apps card that opens the sidebar

## Designs/sketches

![image](https://user-images.githubusercontent.com/20442784/221157491-3fa047dd-f420-4b17-a14e-47d5c0bb5257.png)

## Links

- [Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=4391%3A82177&t=KUMeLBgTn2PuCrPE-0)
- [Discussion threa](https://5afe.slack.com/archives/C03DAGWJCR5/p1677232976161529)

**Comment by katspaugh** [comment]
@iamacook can you remind me why this is blocked?

**Comment by katspaugh** [comment]
@liliiaorlenko shall we unblock this? Lots of people are complaining about this, as you know.

**Comment by liliiaorlenko** [comment]
design proposal is ready so pls continue with it
