### ISSUE TITLE
Beamer's bell icon shows when the sidebar is visible

### ISSUE THREAD

**Issue by DiogoSoaress** [safe-global/safe-wallet-web#1745]
## Bug description
The button with bell icon in the bottom right should only be visible if the Sidebar is hidden as it duplicates the "What's new" button on the sidebar -> Opening the Beamer drawer

## Environment
 - Browser: Chrome / Production
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to Safe dashboard page with a horizontal viewport below 900px, let's say 600.
 2. The Sidebar is hidden and the bell icon is visible.
 3. Increase the viewport above 900px so the sidebar becomes visible.
 4. The bell button should be hidden.

## Expected result
The button hides and displays responding to the sidebar visibility.

## Obtained result
The button is not hidden/displayed wrt the sidebar visibility

## Screenshots
![Screenshot 2023-03-07 at 10 48 49](https://user-images.githubusercontent.com/32431609/223386175-a354b1d4-8d66-476b-ad03-97f6ff16dabf.png)

**Comment by usame-algan** [comment]
Afaik seeing the Bell button in the corner was never intended and we noticed it only after hiding the Sidebar on some pages. For now we've disabled the Bell button via Beamer settings so it doesn't show up on mobile nor desktop viewport.
