### ISSUE TITLE
Show safe app landing page on unsupported networks

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#1770]
## What is the feature about

If a safe app is not available on a network it is not possible to open its landing page (share url). However, this would be useful with the implementation of #1756  in case a user switches to a safe on a different network while using a safe app because it helps to understand whats happening instead of redirecting them to a different page.

## The list of requirements

- Make safe app landing pages available on all networks
- Show a message in case a safe app is not available for a given network e.g. "This safe app is not available on your current network" instead of a list of safes

## Designs/sketches
<img width="1008" alt="Screenshot 2023-03-14 at 11 17 55" src="https://user-images.githubusercontent.com/5880855/224969792-2845e98e-aaa7-40da-8921-bf259f885a9e.png">
<img width="1168" alt="Screenshot 2023-03-14 at 11 19 10" src="https://user-images.githubusercontent.com/5880855/224970106-bab057f4-28c4-4f7c-a969-86d34d391cfd.png">

**Comment by katspaugh** [comment]
Closing because we have no capacity to work on Safe Apps atm.
