### ISSUE TITLE
Parameters can be edited for the relayer indirectly

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#1790]
The values in adv parameters should not be editable when the relaying option is checked (and they are not), but you can edit them while selecting the connected wallet and then change back to the relayer with the new edited values, defeating the purpose of graying out the inputs in the first place

I'd suggest that as soon as you switch to the relayer the values in adv parameters are set to the ones estimated in the beginning

![relayer](https://user-images.githubusercontent.com/4503659/226686462-a3bc8ce3-6a82-43fe-96a9-885a58e2c17d.gif)

_Originally posted by @francovenica in https://github.com/safe-global/web-core/issues/1776#issuecomment-1478272748_

**Comment by katspaugh** [comment]
Closing this as wontfix as these gas fee is ignored when relaying anyway.
