### ISSUE TITLE
[Discussion] - Phantom Wallet integration

### ISSUE THREAD

**Issue by nheingit** [safe-global/safe-wallet-web#1893]
Hey Safe team,

I'm a DevRel engineer over at Phantom. We had spoken to John on y'alls team about adding an integration and he seemed open to the idea. But after opening [my pr](https://github.com/safe-global/web-core/pull/1889) it was closed. We exit our beta this week and will be rolled out on EVM to 100% of our users (3M downloads).

Wanted to kick off a discussion on why the team may be opposed to adding another wallet, and how I could help overcome any obstacles?

Happy to help however I can!

**Comment by johannesmoormann** [comment]
Adding new wallets creates testing overhead on our side, so we decided to only add new wallets based on user demand. We are happy to review this decision when we see Phantom users being interested in using Safe. For the EVM launch unfortunately we cannot support you by adding the wallet.

**Comment by nheingit** [comment]
Understandable, what would communicate user demand to you given that you can't measure the connections? We are the 2nd largest wallet in the space by downloads, behind only MetaMask.

Would you like to start a discussion via email so I can share metrics around our EVM usage?

Or would it be best to send users that feel so inclined to your support page? 

Whatever makes sense to y'all let me know!

**Comment by katspaugh** [comment]
Btw, is Phantom implementing window.ethereum? Or some custom API and hence the need of a custom onboard module? Because we already have the injected wallet onboard module, so it could work out of the box.

**Comment by nheingit** [comment]
We have a custom onboard module to ensure that there aren't any `window.ethereum` collisions between us and MetaMask. So depending on what settings the user have we may/may not inject to `window.ethereum`, but we DO always inject into `window.phantom.ethereum` which is a dup of the normal provider object.

We've worked closely with web3-onboard, web3-modal, dynamic, and rainbowkit to all have direct Phantom integrations that work seamlessly for Phantom users regardless of whether or not they have other wallets installed.
