### ISSUE TITLE
`SignOrExecuteForm` child components unmounting before closing

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#1923]
## Bug description

When executing a transaction, after signing, some components within the `SignOrExecuteForm` unmount due to flag changes.

`useImmediatelyExecutable` internally checks whether a transaction is pending and during the proposal period, this causes elements to unmount, e.g. the "Execute transaction` checkbox, execution method selector, as well as fee details.

Note: before fixing this, we should consider instead including it in the [upcoming refactor of the transaction modal](https://github.com/safe-global/web-core/issues/1828).

## Environment
 - Browser: Firefox
 - Wallet: MetaMask
 - Chain: All

## Steps to reproduce

Create a transaction and after signing its relay, observe the flicker within the modal.

## Expected result

All components remain mouned until the modal closes.

## Obtained result

Some components unmount before the modal closes.

## Screenshots

![modal flikr](https://user-images.githubusercontent.com/4503659/235043530-8c26df25-0f14-4179-b2ec-4d68b310f19e.gif)

**Comment by katspaugh** [comment]
@iamacook is this still the case in epic-tx-redesign?

**Comment by iamacook** [comment]
> @iamacook is this still the case in epic-tx-redesign?

Yes

**Comment by katspaugh** [comment]
Seems to be still the case but it doesn't break anything.
