### ISSUE TITLE
Support Arbitrum Goerli as Additional Testnet

### ISSUE THREAD

**Issue by Oighty** [safe-global/safe-wallet-web#1946]
## What is the feature about
The main Safe app only supports two testnets currently: Goerli (which has high gas prices constantly) and Base Goerli (which is an OP stack chain). Arbitrum is the largest L2 by TVL at the moment and many projects use Arbitrum Goerli testnet as their testing environment. It would be helpful to have access to the Safe UI to have consistent test/prod admin controls via a Safe on Arbitrum.

## The list of requirements
Request: Add Arbitrum Goerli (Nitro Goerli Rollup Testnet) as a supported network on the main Safe app. 

## Links
https://developer.arbitrum.io/public-chains

**Comment by johannesmoormann** [comment]
hey @Oighty as much as we would like to support test chains for every network, doing so is quite resource intensive. currently, we do not have the capacity to support further testnets but will reevaluate this position over time. for the moment I will have to close this issue as this is also much more of an infrastructure topic for us.

**Comment by katspaugh** [comment]
As a piece of alpha, we will soon deprecate our Goerli support and go with Sepolia instead.

**Comment by Oighty** [comment]
> hey @Oighty as much as we would like to support test chains for every network, doing so is quite resource intensive. currently, we do not have the capacity to support further testnets but will reevaluate this position over time. for the moment I will have to close this issue as this is also much more of an infrastructure topic for us.

Got it. Thanks for the reply.
