### ISSUE TITLE
Connect text overfows for mobile viewports

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#1948]
## Bug description
The text on the top bar when disconnected from the app overflows its contaiment

## Environment
 - Browser: Chrome (with emulator), Safari (with an iphone device). Looks the same for both
 - Wallet: Any
 - Chain: Any
 - Env: Prod c1.8.1

## Steps to reproduce
 1. Go to the welcome page 
 2. Use the chrome mobile emulator and set it to iphone12 pro
 3. Check the top bar

## Expected result
The text fits inside the containment

## Obtained result
The text overflows

## Screenshots
![image](https://user-images.githubusercontent.com/4503659/236366239-493b6533-ec40-4f84-ae79-48c45182a17e.png)

**Comment by Shubham0850** [comment]
@francovenica I'm new to opensource contribution, I want to work on this  ticket 😃

**Comment by Shubham0850** [comment]
I'm trying to reproduce the same bug, but i'm not able to see it here ( btw, i'm running `dev` ) 🙂

<img width="602" alt="Screenshot 2023-05-05 at 9 41 47 PM" src="https://user-images.githubusercontent.com/63353473/236511171-6c7d38ff-ee5f-4b5e-ad3b-dc0cee774549.png">

**Comment by katspaugh** [comment]
@Shubham0850 I think you need to be on Gnosis Chain to see this.

**Comment by Shubham0850** [comment]
@katspaugh but i'm not seeing the Gnosis Chain option in the dropdown !!

If you can, provide me the steps to regenerate this bug. Then that would be awesome. Thanks 😃

<img width="796" alt="Screenshot 2023-05-06 at 8 37 01 AM" src="https://user-images.githubusercontent.com/63353473/236595493-31697831-688f-4f8f-8412-877f86abf97c.png">

**Comment by katspaugh** [comment]
There’s a toggle in the sidebar that says “Prod CGW”. You can switch it on, and Gnosis Chain will appear in the list.

**Comment by usame-algan** [comment]
I think this was fixed as part of https://github.com/safe-global/safe-wallet-web/pull/1865 and should be deployed on prod now. Can you try again @francovenica ?

**Comment by Shubham0850** [comment]
@usame-algan thanks for the confirmation 👍

**Comment by francovenica** [comment]
True, is not happening anymore. Idk what caused it in the first place. I'll close this
