### ISSUE TITLE
Include `initializer` in Safe creation transaction details

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#1961]
## What is the feature about

Adding an overview of the `initializer` in Safe creation transaction details, as well as updating the [related help article](https://help.safe.global/en/articles/4774916-verify-safe-creation).

We should render the arguments of `setupModules` and potentially a warning.

## The list of requirements

- [ ] Return the arguments of `setupModules` via the gateway (`dataDecoded.data`, `dataDecoded.to`).
- [ ] Display them in the UI.
- [ ] Show a warning (awaiting designs)

## Links

- [Discussion](https://5afe.slack.com/archives/C03DAGWJCR5/p1683623557388489)

**Comment by katspaugh** [comment]
Can this be done on the backend?

**Comment by iamacook** [comment]
> Can this be done on the backend?

Partially. The transaction service has the [`decodedData`](https://safe-transaction-goerli.safe.global/api/v1/safes/0x22C94Fe640b5a264aA59eb4BD29C51363B57D0fE/creation/) but it is not [exposed by the gateway](https://safe-client.staging.5afe.dev/v1/chains/5/safes/0x22C94Fe640b5a264aA59eb4BD29C51363B57D0fE/transactions/history). If it was, it would negate the first two requirements.

@fmrsabino, how feasible is it to add this to [creation summaries](https://github.com/safe-global/safe-client-gateway/blob/main/src/routes/transactions/converters/summary.rs#L160-L171)?

**Comment by fmrsabino** [comment]
> Partially. The transaction service has the [`decodedData`](https://safe-transaction-goerli.safe.global/api/v1/safes/0x22C94Fe640b5a264aA59eb4BD29C51363B57D0fE/creation/) but it is not [exposed by the gateway](https://safe-client.staging.5afe.dev/v1/chains/5/safes/0x22C94Fe640b5a264aA59eb4BD29C51363B57D0fE/transactions/history). If it was, it would negate the first two requirements.
> 
> @fmrsabino, how feasible is it to add this to [creation summaries](https://github.com/safe-global/safe-client-gateway/blob/main/src/routes/transactions/converters/summary.rs#L160-L171)?


The goal of the "Transaction Summaries" returned by the `/transactions/history` endpoint is so that it is shown in a ready-to-be-rendered state.

That's one of the reasons why we try to map transaction to specific interactions (e.g. Settings Change) at this level and hide this from the clients. The same can be done for the `initializer` but it would depend on what you want to show in the UI.

**Comment by iamacook** [comment]
> The same can be done for the `initializer` but it would depend on what you want to show in the UI.

We need the `decodedData` that is returned by the transaction service.

**Comment by katspaugh** [comment]
Closing as this hasn't been implemented on the backend, and it's not planned there either.
