### ISSUE TITLE
Add Your Safe Preview to the loading state of create Safe

### ISSUE THREAD

**Issue by liliiaorlenko** [safe-global/safe-wallet-web#1967]
## What is the feature about
At the page of loading new safe, would be beneficial to see the preview of your safe, during the design stage I missed this point. 
Designs is provided.
## Designs/sketches
https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?node-id=56%3A7045&t=D2lNzEkjVahyyvuX-1

**Comment by katspaugh** [comment]
Closing as not planned because we're changing the creation flow to not wait for indexing.
