### ISSUE TITLE
Prefix validation not workin on address inputs

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2006]
## Bug description
Pasting an address with the wrong prefix is not being validated. It shows at first that is the wrong network, but clicking outside of the input simply replaces the prefix with the one of the current network and allows you to continue with the tx creation.

This is any input (send funds, address book, add owner, spending limits..)

## Environment
 - Browser: Chrome
 - Wallet: Any
 - Chain: Any
 - Env: prod build 1.9.1 and RC 1.10.0

## Steps to reproduce
 1. Copy an address with the prefix in it
 2. Go to a a safe that is in a different network than the prefix fo the address you copied
 3. Copy the address in the input
 4. Click outside of the address input

## Expected result
It should not allow you to continue the safe creation process unless you paste an address with the correct prefix or change it manually

## Obtained result
At first it shows you that the address has the wrong prefix, but still let you keep the creation process
If the address happens to be in the address book it accepts the address with the wrong prefix right away without ever telling the user it is the wrong prefix

## Screenshots
![prefix validation](https://github.com/safe-global/safe-wallet-web/assets/4503659/ae8a4f63-2627-4c81-a910-f3769a042177)

**Comment by liliya-soroka** [comment]
In addition: The error is not displayed at all if the QR code with the wrong prefix is scanned. The correct prefix from the QR code is replaced with the current active chain prefix for the input address field on send tx
