### ISSUE TITLE
[EPIC] Human-readable transactions

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#2011]
## What is the feature about

Ethereum transactions are complex and there’s no easy way to summarize what a single transaction does in one sentence. We propose to create an API to decode contract calls into a short and simple piece of text.

## ToDos

- [x] #2448
- [x] #2449

## Designs/sketches

TBD

## Links

https://www.notion.so/safe-global/Human-readable-tx-descriptions-8ede96b840584c96a8c58b546a59d921

**Comment by mgarciap** [comment]
The Notion link is not working: `You do not have access to this page.`
https://www.notion.so/safe-global/Human-readable-tx-descriptions-8ede96b840584c96a8c58b546a59d921
