### ISSUE TITLE
Migrate `safe-react-components` to `safe-wallet-web`

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2028]
## What is the feature about

We migrated often used components here to https://github.com/safe-global/safe-react-components. Since doing so, however, we have encountered several issues; missing `key`s, difficulty updating the theme, etc. After discussion, we've agreed that moving them back here makes the most sense.

We should consider that projects likely want to import the components still and research into this should also be taken into account, e.g. tree-shaking, etc.

## The list of requirements

- [ ] Migrate components and theme from `safe-react-components` here.
- [ ] Investigate installing the above in other repos from here.

**Comment by katspaugh** [comment]
Done in #3038 and earlier PRs.
