### ISSUE TITLE
Safe creation via relayer on GC is failing

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/safe-wallet-web#2029]
## Bug description

Error message when trying to create a Safe via the relayer

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: GC

## Steps to reproduce
 1. Go to https://app.safe.global/new-safe/
 2. create a 1/1 Safe

## Expected result

Successfully created Safe

## Obtained result

<img width="1456" alt="Screenshot 2023-05-23 at 14 45 57" src="https://github.com/safe-global/safe-wallet-web/assets/93598450/e3c936d5-b826-432e-a76b-bf7505aa6423">

**Comment by iamacook** [comment]
I'm going to close this as it has resolved itself.
