### ISSUE TITLE
Use onboard's native wallet reconnection

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2042]
## What is the feature about

We use proprietary logic to reconnect to the last used wallet (`lastWalletStorage`). Newer versions of `@web3-onboard` [include `autoConnectLastWallet`](https://onboard.blocknative.com/docs/modules/core#connect) which we may be able to leverage instead.

## The list of requirements

- Investigate the feasibility of migrating to `autoConnectLastWallet`
- If possible, remove `lastWalletStorage` and related logic

## Links

- [Documentation](https://onboard.blocknative.com/docs/modules/core#connect)

**Comment by katspaugh** [comment]
Closing because we have a lot of custom logic related to wallet connection.
