### ISSUE TITLE
[Tx Flow] Replace TX Screen

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#2058]
## What is the feature about

The Replace transaction screen needs to be adjusted for the new tx flow

## The list of requirements

- Move overview stepper to the sidebar
- Add Illustration

## Designs/sketches
<img width="671" alt="Screenshot 2023-05-30 at 10 37 21" src="https://github.com/safe-global/safe-wallet-web/assets/5880855/f58eda3b-7318-4f24-b5f4-03ba9a8a28ba">

**Comment by DiogoSoaress** [comment]
We should hold off this task until designs from @liliiaorlenko are final?

**Comment by liliiaorlenko** [comment]
> We should hold off this task until designs from @liliiaorlenko are final?

yes pls, I would need to work on it more!

**Comment by usame-algan** [comment]
I've moved the screen into the `TxLayout` on a new branch but since the design is not finalised yet I suggest we move this ticket back until its unblocked.
