### ISSUE TITLE
CSS bug in pending txs Dashboard widget

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2060]
<img width="540" alt="Screenshot 2023-05-30 at 12 34 11" src="https://github.com/safe-global/safe-wallet-web/assets/381895/8ddf7e93-ca7d-4047-b4a9-fceee79934af">

There's too much white space on the left, and the right part is cramped. Items should be evenly spread instead.

**Comment by ElizabethOgbee** [comment]
I would like to work on this issue if it hasn't been assigned yet

**Comment by iamacook** [comment]
> I would like to work on this issue if it hasn't been assigned yet

We'd welcome your contribution! Please let us know if you need any help!

**Comment by ElizabethOgbee** [comment]
I will

**Comment by ElizabethOgbee** [comment]
![Screenshot (187)](https://github.com/safe-global/safe-wallet-web/assets/97669038/7c005e62-bae1-4064-9124-09e781bd1332)
 I have interacted with the website from my local host and I can't find the exact component I'm to work with . I will be happy if more info is provided. Thanks

**Comment by iamacook** [comment]
The widget in question is `PendingTxsList`, located on the dashboard (`/home`):

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/205db346-c2c3-4452-9e20-bd4ff587c83d)

**Comment by ElizabethOgbee** [comment]
Thanks

**Comment by iamacook** [comment]
> I'm trying to send a transaction to another account using sapoila testnet in order to view the changes that I am suppose to make but I keep getting this error

Ensure you have an [Infura API key](https://github.com/safe-global/safe-wallet-web#environment-variables) in your env. vars.

**Comment by ElizabethOgbee** [comment]
I added infura API key but its still not working and I keep getting this error "This transaction will most likely fail. To save gas costs, avoid creating the transaction.
The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up."

**Comment by katspaugh** [comment]
You can just open an existing Safe account like this one: https://app.safe.global/home?safe=eth:0x5f9ee776B85f1aFF123f935C48C528D00a62B0ad

It already has a few transactions in the widget.

**Comment by ElizabethOgbee** [comment]
Alright

**Comment by ElizabethOgbee** [comment]
I successfully made a transaction and i Fixed the issue aready
![Picture1](https://github.com/safe-global/safe-wallet-web/assets/97669038/ff4bac5b-dc29-4892-8a64-22c8f2635292)

**Comment by katspaugh** [comment]
On your screenshot, it looks like the green box is now too far from the arrow.
<img width="322" alt="Screenshot 2023-07-03 at 09 42 32" src="https://github.com/safe-global/safe-wallet-web/assets/381895/195558f9-3538-4917-9e5e-453768d8e093">

Anyway, please open a PR and we'll review your code.

**Comment by ElizabethOgbee** [comment]
Okay I will fix it and create a PR
