### ISSUE TITLE
Opensea buttons not working (error 404)

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2078]
## Bug description
Opensea buttons not working (error 404)
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to the NFT page for the safe with NFTs
 2. click Opensea button 
 
Current result:  https://opensea.io/assets/0xc1Caf0C19A8AC28c41Fe59bA6c754e4b9bd54dE9/2168 - 404 error
same on zerion  - https://app.zerion.io/nfts/ethereum/0xc1caf0c19a8ac28c41fe59ba6c754e4b9bd54de9:2168
## Expected result
Make sure that the NFT token details is opened on the Opensea

support ticket - https://github.com/5afe/safe-support/issues/203

**Comment by katspaugh** [comment]
Fixed here: https://github.com/safe-global/safe-wallet-web/pull/2065/commits/1453c3d9092cda35826f6463e73ec8d41ff83d32

**Comment by francovenica** [comment]
Can confirm the fix is fine the RC v1.12, so once that is deployed it will be fixed in prod.
