### ISSUE TITLE
Why can't I see my contract method name?

### ISSUE THREAD

**Issue by nick-zkp** [safe-global/safe-wallet-web#2131]
## Description
When I use safe to execute a successful contract call, but I can't see the name of the contract method on the front end?
Please describe concisely the bug you have found.

## Environment
Goerli network

## Steps to reproduce

If applicable, please provide a screenshot or small video reproducing the bug.
Provide as much information as necessary to reproduce the bug.

## Expected result

Please describe concisely what you expect instead.

## Additional context
My contract has been verified on blockscan.The contract address is "0x6AB36dE1724AcA4abc94CEfd505aC16AB770818f".
![1685752875671](https://github.com/safe-global/safe-core-sdk/assets/88881925/787ffd18-3941-40bd-acac-f490398d26d6)

**Comment by iamacook** [comment]
@nick-zkp, we've updated the ABI of the contract. Can you please confirm if you are now seeing the methods?

**Comment by iamacook** [comment]
@nick-zkp, I'm going to close this as the methods [are appearing in the UI](https://app.safe.global/transactions/history?safe=gor:0x626DddE5e3f51F04bC7A4C4c097B61935FdC37e2). If you experience any further issues, do not hesitate to get in touch.
