### ISSUE TITLE
WC v2 - key.pairing error in console

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2137]
## Bug description
There is an error that shows when you connect with WC v2. It is easier to see when you connect with another safe as owner.
This doesn't affect the use of the safe, tx works fine.
This ticket is just to see how much of an issue this error in the console is

## Environment
 - Browser: any
 - Wallet: any
 - Chain: Ethereum mainnet
 - Env: This ticket https://github.com/safe-global/safe-wallet-web/pull/2095

## Steps to reproduce
 1. Go to the web app
 2. Open 2 safes in different windows
 3. Open the WC app in one of them
 4. In the other window open the connect modal, choose WC and copy the code
 5. Paste it in the WC app in the 1st window
 6. Check the console where you connected the account

## Expected result
No errors in the console

## Obtained result
a "key.pairing" error shows

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/c9ad05ea-6677-4c58-9a81-80786c9919b0)

**Comment by iamacook** [comment]
After looking into this, I believe [a fix for this](https://github.com/WalletConnect/walletconnect-monorepo/pull/2684) has already been merged by WC. However, we have to first wait for their release and the subsequent one from onboard for us to then update.
