### ISSUE TITLE
EIP1271 signatures not working with Safe 1.1.1 and OpenSea

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2161]
After signing a login message, OpenSea's popup is still hanging.
<img width="594" alt="Screenshot 2023-06-23 at 14 28 19" src="https://github.com/safe-global/safe-wallet-web/assets/381895/3ef5e209-9898-4002-9a71-4fea39cddb11">

**Comment by andyrobert3** [comment]
how did you recreate this issue? 

I tried with Gnosis Safe (Wallet Connect), and it worked fine
@katspaugh please share

**Comment by katspaugh** [comment]
It has to be a 1.1.1 Safe as the title mentions.

**Comment by andyrobert3** [comment]
how do we create a Safe Wallet with a specific version @katspaugh, in this case v1.1.1

**Comment by katspaugh** [comment]
This issue isn't really a good one to tackle as an external contributor. I recommend checking the ones with the `good first issue` label. Cheers.

**Comment by usame-algan** [comment]
Can confirm this still happens with the native WC implementation and a 1.1.1 safe. OpenSea shows a "Not authorized" Notification after signing the message.

<img width="469" alt="Screenshot 2024-01-11 at 13 59 53" src="https://github.com/safe-global/safe-wallet-web/assets/5880855/90889277-9d0d-4aa5-8b01-6c1d355e8180">

**Comment by katspaugh** [comment]
I suggest we close this as not planned. We haven't gotten complaints from actual users, so I don't think it's an issue people care about.
