### ISSUE TITLE
ERC20 Approval txs stuck in Safe 

### ISSUE THREAD

**Issue by daveai** [safe-global/safe-wallet-web#2165]
Trying to approve ERC20 LP tokens to Balancer on Gnosis Chain, using the GC Relayer service seems to brick the app.

The relayer executed the txs, but the approval is not recognised on the Balancer UI and the approval stays stuck on the Safe Transactions "Queue" even though the relayer already executed it (being unable to manually execute it, as it already has, the Safe becomes temporarily unusable). After an hour or so the txs disappears i.e. doesn't show up neither in "Queue" nor in "History".

**Comment by katspaugh** [comment]
It seems to be related to temporary indexing issues on the backend that we're experiencing atm.
The backend team are looking into it. Closing this issue since it's not frontend-related. Thanks for the report!
