### ISSUE TITLE
How to add Binance Smart Chain to Chain List of Safe Web?

### ISSUE THREAD

**Issue by jeksman** [safe-global/safe-wallet-web#2182]
i created my own instance of [Safe Wallet Web](https://github.com/safe-global/safe-wallet-web) and for now i have only 4 networks in network selector Network selector in Safe Wallet Web

[Network selector](https://i.stack.imgur.com/u0y5n.png)

Can you please advise on how to modify the network list? How to add or remove networks? e.g i need to add Binance Smart Chain, and remove all test networks

Thank you in advance

**Comment by katspaugh** [comment]
It looks like your instance is targeting the staging backend (which is the default when you run it locally).
You should run the app in production mode or set your own GATEWAY_URL_STAGING.
