### ISSUE TITLE
Disallow inserting the app in an iframe

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2200]
Add this to our existing CSP meta tag:

```
# Only allow my site to frame itself
Content-Security-Policy: frame-ancestors 'self'
```

Test it, if it doesn't work, we'll add a header on the infra instead.

See https://infosec.mozilla.org/guidelines/web_security#x-frame-options

**Comment by schmanu** [comment]
@katspaugh It is neither possible to set the CSP frame-ancestors policy nor the X-Frame-Options through meta tags.

Resources on this:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors
  > This directive is not supported in the [meta](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) element.
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
  > Note: Setting X-Frame-Options inside the [<meta>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta) element is useless! For instance, <meta http-equiv="X-Frame-Options" content="deny"> has no effect. Do not use it! X-Frame-Options works only by setting through the HTTP header, as in the examples below.

I will ask in the infra channel if they can add that header.
