### ISSUE TITLE
Ensure that new safes created with the latest version supported by the services

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-wallet-web#2207]
## What is the feature about
https://github.com/safe-global/safe-deployments/pull/248 is soon to be released, and that will switch the default Safe version returned by the deployments package to 1.4.1. 1.4.1 is not supported by the services yet, so the interface needs to ensure it uses the latest supported version.

## The list of requirements
- Pin the deployed Safes version to the latest supported one by the services (1.3.0 at the moment of writing)

**Comment by katspaugh** [comment]
We also need to check that the Core SDK still works as expected.
