### ISSUE TITLE
chore: remove resolution once onboard/trezor module is updated

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-wallet-web#2258]
## Description

We added a remporary yarn resolution for this issue:
https://github.com/trezor/trezor-suite/pull/8873

As soon as the dependency is updated on trezor's side and the @web3-onboard/trezor gets updated, we should update the trezor module and remove the resolution.

**Comment by liliya-soroka** [comment]
@schmanu is it still relevant ?

**Comment by katspaugh** [comment]
Looks like those modules will never be updated. Onboard moved on to a WalletConnect-based implementation which our users don't want. So I'd close this as wontfix. Looks like we're stuck with those legacy modules until they stop working.
