### ISSUE TITLE
[Tx flow] Simulation not reset when changing gas limit

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-wallet-web#2303]
## Bug description
After changing the gas limit the Tx Simulation status is not reset.
We pass the gas limit to the simulation because we had some problems with computing it correctly in the past on some chains. 
The simulation can be a handy tool to figure out a correct gas limit in such cases.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Open tx execution modal
 2. Simulate the tx
 3. Change the gas limit to something too low
 4. The tx can not be re-simulated. It still says "Success"

## Expected result
- After changing the gas limit, the tx can be simulated again.

## Obtained result
- It still shows the previous simulation result

**Comment by usame-algan** [comment]
After the tx flow revamp, we are not passing the gas limit to the simulation anymore so I suggest either passing it again and resetting the simulation when it changes or always relying on the block gas limit for simulation and not resetting. Question is if the simulation would catch something that the `isValidExecution` doesn't

**Comment by katspaugh** [comment]
Another thing is that the simulation is now decoupled from execution. We run it also when creating/signing, where there's no gas estimation yet.
