### ISSUE TITLE
Created Safes not added to `addedSafes`

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2313]
## Bug description

When creating a Safe, it is not always added to the store.

## Steps to reproduce
 1. Create a Safe and observe that it is not present in the sidebar.

## Expected result

Safe is present in the sidebar after creation.

## Obtained result

Safe is not always present in the sidebar after creation.

**Comment by katspaugh** [comment]
Likely a duplicate of #1986.

**Comment by katspaugh** [comment]
Manu: could be related to closing the browser during the Safe creation.
