### ISSUE TITLE
[Tx flow] The same owner can sign tx a few times

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2321]
## Bug description
The same owner can sign tx a few times
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Create tx as an owner 1
 2. switch MM account from the owner 1 to the owner 2 
 3. click Sign created tx
 4. switch MM back to the owner 1
 Current result: The submit button is available, and the same owner can click the sign again 

## Expected result
The sign button should be disabled on the Tx modal if the owner already signed the tx
## Screenshots
https://drive.google.com/file/d/1tbTvTBJ2ILOllDQIhIdyIa4Bo3sLmoNf/view?usp=sharing

**Comment by katspaugh** [comment]
Technically, nothing bad will happen if you sign a tx with the same owner twice. It will just overwrite the first signature.
But still good to warn about that.
