### ISSUE TITLE
Recomended nonce when the queued tx is 0

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2326]
## Bug description
When a tx is created it should be recomended for the user a nonce +1 of the latest tx in the list. This doesn't happen if the latest tx is 0. It will recomend again the nonce 0 when creating a new transaction

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Any
 - Env: Current prod build 1.15.1

## Steps to reproduce
 1. Create a new safe or have a safe with no tx created yet
 2. Create and queue any tx. It should be nonce 0
 3. Try to create a new tx and check the recomended nonce

## Expected result
It should recomend nonce 1

## Obtained result
Recomends nonce 0

## Screenshots
![not recomended nonce](https://github.com/safe-global/safe-wallet-web/assets/4503659/f9dfc024-7935-4cb8-b2f7-1cb8c7bae7de)

**Comment by katspaugh** [comment]
This seems to be a CGW bug.
Here's a curl:
```
curl 'https://safe-client.safe.global/v2/chains/100/safes/0x229C53Ed588ae1593886fCfaC040113E9ac62903/multisig-transactions/estimations' \
  -H 'authority: safe-client.safe.global' \
  -H 'accept: */*' \
  -H 'accept-language: en' \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'origin: https://app.safe.global' \
  -H 'pragma: no-cache' \
  -H 'referer: https://app.safe.global/' \
  -H 'sec-ch-ua: "Not/A)Brand";v="99", "Google Chrome";v="115", "Chromium";v="115"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36' \
  --data-raw '{"to":"0x229C53Ed588ae1593886fCfaC040113E9ac62903","value":"0","data":"0x","operation":0}' \
  --compressed
```

It returns
```
{"currentNonce":0,"recommendedNonce":0,"safeTxGas":"86353"}
```

Despite this Safe having a transaction queued with nonce 0.

**Comment by katspaugh** [comment]
Will be solved on the CGW side.
