### ISSUE TITLE
Queued txs duplicated while being executed

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2329]
## Bug description
While the batch tx are being executed they show duplicated in the queue tab.

## Environment
 - Browser: Chrome
 - Wallet: any
 - Chain: any
 - Prod env: 1.15.2 (This issue is older than this version)

## Steps to reproduce
 1. Go to a safe and create 2 tx with consecutve nonce and queue them
 2. Execute the batch

## Expected result
Only the 2 tx shown in the queue should be present

## Obtained result
The tx duplicate. Even the title "Queued" and "next" show, so it seems the whole list is displayed again

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/aff51932-d45a-4110-8eec-c8ca589329f1)

**Comment by katspaugh** [comment]
Looks like the duplicates are from `usePendingTxsQueue` which is supposed to display only untrusted immediate executions in 1/N Safes.

<img width="533" alt="Screenshot 2023-07-31 at 11 13 37" src="https://github.com/safe-global/safe-wallet-web/assets/381895/981b1221-8388-4a1e-b9d8-8f985896cfdb">

**Comment by katspaugh** [comment]
@francovenica this is fixed on CGW, you can test it on dev.

**Comment by francovenica** [comment]
This one looks good in 2353.
