### ISSUE TITLE
Update `@safe-global/safe-apps-sdk` to the latest version

### ISSUE THREAD

**Issue by mmv08** [safe-global/safe-wallet-web#2337]
## What is the feature about
Updating the safe apps SDK to the latest version (8.0.0 when creating the issue). It should fix bugs like:
- https://github.com/safe-global/safe-apps-sdk/issues/480

## The list of requirements
- Update safe apps SDK to the latest version

## Links
- https://www.npmjs.com/package/@safe-global/safe-apps-sdk

**Comment by Argeare5** [comment]
this error is still present
