### ISSUE TITLE
[Both modes] Checkboxes in the Preferences > Cookies page are invisible when checked

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2344]
## Bug description
In the preferences page, the checkboxes in the cookies page are invisible when checked. (They are there, is just that you have to hover them to see them)

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any
 - Env: Prod 1.15.2

## Steps to reproduce
 1. Go to prefences page > Cookies
 2. Check the checkboxes there

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/a98805be-3b9b-4046-8d78-c6cbaf98bb65)

**Comment by liliya-soroka** [comment]
![image](https://github.com/safe-global/safe-wallet-web/assets/338622/fe45a9d3-7ce6-4f10-93ff-8135ac5d538a)
