### ISSUE TITLE
[Safe creation] Predicted Safe address is wrong on zkSync

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2370]
During a Safe creation on zkSync, we show the future Safe address and it's different from the actual resulting address.

See https://5afe.slack.com/files/U03DA8MS83Z/F05MHA2V52L/zksync_safe_creation.mp4

**Comment by iamacook** [comment]
We are leveraging the [SDK to predict this](https://github.com/safe-global/safe-wallet-web/blob/consistent-provider/src/components/new-safe/create/logic/index.ts#L76-L81). We should check if updating it fixes it.

**Comment by katspaugh** [comment]
@germartinez is it fixed in the SDK?

**Comment by germartinez** [comment]
Not fixed in the SDK. This is must be related to this specific network and the SDK didn't have their test suite run against zkSync

**Comment by katspaugh** [comment]
OK, thanks, please keep us posted. We might have to hide this predicted address on zk-chains for the time being, then.
