### ISSUE TITLE
[Epic] Push notification

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2391]
Create a push notification system using Firebase + tx-service.

Notion: https://www.notion.so/safe-global/Notifications-e0c4cc7d9f5748199d7b215bde6c3984

Designs: tbd

**Comment by liliiaorlenko** [comment]
pls check the design:
[on screen](https://www.figma.com/file/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?type=design&node-id=1%3A15710&mode=design&t=WvRp4UBRTJpR6a4Q-1)
[states](https://www.figma.com/file/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?type=design&node-id=1%3A16071&mode=design&t=WvRp4UBRTJpR6a4Q-1)
