### ISSUE TITLE
Cannot connect from MetaMask mobile via WalletConnect V2

### ISSUE THREAD

**Issue by ElvisKrop** [safe-global/safe-wallet-web#2435]
## Bug description
I'm unable to establish a connection via WalletConnect V2 from MetaMask mobile on https://app.safe.global.
Just to proof that MetaMask on my mobile is working well, I was able to complete the same steps on https://app.uniswap.org.

## Environment
 - Browser: Chrome / Brave / Firefox (I think any)
 - Wallet: WalletConnect V2 + Mobile MetaMask on Android
 - Chain: Any

## Steps to reproduce
 1. Go to https://app.safe.global;
 2. Click on "Connect Wallet";
 3. Select "WalletConnect" option from the modal;
 4. open the MetaMask on your mobile phone;
 5. scan the proposed qr-code from the desktop screen;

## Expected result
User should be able to connect the MetaMask mobile wallet via WalletConnect.

## Obtained result
Unable to establish a connection via WalletConnect V2 from MetaMask mobile.

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/47831692/c43cca2f-b4e5-4a7b-ae31-b11a584a403e)

There are a few errors in the console:
![image](https://github.com/safe-global/safe-wallet-web/assets/47831692/5a00e94d-c6d2-4bc5-badf-8943afd28c91)

**Comment by katspaugh** [comment]
@francovenica could you check if you can reproduce this?

**Comment by francovenica** [comment]
Yes, is like that in Prod.

**Comment by katspaugh** [comment]
I've also reproduced this with the iOS MetaMask.

**Comment by katspaugh** [comment]
Looks like it's a [web3-onboard bug](https://github.com/blocknative/web3-onboard/issues/1783), looking for a solution.
