### ISSUE TITLE
[EIP1271] Show a sharable link when signing a message

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2437]
User feedback:

> When signing a message, the user was unsure how the other signers would be able to sign. Especially since there was not way to share a link like it is possible when signin txs.

Let's show a sharable link to the transaction as soon as it's proposed.

## Designs
[screen view](https://www.figma.com/file/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?type=design&node-id=1%3A15710&mode=design&t=FLMcU43UXdbatjOb-1)
[states](https://www.figma.com/file/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?type=design&node-id=1%3A16071&mode=design&t=FLMcU43UXdbatjOb-1)

**Comment by liliiaorlenko** [comment]
Prepared the design, pls check
[screen view](https://www.figma.com/file/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?type=design&node-id=1%3A15710&mode=design&t=FLMcU43UXdbatjOb-1)
[states](https://www.figma.com/file/cMDccuR9aZFqAiBd4dKsKg/Transaction-flow?type=design&node-id=1%3A16071&mode=design&t=FLMcU43UXdbatjOb-1)

**Comment by katspaugh** [comment]
Closing as a duplicate of #2020.
