### ISSUE TITLE
/new-safe/load does not support address parameter

### ISSUE THREAD

**Issue by biafra23** [safe-global/safe-wallet-web#2438]
## Bug description

When clicking this link: https://safe-wallet-web.dev.5afe.dev/new-safe/load?chain=eth&address=0x308686553a1EAC2fE721Ac8B814De638975a276e 

The upcoming page is supposed to prefill chain and address. But it only selects the chain

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to https://app.safe.global/new-safe/load?chain=eth&address=0x308686553a1EAC2fE721Ac8B814De638975a276e 

## Expected result

chain and address are prefilled (only the name has to be added by the user)

## Obtained result

Only chain is selected.

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/246473/4161d183-3aa3-44c0-9463-dae4560399c1)

**Comment by katspaugh** [comment]
Thanks Dirk, we'll take a look.
Just to clarify, when you say "page is supposed to prefill chain and address", do you mean that the Safe mobile app relies on this behavior? Is this documented anywhere on your side, i.e. is there a list of URLs that you expect us to support?

**Comment by biafra23** [comment]
> Just to clarify, when you say "page is supposed to prefill chain and address", do you mean that the Safe mobile app relies on this behavior? Is this documented anywhere on your side, i.e. is there a list of URLs that you expect us to support?

No. That is just what Aaron said should happen. And as a user I would like this to happen as well.

**Comment by katspaugh** [comment]
True, there's even code for it but it's not working: https://github.com/safe-global/safe-wallet-web/blob/dev/src/pages/new-safe/load.tsx#L8-L9

**Comment by DmitryBespalov** [comment]
What do you think of adding the `chain` parameter to the `/new-safe/create`? Would it have any use?

**Comment by katspaugh** [comment]
The `chain` param works on any route that doesn't have a `safe` param. E.g. https://app.safe.global/new-safe/create?chain=gno
