### ISSUE TITLE
Batch indicator badge is not clear

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2442]
## Bug description

When a transaction is batched, the badge in the indicator should be the primary green but it is currently white.

## Steps to reproduce
 1. Ensure dark mode is enabled.
 2. Batch a transaction.
 3. Observe the white badge in the indicator.

## Expected result

Badge is primary green.

## Obtained result

Badge is white.

## Screenshots

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/d24e29d3-dd99-4cb8-bcbe-f76366e6e6b4)

**Comment by PrabalParihar** [comment]
@iamacook 
I am interested in this issue 
Would you be able to assign this issue to me so I can go further?

**Comment by iamacook** [comment]
> @iamacook I am interested in this issue Would you be able to assign this issue to me so I can go further?

@PrabalParihar, please feel free to submit a PR. We'd welcome your contribution!

**Comment by iamacook** [comment]
I'm going to close this as https://github.com/safe-global/safe-wallet-web/pull/2646 fixed the issue.
