### ISSUE TITLE
Notification list overflows the viewport in mobile

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2446]
## Bug description

Tested with the Chrome mobile emulator, using "iPhone 12 pro" with 390 x 844 resolutioni

## Environment
 - Browser: Chrome
 - Wallet: any
 - Chain: any
 - Env: Prod 1.17

## Steps to reproduce
 1. Open notifications in the mobile viewport (it can be empty, no need to have notifications in it)

## Obtained result
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/af7594e9-a39a-4728-a18d-37d6532716f5)

**Comment by KaushikKC** [comment]
I would like to do this issue.
Can you assign me this issue?

**Comment by katspaugh** [comment]
Go ahead, @KaushikKC

**Comment by iamacook** [comment]
I'm going to close this as the [changes have been merged](https://github.com/safe-global/safe-wallet-web/pull/2469#issuecomment-1723122236).
