### ISSUE TITLE
Human-readable descriptions v1

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#2448]
## What is the feature about

This feature is part of the Epic #2011 and aims to add a first version of human-readable descriptions on the CGW and Web UI.

### CGW
https://github.com/safe-global/safe-client-gateway-nest/pull/631
- Create a structure to define messages for ABI calls
- Define messages for ERC20 and Safe transactions
- Implement parser and components for messages
- Return human descriptions as a simple string

### Web UI
- Add human descriptions to nonce replacement form, notifications

## Links

https://www.notion.so/safe-global/Human-readable-tx-descriptions-8ede96b840584c96a8c58b546a59d921

**Comment by HAAH10** [comment]
###

**Comment by HAAH10** [comment]
@**
