### ISSUE TITLE
The alert must be accepted twice when exiting a tx form

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2471]
## Bug description

If you try to exit a tx form, a browser alert is shown asking the user if he's sure to exit. the alert must be clicked twice for it to go away

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet
 - Env: prod 1.17.1 

## Steps to reproduce
 1. Go to any safe
 2. Start any type of tx
 3. Exit the form by going somewhere else in the app
 4. The alert shows up
 5. Click in "Ok"

## Expected result
Alert closes and the user is redirected

## Obtained result
The alert must be clicked twice

## Screensho
![alert](https://github.com/safe-global/safe-wallet-web/assets/4503659/537da725-ee50-4193-be23-1d80d0fefc05)
ts

**Comment by iamacook** [comment]
I am unable to reproduce this. Can you test it again @francovenica?

**Comment by francovenica** [comment]
I can't reproduce it anymore either, maybe it was fixed as a side effect of another PR. I'll close  it
