### ISSUE TITLE
Minor enhancement for mobile view: Welcome screen ordering 

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/safe-wallet-web#2473]
## What is the feature about

<img width="580" alt="Screenshot 2023-08-30 at 18 07 06" src="https://github.com/safe-global/safe-wallet-web/assets/93598450/e532385f-19f7-40c8-a300-81bff4bfdb6b">

rearranging the order of welcome to safe and data import.

**Comment by udhaykumarbala** [comment]
Hi @katspaugh, pushed a PR for this #2474 . Happy to contribute more 😇

**Comment by udhaykumarbala** [comment]
hey folks, can you help me sign the CLA

**Comment by johannesmoormann** [comment]
@udhaykumarbala that was quick. big thanks!
