### ISSUE TITLE
Emojis not working in a lot of addresses

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2475]
## Bug description

Emojis are not showing in a lot of addresses

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet
 - Env: Prod 1.17.1

## Steps to reproduce
 1. Add these addreses

This one has it: 
eth:0x8675B754342754A30A2AeF474D114d8460bca19b

All these do not:
eth:0x7724b234c9099C205F03b458944942bcEBA13408
eth:0x49d4450977E2c95362C13D3a31a09311E0Ea26A6
eth:0x0E24B6e3BefF0b44b773F068343Bc2CB56cB3769
eth:0x9cf2288d8FA37051970AeBa88E8b4Fb5960c2385

## Expected result
All of them should have an emoji

## Obtained result
Few of them have it

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/6ee20209-71e6-41cc-9578-234e6b30dde0)

**Comment by katspaugh** [comment]
They are only shown for the Safes you have added.
