### ISSUE TITLE
safe creation on Base: `err: max fee per gas less than block base fee`

### ISSUE THREAD

**Issue by firnprotocol** [safe-global/safe-wallet-web#2481]
## Bug description

Upon creation of a new safe on Base Mainnet, I get an error toast saying: "Your transaction was unsuccessful. Reason: Details: Internal JSON-RPC error." upon inspecting the console, I have an RPC error returned by MetaMask:
```javascript
{
  code: -32603,
  data: {
    code: -32000,
    message: "err: max fee per gas less than block base fee: address 0x70bFF9998d4e4788B1f1581e66900F0d1802a130, maxFeePerGas: 100000000 baseFee: 105514391 (supplied gas 15010499)"
  },
  message: "Internal JSON-RPC error."
}
```
it looks like the UI is somehow miscalculating the max (priority fee per) gas.

experimentally, the "baseFee" varies from around 103,000,000 to 130,000,000; i've been trying this repeatedly for about 30 minutes.

## Environment
 - Browser: Chrome 116.0.5845.110
 - Wallet: MetaMask 10.35.0
 - Chain: Base

## Steps to reproduce
 1. create a new safe on Base. i am doing a 2/2 safe, though I doubt it matters.

## Expected result
success

## Obtained result
see above

## Screenshots

<img width="1792" alt="Screenshot 2023-08-31 at 10 05 18 PM" src="https://github.com/safe-global/safe-wallet-web/assets/93839494/bde4bade-949b-4620-bace-640115f41d1c">

**Comment by katspaugh** [comment]
Thanks! We’ll adjust it.

**Comment by firnprotocol** [comment]
np! worked for me.
