### ISSUE TITLE
[NFT page] Page not responding error

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2482]
User was trying to send NFTs and was stuck at signing for 10-15 minutes before a successful transaction execution. But checking on transactions tab, page seemed to be stuck and getting "Page not responding" pop up. Tried clicking on assets tab and the UI is stuck again. User has 6000+ NFTs, does this affect how the page loads? I tried loading his safe on my end from different browsers (even on private browser) and I'm getting the same issue on my end as well.

User is using Chrome on Ubuntu 20.04, while I tried Edge and Firefox on my end.

Safe address: https://app.safe.global/balances/nfts?safe=gor:0x41cec4Cd8b75308586C151839c314BCf4d98069D

**Comment by usame-algan** [comment]
Discussion on slack: https://5afe.slack.com/archives/C04MJJM9S3U/p1692105856091939

**Comment by liliya-soroka** [comment]
done
