### ISSUE TITLE
Don't fetch txDetails for Batch Execute

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#2487]
This issue is currently blocked by #2011 

## What is the feature about

We fetch txDetails for every transaction that is part of the batch when using Batch Execute in the UI. This is because we need the `dataDecoded` in order to display what each transaction does (method name, parameters). Once Human-readable transactions are implemented we will have access to that information without having to fetch `txDetails`.

## The list of requirements

- Remove txDetails requests from Batch Execute
- Use `txInfo.humanDescription` or `txInfo.richInfo` instead

**Comment by usame-algan** [comment]
This would also address https://github.com/5afe/safe-support/issues/269

Discussion on [Slack](https://5afe.slack.com/archives/C04MJJM9S3U/p1692083488828649)

**Comment by iamacook** [comment]
It looks like we will need to fetch them for execution as we [extract the arguments of a transaction](https://github.com/safe-global/safe-wallet-web/blob/dev/src/utils/transactions.ts#L112) from the `txDetails`.
