### ISSUE TITLE
Effects depending on `txHistoryTag` run with every Safe info poll

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2490]
## Bug description

We often use the `txHistoryTag` as a dependency for effects that poll, e.g. the [Safe token balance](https://github.com/safe-global/safe-wallet-web/blob/dev/src/hooks/useSafeTokenAllocation.ts#L154).

However, for Safes that have no historical transactions, the gateway returns the current timestamp as the `txHistoryTag`. This means with every Safe info poll, the effects that depend on the `txHistoryTag` run.

We should check the existence of historical transactions in order to use this tag as a dependency (and potentailly the same for queue), e.g. `txHistory.page?.results?.length > 0 && safe.txHistoryTag`.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Open a Safe with no historical transaction.
 2. Observe consistent polling of token allocation.

## Expected result

Effects that rely on `txHistoryTag` only updated when a historical transaction is added.

## Obtained result

Effects run with every Safe info poll.

**Comment by usame-algan** [comment]
This also happens for the `txQueuedTag` and the `collectiblesTag` respectively. Can we extend the title and description to reflect this?

**Comment by fmrsabino** [comment]
To give some more context on the current state of the tags on the CGW:

- `txHistoryTag` – currently returns the UNIX timestamp of the latest transaction or `null` if there are no transactions.
- `collectiblesTag` – currently returns the UNIX timestamp of the execution date of the latest collectible transfer or `null` if there are no transfers.
- `txQueuedTag` – currently returns the UNIX timestamp of the most recently modified transaction in the queue or `null` if there are no transactions in the queue.
- `messagesTag` – currently returns the UNIX timestamp of the most recently modified message or `null` if there are no messages.

Therefore the check suggested to be done on the frontend shouldn't be required.

> the gateway returns the current timestamp as the txHistoryTag

This information also seems to be outdated.

Let me know if there was anything unclear!

**Comment by katspaugh** [comment]
I'll close it then, thanks Fred!

**Comment by usame-algan** [comment]
Thanks for the explanation @fmrsabino!
Is this deployed on staging and prod? I was testing https://github.com/safe-global/safe-wallet-web/pull/2905 today and had the issue of the `queuedTag` still updating to the current timestamp on every safe info poll when the queue of my safe was empty.

**Comment by fmrsabino** [comment]
> Thanks for the explanation @fmrsabino! Is this deployed on staging and prod? I was testing #2905 today and had the issue of the `txQueuedTag` still updating to the current timestamp on every safe info poll when the queue of my safe was empty.

My comment in https://github.com/safe-global/safe-wallet-web/issues/2490#issuecomment-1830236326 was not 100% correct. Even though that's how we compute each tag, there's another fallback which would map it to the current time instead of `null`.

So this is still an issue. Converting it to `null` would be an API breaking change. 

On mobile the tags are not being parsed:
https://github.com/safe-global/safe-ios/blob/505984d4bee362636d23db5c7d94e03a45a18377/Multisig/Data/Services/Safe%20Client%20Gateway%20Service/SCGModels.swift#L548-L559

But in the end this would be an API breaking change if we move away from `string` so we need to be careful on how we proceed.

**Comment by liliya-soroka** [comment]
CGW side was implemented and released. 
cc @usame-algan
