### ISSUE TITLE
CORS issue in production when creating a new wallet

### ISSUE THREAD

**Issue by dszlachta** [safe-global/safe-wallet-web#2494]
## Bug description

When creating a new wallet through `https://app.safe.global/new-safe/create?chain=eth`, the process stops at "Indexing". In Developer Tools, I see CORS error for `https://safe-client.safe.global/v1/chains/1/safes/[redacted]`, then there's a bunch of errors coming from the code (see attached screenshot). The wallet has been created, but the site suggests that it's still indexing.

## Environment
 - Browser: Firefox 118.0b4
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to https://app.safe.global/new-safe/create
 2. Create a new wallet on Ethereum mainnet, 1 owner
 3. Approve smart contract call
 4. The process goes smoothly until it reaches "Indexing"

## Expected result

Wallet creation process ends successfully or I am informed about the errors.

## Obtained result

Wallet is created, but I wasn't informed about it. It looks like "indexing" takes forever.
When I try to access the wallet, it says "This Safe Account couldn't be loaded".

## Screenshots

![Zrzut ekranu 2023-09-6 o 11 49 03](https://github.com/safe-global/safe-wallet-web/assets/2346536/a79f151d-2047-48c3-be1b-e624eda01c1c)

**Comment by katspaugh** [comment]
There's currently a DB upgrade in progress. Should be over soon. Sorry for the trouble.
