### ISSUE TITLE
Filter: Contract addresses are not seen fully for all filter types 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2507]
## Bug description
Filter: Contract addresses are not seen fully for all filter types
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: any

## Steps to reproduce
 1. Go to the history tab
 2. open filter 
 3. try all filter where the address is one of the options for filtering
Current result: The address is not seen fully as in the drop-down with the addresses from the addressbook, as in the field
## Expected result
1. the whole address should be seen in the drop-down
2. as an idea, we can  truncate the address in the "address" field to show first symbols and last 4 symbols
## Screenshots
<img width="1222" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/ac67aaa3-cadd-41bd-b768-33f746fe2444">

**Comment by usame-algan** [comment]
Seems like the address is truncated at the end now. @liliya-soroka is this ok enough to close the issue?
![Image](https://github.com/safe-global/safe-wallet-web/assets/5880855/92975d7c-0830-40f8-9e81-859b409b0e80)

**Comment by usame-algan** [comment]
Can be retested on dev

**Comment by liliya-soroka** [comment]
Verified.

**Comment by francovenica** [comment]
This was indeed pushed to prod. Looks good there as well. Closing
