### ISSUE TITLE
Filter by the token address doesn't work for the incoming filter

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2509]
## Bug description
Filter by the token address doesn't work for the incoming filter
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: zkSync

## Steps to reproduce
 1. Go to https://app.safe.global/transactions/history?safe=arb1%3A0x861099a9FD94b03471a1002efCa662c3ECAdB10C&type=Incoming&token_address=0x82aF49447D8a07e3bd95BD0d56f35241523fBab1
 2.  the history is filtered by token address+incoming txs  ( 0x82aF49447D8a07e3bd95BD0d56f35241523fBab1)

Request to the CGW - https://safe-client.safe.global/v1/chains/42161/safes/0x861099a9FD94b03471a1002efCa662c3ECAdB10C/incoming-transfers/?safe=arb1%3A0x861099a9FD94b03471a1002efCa662c3ECAdB10C&token_address=0x82aF49447D8a07e3bd95BD0d56f35241523fBab1

Current result: There are next issues:
1. outgoing and incoming txs are displayed ( because sender=receiver)
2. the same txs is displayed twice when the filter is used ( check tx hash). At the same the tx is displayed only once when filter is not used
<img width="1200" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/54531292-3e8b-4bae-94df-48e1691444a2">
4. the filtering by the token address doesn't work - [Wrapped Ether (WETH)](https://arbiscan.io/token/0x82aF49447D8a07e3bd95BD0d56f35241523fBab1) address was used for filtering , but at the result you can see incoming NFT txs and incoming/outgoing txs with other tokens 
<img width="743" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/663c9891-acd6-499d-8d4a-81bd4de35c60">

## Expected result
The filter by token address incoming txs should return only incoming txs with the token address from the filter

**Comment by liliya-soroka** [comment]
CGW issue - https://github.com/safe-global/safe-client-gateway/issues/693

**Comment by katspaugh** [comment]
I don't see it as a major issue as it's not interfering with transaction making.

**Comment by usame-algan** [comment]
> outgoing and incoming txs are displayed ( because sender=receiver)

Do we consider this a bug? What is the expected behaviour?

**Comment by katspaugh** [comment]
No, that part is expected.

**Comment by liliya-soroka** [comment]
closed as fixed on back-end side
