### ISSUE TITLE
cgw service is not working

### ISSUE THREAD

**Issue by zctocm** [safe-global/safe-wallet-web#2516]
## Bug description
I am experiencing errors when deploying a safe-wallet-web to support the BSC Testnet locally.
I have already submitted the transaction to BSC Testnet, the API route: v1/chains/97/safes/address is not working, but the main page of cgw API works.
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: BSC Testnet

## Steps to reproduce
 1. Go to the main page.
 2. Create a safe account.

## Expected result
The cgw API works.

## Screenshots
![CleanShot 2023-09-17 at 16 11 01@2x](https://github.com/safe-global/safe-wallet-web/assets/16474758/2db78b08-c2ba-4af9-8821-21b5c8a1e6e5)
<img width="1634" alt="CleanShot 2023-09-17 at 16 12 15@2x" src="https://github.com/safe-global/safe-wallet-web/assets/16474758/16f1446a-94d0-487f-b667-520f4fed1c7f">
<img width="852" alt="CleanShot 2023-09-17 at 16 17 27@2x" src="https://github.com/safe-global/safe-wallet-web/assets/16474758/c4a146bf-b451-4412-af9c-ee71a6c51a8a">

**Comment by katspaugh** [comment]
CGW depends on the safe-transaction-service, are you also running that locally?
I’d appreciate if you post your questions on ethereum stackexchange. This repo is only for the frontend, not for backend dev support.

**Comment by katspaugh** [comment]
Then you can debug it using the CGW and transaction service logs.
