### ISSUE TITLE
Don't use the word "Confirm"

### ISSUE THREAD

**Issue by SKYBITDev3** [safe-global/safe-wallet-web#2517]
A "confirmation" in relation to blockchain refers commonly to completion of transaction processing by a miner or validator on the blockchain network.

So using the word "confirm" and related words in Safe can cause confusion, especially for newcomers who may already find it difficult enough to set up and use Safe.

Better alternative words for Safe transaction proposal approval may be:
Accept
Agree

I don't suggest "approve" because [approve](https://docs.openzeppelin.com/contracts/4.x/api/token/erc20#IERC20-approve-address-uint256-) is a standard function in token contracts for adjusting spending allowance.

**Comment by katspaugh** [comment]
Thanks for the suggestion! Which project do you represent, if not a secret?

**Comment by SKYBITDev3** [comment]
> Which project do you represent

I'm a technical developer at [SKYBIT](https://SKYBIT.ASIA)

**Comment by katspaugh** [comment]
Gotcha, thanks!
I'm going to close this issue as we're not planning to change the wording in the app in all the places where it's used, but we'll keep your suggestion in mind if we redesign parts of the transaction flow. I think "Accept" is a good alternative to "Confirm" indeed.
