### ISSUE TITLE
Cannot sign via 1inch iOS wallet and WalletConnect

### ISSUE THREAD

**Issue by tschubotz** [safe-global/safe-wallet-web#2531]
## Bug description

Cannot sign via 1inch iOS wallet and WalletConnect

## Environment
 - Browser: Chrome
 - Wallet: 1inch
 - Chain: Ethereum mainnet

## Steps to reproduce
1. I have a Safe on Mainnet with 2/3 owners. 1 owner is a 1inch mobile wallet on iOS
2. Connect to web app the 1inch wallet via WalletConnect
3. Initiate a tx (I did a remove owner tx)
4. Hit "Sign"

## Expected result

Tx can be signed via 1inch wallet.

## Obtained result

unable to sign 

```
Error submitting the transaction. Please try again.
SafeProxy contract is not deployed on the current network
```

## Screenshots
<img width="529" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/1380529/2546a028-7eb8-4b85-b8f2-b43b86dd386a">

## Misc

Interestingly enough it works with 1inch Android.

**Comment by katspaugh** [comment]
The 1inch team said that this is now fixed on their side by patching the WC v2 SDK.
I'll do another test once a new app version is released.

**Comment by katspaugh** [comment]
It works now. I successfully signed a tx on mainnet, and then executed a tx on Polygon from the same WC connection.
