### ISSUE TITLE
Cannot connect Ledger Live using Wallet Connect

### ISSUE THREAD

**Issue by kronosapiens** [safe-global/safe-wallet-web#2538]
## Bug description

Attempting to connect Ledger Nano using Wallet Connect and Ledger Live desktop application. Receive the following error in Ledger Live:

```
Application error: a client-side exception has occurred (see the browser console for more information).
```

The browser console displays the following:

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://verify.walletconnect.com') does not match the recipient window's origin ('https://app.safe.global').
```

## Environment
 - Browser: Brave
 - Wallet: WalletConnect <> Ledger Live
 - Chain: Optimism

## Steps to reproduce
 1. Connect wallet using WalletConnect
 2. Under the "Desktop" options click "LedgerLive"

## Expected result

LedgerLive will connect and I can sign transactions using my Ledger.

## Obtained result

Connection fails.

## Screenshots

<img width="399" alt="Screen Shot 2023-09-23 at 8 51 57 AM" src="https://github.com/safe-global/safe-wallet-web/assets/1874062/75738f18-1c7b-4840-89ac-3566a19238e2">

<img width="737" alt="Screen Shot 2023-09-23 at 8 50 45 AM" src="https://github.com/safe-global/safe-wallet-web/assets/1874062/6c69e561-9dd5-408f-9f9c-c0053790f0b1">

<img width="696" alt="Screen Shot 2023-09-23 at 8 51 08 AM" src="https://github.com/safe-global/safe-wallet-web/assets/1874062/6d64cc4b-bbf3-4ad5-adbf-ad014aa6083b">

**Comment by katspaugh** [comment]
Thanks for the report! This is most likely on the web3-onboard’s side. Does WalletConnect work well with Ledger Live on other sites for you?

**Comment by kronosapiens** [comment]
I'll try and get back to you. So far I've only used it to try and control the Safe.

**Comment by katspaugh** [comment]
Gotcha, thanks. We might have to roll it back to the direct Ledger option.

**Comment by katspaugh** [comment]
I've enabled direct Ledger support on Optimism. ✅ 
Please see if it works for you.

**Comment by kronosapiens** [comment]
Hi @katspaugh, I am able to connect with the direct Ledger option, thank you.

Regarding WalletConnect, is it possible to fix the underlying issue? Or is that a major challenge?

**Comment by katspaugh** [comment]
Thanks for checking!
I’ll keep the issue open then.

**Comment by 8ball030** [comment]
I also have this issue.

I am unable to connect with either wallet connect or direct ledger.

I am running on linux which might explain why direct connect doesnt work.

My error in console after trying to connect is;

```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://verify.walletconnect.com'/) does not match the recipient window's origin ('https://app.safe.global'/).
```

**Comment by 8ball030** [comment]
Currently blocking me unfortunately :'(

**Comment by arein** [comment]
WalletConnect here. We're investigating

**Comment by kronosapiens** [comment]
Hi @arein, I am connecting from the Safe website (https://app.safe.global/home)

**Comment by 8ball030** [comment]
ditto to @kronosapiens

**Comment by arein** [comment]
@8ball030 @kronosapiens is this a new issue ? Has this worked before? just so we don't research the wrong way

**Comment by kronosapiens** [comment]
I have never successfully used WalletConnect to connect my Ledger with Safe.

**Comment by 8ball030** [comment]
Me neither.
Would be very helpful to be able to do so however.
Would like to avoid putting the back up phrase into the safe app as this would kind of defeat the purpose.
Thanks a lot for your help!
Regards, 8baller

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by 8ball030** [comment]
from what i cna see, looks like for somereason the dappUrl isnt getting passed into the wallet connect maybe?>

Or something like is addresses in this pr;

https://github.com/safe-global/safe-wallet-web/pull/2535/commits/62101e5c7e6f3d030bd3ed2440ddcc5e189a03bd

**Comment by arein** [comment]
> I have never successfully used WalletConnect to connect my Ledger with Safe.

That's so disappointing. Sorry about this. We created a backchannel between Ledger/Safe/WalletConnect to get this fixed ASAP

**Comment by arein** [comment]
@kronosapiens Ledger marked the fix as merged. Can you confirm it works now and close the issue if so? 🙏

**Comment by kronosapiens** [comment]
It works! Thank you 🥇
