### ISSUE TITLE
"Replace nonce" option in the nonce dropdown as a extra padding on top

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2577]
## Bug description

Whenver the user edites the nonce of a tx, a dropdown suggesting values show up. When the "Replace nonce" options shows, it has  a padding on top of it that shouldn't be there

## Environment
 - Browser: Chrome
 - Wallet: any
 - Chain: any

## Steps to reproduce
 1. Go to a safe with a tx in queue
 2. Create a tx
 3. Edit the nonce so the value matches at least 1 digit of the current nonce already in queue

## Expected result
The dropdown should look like this
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/353a636f-ce2b-4a0d-b655-e95f967d6f81)

## Obtained result
There is a padding on top
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/4aaad734-92db-45a9-bfbc-5a4af5f33c50)

**Comment by liliya-soroka** [comment]
Verified. It was fixed
<img width="443" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/45ce839f-1c8f-4499-9bbc-69147af47834">
