### ISSUE TITLE
Cancelled transactions remain pending

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2613]
## Bug description

Cancelling an executing transaction remains both pending in the stepper and locally. It is eventually cleared from the pending state by our monitor, but it should ideally happen in the stepper.

## Environment
 - Browser: Firefox
 - Wallet: MetaMask
 - Chain: Goerli

## Steps to reproduce
 1. Execute a transaction and keep the `SuccessScreen` stepper open.
 2. Cancel the transaction in progress.
 3. Observe an "in progress" stepper and pending in the store.

## Expected result

Stepper shows an error and transaction is removed from pending store.

## Obtained result

Stepper remains "in progress" and transaction as pending.

## Screenshots

![cancelled-transaction](https://github.com/safe-global/safe-wallet-web/assets/20442784/901630fe-817b-4824-9cb5-7c57c2843e56)

**Comment by usame-algan** [comment]
@francovenica I moved this ticket to QA as it will be fixed by the same PR linked above.
