### ISSUE TITLE
Executing a tx with a safe-as-owner in zkSync

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2631]
## Bug description

This issue was reported initially on support: https://github.com/5afe/safe-support/issues/306

I tried to execute a tx in zkSync network and in the console the issue was: "invalid sender. can't start a transaction from a non-account"

NOTE: 
I tried the same in goerli and I didn't had issues, so is possible this is an issue with the network

## Environment
 - Browser: Chrome
 - Wallet: WC dApp (safe as owner)
 - Chain: zkSync Era Mainnet
 - Env: Current prod 1.19.1

## Steps to reproduce
 1. Have a safe 2/2. one owner can be a EOA and the 2nd must be a safe
 2. Create a tx like adding an owner, with the EOA
 3. Connect with the safe using the WC dApp
 4. Try to execute the tx

## Expected result
Tx can be executed normally

## Obtained result
The estimation fails, the console shows the error
 "invalid sender. can't start a transaction from a non-account"

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/dac033e0-447a-4519-8941-c3102c1900c6)

**Comment by 15563877167** [comment]
fixing?

**Comment by sethih26** [comment]
ETA on wen it will be fixed?

**Comment by katspaugh** [comment]
It's a bug on zkSync, feel free to chime in here: https://github.com/zkSync-Community-Hub/zkync-developers/discussions/144
