### ISSUE TITLE
Error loading chains

### ISSUE THREAD

**Issue by lucaschenex** [safe-global/safe-wallet-web#2633]
## Bug description
Connecting wallet no response, page error code 620: Error loading chains
I found this to be a transient issue on and off for a while

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: NA

## Steps to reproduce
 1. Go to https://app.safe.global/welcome

## Expected result
connect wallet

## Obtained result
no chains selection on top right conner
unable to click connect wallet

## Screenshots
<img width="1672" alt="Screenshot 2023-10-16 at 15 52 33" src="https://github.com/safe-global/safe-wallet-web/assets/2229985/b866efd5-8749-46d2-8479-13717c8de342">

**Comment by katspaugh** [comment]
Since it's intermitttent, it's probably some temporary infrastructure issue.
Closing since this repository is for frontend issues only.

@Safe-infra please check.
