### ISSUE TITLE
afterinstall doesn't generate contract types for typescript

### ISSUE THREAD

**Issue by bilbeyt** [safe-global/safe-wallet-web#2656]
I have detected in safe-infrastructure repo that image has no types generated. 

`docker exec -it cgw-web sh` to check it to validate image had no typings. Also tried to run `yarn install` again inside the image and saw that afterinstall runs but fails saying "patch-package command not found" but if i run 

`docker exec -it cgw-web sh -c "yarn after-install"` then it works.

**Comment by katspaugh** [comment]
Thanks for the report! This is likely fixed on this branch – #2535 – where we no longer depend on patch-package.
