### ISSUE TITLE
Mapping from chainId to Safe Network ShortName (oeth, arb1 etc)

### ISSUE THREAD

**Issue by startswithaj** [safe-global/safe-wallet-web#2677]
Is there a mapping from chainId or Safe UI's network url shortname? I.E. `https://app.safe.global/transactions/history?safe=oeth:`

```
{
  42161: 'arb1'
  10: 'oeth'
}
```

**Comment by katspaugh** [comment]
You should check the safe-deployments repo.

**Comment by startswithaj** [comment]
Just circling back on this one. If anyone is looking for the actual list its located here: https://github.com/safe-global/safe-core-sdk/blob/main/packages/protocol-kit/src/utils/eip-3770/config.ts
