### ISSUE TITLE
Top up account screen

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#2679]
## What is the feature about

In case a Safe has no assets we want to display a top-up screen to make it easier for users to start using their safe.

## The list of requirements

- Only show this screen if there are no tokens in the safe

## Designs/sketches
<img width="769" alt="Screenshot 2023-10-23 at 10 06 01" src="https://github.com/safe-global/safe-wallet-web/assets/5880855/62665f56-24e5-46e0-bf8e-4f2b1dbbe1b8">

https://www.figma.com/file/WSpulDIM1EoSCI6Ph9QdWq/Seedless-onboarding?type=design&node-id=208-57634&mode=design&t=x581uyWlZId3sO1E-0

**Comment by katspaugh** [comment]
Closing as this was implemented.
