### ISSUE TITLE
Görli Walletconnect tx queuing / tx service broken atm?!

### ISSUE THREAD

**Issue by elmariachi111** [safe-global/safe-wallet-web#2681]
## Environment
 - Browser: Chrome & FF
 - Wallet: MetaMask
 - Chain: Görli

## Steps to reproduce
I can connect with WalletConnect but any transaction that my dapp writes doesn't show up in the tx queue. It's cancelled by the viem client after ~3 minutes

## Expected result
can submit tx via wc

## Screenshots

**Comment by katspaugh** [comment]
Are you talking about the WalletConnect Safe App?
<img width="560" alt="Screenshot 2023-10-23 at 12 50 12" src="https://github.com/safe-global/safe-wallet-web/assets/381895/17a2d09b-796c-4295-ae2a-9c42e1c74838">

Do you see outgoing `/propose` requests?

**Comment by elmariachi111** [comment]
That's the context, precisely. It actually works again now. Was pulling my hair for ~1h. I'm not seeing any /propose requests at all;  But I think we need to keep the Walletconnect screen open for this to work (assumed this works regardless on which Safe Web page an user looks at, never read that message tbh ;) ) 
![image](https://github.com/safe-global/safe-wallet-web/assets/1344649/4b5a0f5f-11d9-443f-9802-6923d431677c)

**Comment by katspaugh** [comment]
OK, cool. I'll close the issue then.

>  we need to keep the Walletconnect screen open for this to work

We're atm working on moving WalletConnect to the main app, to the header, so it will work on any page soon. 👍
