### ISSUE TITLE
Recommended nonce loading is too long 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2689]
## Bug description
Recommended nonce loading is too long  and it's possible to create a few txs under the same current safe nonce because of it 
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to the walletconnect native implementation PR
 2. trigger tx from the dapp
 Current result:The suggested nonce is still being loaded while the sign button is already available. As the result it's possible to create tx with the safe current nonce instead of the next one in the queue

https://github.com/safe-global/safe-wallet-web/assets/338622/4a36d8ea-f814-4a79-8acb-2e5018482606

3. go to the queue list
4. click confirm tx
Current result: The tx nonce has been in a loading state for a long time. It's quite strange as the nonce is known for the tx from the queue list 
https://github.com/safe-global/safe-wallet-web/assets/338622/77efb27d-2792-439f-8049-97218300f21d

## Expected result
Could we check why the nonce loading is taking so much time?

**Comment by katspaugh** [comment]
I've seen this too, and thought the nonce would never load. But it did, in a few long seconds.
Doubt it's related to WalletConnect though. Most likely a backend issue.

**Comment by liliya-soroka** [comment]
I think the recommended nonce loading time depends on the number of transactions in the queue. The longer queued txs list , the longer it takes to receive a response.

**Comment by katspaugh** [comment]
@liliya-soroka this will be solved here: https://github.com/safe-global/safe-client-gateway/issues/681
I'll close this issue for now.
