### ISSUE TITLE
Cannot easily scroll to end on Confirm Transaction screen

### ISSUE THREAD

**Issue by DefiDebauchery** [safe-global/safe-wallet-web#2690]
## Bug description
When signing transactions with a large number of steps, the Sign button, located on the bottom of the page, becomes less accessible. While a mouse scrollwheel works, you would typically be able to use End or Cmd-Down (Mac) on the keyboard to quickly move the viewport to the bottom; however, the structure of the page does not allow this.

## Environment
 - Browser: Chrome
 - Wallet: Rabby
 - Chain: Optimism

## Steps to reproduce
 1. Create a MultiSend or other transaction that enables a scrollbar on the Confirm Transaction screen
 2. Try to quickly access the Sign button, located at the bottom of the page

## Expected result
One should be able to use End or Cmd-Down to move the viewport to the bottom of the page.

## Obtained result
The viewport does not move, despite the scrollbar.

## Screenshots
![Screenshot 2023-10-24 at 10 55 07 AM](https://github.com/safe-global/safe-wallet-web/assets/75273961/e1486839-5059-459f-8f76-316e97591deb)

**Comment by usame-algan** [comment]
Possibly related to #2682

**Comment by liliya-soroka** [comment]
A quick way to reproduce :
1. Open. transaction builder
2. upload json file - 
[supreme working batch.json](https://github.com/safe-global/safe-wallet-web/files/14295623/supreme.working.batch.json) - Click "Ok, I understand"
3. Click "create batch" and "send batch" 
Confirm tx page with many actions will be opened:
<img width="848" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/30ca93a0-e436-4f73-89d0-66d63fda405c">
