### ISSUE TITLE
[Tx flow] Don't treat user rejection as an error

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2701]
1) Don't log "user rejected" as an error to Sentry
<img width="1160" alt="Screenshot 2023-10-30 at 07 29 10" src="https://github.com/safe-global/safe-wallet-web/assets/381895/78a959a4-5cc5-46bf-ae28-09c949128cb3">
2) Don't show a notification for that
<img width="367" alt="Screenshot 2023-10-30 at 07 30 42" src="https://github.com/safe-global/safe-wallet-web/assets/381895/02309065-b78b-41c3-b113-7b71133b0459">

**Comment by JABirchall** [comment]
Maybe this could also be improved on the frontend as well, as rejecting a transcation displays "There was an error". 

![](https://i.imgur.com/Xv4krgr.png)

Maybe just replacing that text with "The transcation was rejected by the user" or soemthing.
