### ISSUE TITLE
Apps - Filters on the "My pinned apps" subsection

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2703]
The PR https://github.com/safe-global/safe-wallet-web/pull/2699 removes the "Bookmarked apps" tab and adds a "My pinned apps" subsection whenever an app is pinned

That subsection is removed whenever you use the filters "Category" or "optimized with".

This ticket is to make those filters work with this new "My pinned apps" subsection

![Uploading regression 1.gif…]()

**Comment by katspaugh** [comment]
It's an intentenational behavior.
