### ISSUE TITLE
[Mobile pairing] Modal window with QR code and deprecation message doesn't appear

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2711]
## Bug description
[Mobile pairing] Modal window with QR code and deprecation message doesn't appear
## Environment
 - Browser: Chrome
 - Wallet: mobile pairing
 - Chain: any

## Steps to reproduce
 1. Go to the Connect wallet
 2. select mobile pairing
 Current result: Connected status appears in the onboard modal window, but the modal window with QR code and deprecation message doesn't appear

## Expected result
Make sure that QR code is displayed
## Screenshots
<img width="1381" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/ddf53d8c-9c47-4d91-b01c-493f6668e572">

**Comment by katspaugh** [comment]
Good catch. I'll disable this wallet option in the meanwhile.
