### ISSUE TITLE
Safe-as-an-owner doesn't work with native WC implementation in the same browser in 2 different tabs

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2719]
## Bug description
Safe-as-an-owner doesn't work with native WC implementation in the same browser in 2 different tabs## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: any

## Steps to reproduce
 1. Open web app in 2 tabs in the same browser under the same session
 2. try to connect safe-as-owner to the parent safe
 Current result: Nothing happens after the wc url is passed 

## Expected result
It should be possible to connect  safe-as-an-owner when 2 tabs in the same browser are used for connecting the safe-as-an-owner via wc native implementation

**Comment by Dracaena27** [comment]
The issue persist.

**Comment by Dracaena27** [comment]
The nested wallets are connecting now using different browsers, but I´d like to use the same browser. Do you know if this is possible?

**Comment by katspaugh** [comment]
We don’t support multi tab operation very well atm due to state persistence. There’s a tech debt issue to fix this. I’ll prioritize it.

**Comment by katspaugh** [comment]
Fixed in #2793.
