### ISSUE TITLE
Safe-as-an-owner+WC: add safe{wallet} app icon

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2720]
## Environment
 - Browser: Chrome/FF
 - Wallet: MetaMask/safe-as-an-owner
 - Chain: any

## Steps to reproduce
 1. Connect safe-as-an-owner via WC to parent safe
Current result: Safe{Wallet} web app doesn't have logo

## Expected result
Add safe{Wallet} web app logo 
## Screenshots
<img width="490" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/5cc124bf-53d0-4eda-946d-9a83befa3a47">

<img width="68" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/22a0b7cd-9e2d-40db-a61e-820c57b1b70b">

**Comment by katspaugh** [comment]
Fixed here: https://github.com/safe-global/safe-wallet-web/pull/2717/commits/fff1d739858fe80dcd8acbf0c77154c6d109f2d2
