### ISSUE TITLE
UI jumps on WC safe app click 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2733]
## Bug description
UI jumps on WC safe app click  

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: any

## Steps to reproduce
 1. Go to the safe app
 2. click on the wallet connect 
 
Current result: 
https://github.com/safe-global/safe-wallet-web/assets/338622/5778d0bb-32d8-47a6-9676-2ea3e3f7d948

## Expected result
No movement to the left when the WC app was clicked

**Comment by katspaugh** [comment]
The app has been removed.
