### ISSUE TITLE
[Polygon] Support Official USDC coin deployment

### ISSUE THREAD

**Issue by JABirchall** [safe-global/safe-wallet-web#2743]
## What is the feature about
Last month Circle added polygon to their official supported chains and deployed the official USDC token on the network.

## The list of requirements
Support fetching the price of the official USDC token on polygon
Address: 0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359

Rename the bridged USDC symbol to USDC.e
Renamed the bridged USDC token name to USD Coin (PoS)
Address: 0x2791bca1f2de4661ed88a30c99a7a9449aa84174

## Designs/sketches
![](https://i.imgur.com/v3b17Ay.png)

## Links
Announcement https://www.circle.com/blog/announcing-support-for-polygon-usdc
Officla USDC Deployment https://polygonscan.com/token/0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359
Bridged USDC.e Deployment https://polygonscan.com/token/0x2791bca1f2de4661ed88a30c99a7a9449aa84174

**Comment by katspaugh** [comment]
Thanks for letting us know!
This is the wrong repository though, you might want to post it in https://github.com/safe-global/safe-transaction-service
Cc @Uxio0

**Comment by JABirchall** [comment]
Ahh, thanks ill repost the request there.
