### ISSUE TITLE
[Recovery] Dashboard enable widget

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2753]
## What is the feature about

Widget to enable recovery via the dashboard.

## The list of requirements

- [x] Create widget

## Designs/sketches

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/2bad102a-965f-48f5-84dd-3d4decafd834)

## Links

- [Feature spec.](https://www.notion.so/safe-global/Recovery-feature-spec-d873c33a27c24cfabc91c85dbcf3ea35)
- [Figma](https://www.figma.com/file/pO43pjVwR34Uy1ihMsY3OM/Generic-recovery?type=design&node-id=446-5810&mode=design&t=RGkXuGwJrKf50WY0-0)

**Comment by liliya-soroka** [comment]
Cases to check:
1. Verify the Dashboard widget on the network with Recovery - checked (the account recovery widget replaced the relay widget)
2. Verify that no widget on the network without Recovery feature - checked ( no widget on the dashboard)
3. Verify the widget view when account recovery was not set up - checked ( "Set up recovery" button leads to the account recovery set up flow) 
4. Verify the widget view when the recovery was set up - ?

**Comment by liliya-soroka** [comment]
Verified , the issues reported on the stabilization board
