### ISSUE TITLE
[Recovery] Recovery settings

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2756]
## What is the feature about

Adding CRUD settings for recovery to the Safe settings.

## The list of requirements

- [x] Add "Account recovery" section to Safe settings with the following states
  - [x] Enable recovery state
  - [x] Edit/remove state

Note: there can be >1 Delay Modifier activated on a Safe.

## Designs/sketches

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/ac1e63cf-8bc2-4312-9a9a-75ae361c478f)

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/59338b1c-2e35-4da4-aa24-9f824442ed21)

## Links

- [Feature spec.](https://www.notion.so/safe-global/Recovery-feature-spec-d873c33a27c24cfabc91c85dbcf3ea35)
- [Figma for enable state](https://www.figma.com/file/pO43pjVwR34Uy1ihMsY3OM/Generic-recovery?type=design&node-id=449-9897&mode=design&t=RGkXuGwJrKf50WY0-0)
- [Figma for edit/remove state](https://www.figma.com/file/pO43pjVwR34Uy1ihMsY3OM/Generic-recovery?type=design&node-id=449-11936&mode=design&t=RGkXuGwJrKf50WY0-0)

**Comment by liliya-soroka** [comment]
Verified
Checked cases:
1. recovery settings view before the account recovery set up
2. recovery table with one record when an owner connected
3. recovery table with one record when a non-owner connect
4. recovery table with one record when the guardian connected
5. delete/edit recovery record and delete module will be checked separately
