### ISSUE TITLE
[Recovery] Email management

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2757]
## What is the feature about

Recovery email address CRUD.

Note: there are still [open questions](https://5afe.slack.com/archives/C05N1N2HDNE/p1699354685285399) about the following and the signature verification backend work needs to first be completed before tackling this.

## The list of requirements

- [x] Add new "Recovery email address" section to "Notification" settings of a Safe.
- [ ] Add enable state/flow
  - [x] Add email modal
  - [ ] Signature generation
  - [ ] Verification code
- [ ] Add show/edit state.

## Designs/sketches

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/d202bb41-7dbb-4620-b87c-6444cc6383da)

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/99134f0e-47bd-4ccc-be94-acefa842fe88)

## Links

- [Feature spec.](https://www.notion.so/safe-global/Recovery-feature-spec-d873c33a27c24cfabc91c85dbcf3ea35)
- [Figma](https://www.figma.com/file/pO43pjVwR34Uy1ihMsY3OM/Generic-recovery?type=design&node-id=647-12545&mode=design&t=RGkXuGwJrKf50WY0-0)

**Comment by usame-algan** [comment]
Closing this in favor of #3145
