### ISSUE TITLE
[Recovery] Enable module flow - email verification

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2760]
## What is the feature about

Enable recovery module flow.

Note: the signature verification backend work needs to first be completed before tackling this.

## The list of requirements

- [x] Transaction flow
  - [x] Intro.
  - [x] Settings
    - [ ] Email verification
  - [x] Review

## Designs/sketches

More in-depth flows available on [Figma](https://www.figma.com/file/pO43pjVwR34Uy1ihMsY3OM/Generic-recovery?type=design&node-id=456-15322&mode=design&t=Lo3nDvw622nW8RA7-0).

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/bb9ed7fd-1ca4-4abe-ab1e-7d66c5f616f2)

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/43b7e239-5bcf-46d0-a91d-5b120f555e0c)

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/df17a448-d332-46bf-8640-a33f1f179e3b)

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/480416a2-0f16-4cb2-a651-5806603dd103)

## Links

- [Feature spec.](https://www.notion.so/safe-global/Recovery-feature-spec-d873c33a27c24cfabc91c85dbcf3ea35)
- [Figma](https://www.figma.com/file/pO43pjVwR34Uy1ihMsY3OM/Generic-recovery?type=design&node-id=456-15322&mode=design&t=Lo3nDvw622nW8RA7-0)

**Comment by usame-algan** [comment]
Closing this in favor of #3148
