### ISSUE TITLE
[Recovery] Email template

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2765]
## What is the feature about

Email templates for:

- Email verification
- Recovery attempt started
- Unknown transaction

## The list of requirements

- [ ] Create template according to designs

## Designs/sketches

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/20af8da2-4f5e-4659-bb8a-cec2072f1803)

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/a4ecdf32-4675-4c7c-a773-d35ccbcb2fb0)

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/78d2f5e0-8140-44e1-ab5b-a9d92b124379)

## Links

- [Feature spec.](https://www.notion.so/safe-global/Recovery-feature-spec-d873c33a27c24cfabc91c85dbcf3ea35)
- [Figma](https://www.figma.com/file/pO43pjVwR34Uy1ihMsY3OM/Generic-recovery?type=design&node-id=1017-19714&mode=design&t=Lo3nDvw622nW8RA7-0)

**Comment by katspaugh** [comment]
The email HTML can be found [here](https://github.com/safe-global/safe-wallet-web/blob/recovery-epic/public/email-templates/recovery/index.html) but this task is blocked until we get access to the PushWhoosh admin to implement the actual template.

**Comment by usame-algan** [comment]
Closing this as it has been completed
