### ISSUE TITLE
WC  - The safe connects with itself after refreshing

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#2790]
## Bug description
After the user connects with WC using a wallet on his phone (like MM), then if refreshes the page, the WC pairing feature shows that the safe is connected with itself

This issue is in current prod 1.21.1

## Environment
 - Browser: Chrome
 - Wallet: WC (MM phone app) and WC pairing
 - Chain: Any
 - Env: Current prod 1.21

## Steps to reproduce
 1. Open the onboard modal and choose WC
 2. Use your MM phone app and scan the QR to connect
 3. Refresh the page manually

## Expected result
The WC should reconnect with the account you were connected before the refreshing

## Obtained result
Now is the safe itself connected instead

## Screenshots
![WC wrong pairing](https://github.com/safe-global/safe-wallet-web/assets/4503659/4347e6ea-c705-48e6-818e-ab46e39ca242)

**Comment by usame-algan** [comment]
Maybe this helps with debugging but the issue only happens for me if the connected wallet is an owner of the safe

**Comment by liliya-soroka** [comment]
The bug was fixed.
Wallet connected via WC is not part of dapps WC any more
