### ISSUE TITLE
[Recovery] Improve `TransactionAdded` querying

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2792]
## What is the feature about

We currently query for [`TransactionAdded` events](https://github.com/gnosis/zodiac-modifier-delay/blob/main/contracts/Delay.sol#L16-L23) on-chain from the block of Safe creation. Some chains, however, limit the amount/extent of `eth_getLogs` RPC calls. As such, we should investigate/implement way(s) to improve this:

It is outside the scope of this issue but we should also take the following into account when working on this, for later iteration:

1. As we query from the Safe creation block, we first get the creation transaction hash from the Transaction Service. This should ideally be done via the gateway instead.
2. Instead of on-chain requests, an indexer would ultimately be a better alternative (perhaps from that of the alerts provider).

Possible optimization idea:
A Safe account can only be recovered for at most Cooldown Period + Expiration time seconds.
We could try to fetch the first blocknumber in this time window and only query events between that and the latest block.

## The list of requirements

- [ ] Investigate and request `eth_getLogs` in a paginated/cached manner.
- [ ] Nonce comparison w/ fetching.

## Links

- [Feature spec.](https://www.notion.so/safe-global/Recovery-feature-spec-d873c33a27c24cfabc91c85dbcf3ea35)
- [Discussion that spawned this issue](https://github.com/safe-global/safe-wallet-web/pull/2767#discussion_r1390768220)

**Comment by liliya-soroka** [comment]
Verified
