### ISSUE TITLE
Manually trigger E2E action in PRs

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#2800]
## What is the feature about

The E2E test job runs automatically on every commit. Every run takes between 10 and 15 minutes with parallelized config. This can be a bit too excessive in case there are multiple commits in a short span or if a commit only changes a specific place inside the app and doesn't affect other views that are tested through E2E.

⚠️ Github offers a way to manually trigger actions through the `workflow_dispatch` option but without further adjustment it has to be triggered outside of the PR view for a target branch which is not exactly what we want. Instead it should be possible to do this inside a PR e.g. through adding a comment to the PR or assigning a label. ⚠️ 

## The list of requirements

- Change the E2E job to be manually triggered in PRs
- Only allow PR merges if the job ran successfully at least once
- Keep it automated on release branches / when merging into main
- Run it after the lint and unit test job since these are faster

**Comment by katspaugh** [comment]
The new smoke suite + a manual regression suite seems to be working reasonably well and it's scalable.
