### ISSUE TITLE
Cannot sign transaction at the safe with multiple owners and more than 1 threshold from MetaMask mobile

### ISSUE THREAD

**Issue by ElvisKrop** [safe-global/safe-wallet-web#2818]
## Bug description
As a user I'm unable to create a safe with 2 or more required signers and sign a transaction via WalletConnect from MetaMask mobile on [Safe{Wallet} web app](https://app.safe.global/).

## Environment
 - Browser: Chrome
 - Wallet: WalletConnect + Mobile MetaMask on Android
 - Chain: every (I have personaly reproduced on Sepolia and Goerli)

## Steps to reproduce
 1. Create a safe with 2 (or more) owners and 2 (or more) threshold, on this step you can use any wallet;
 2. Connect to the recently created Safe{Wallet} via WalletConnect option from MetaMask mobile app;
 3. Try to propose and sign any transaction
 
 The same use case fails if you try to sign a transaction directly in the MetaMask Mobile web browser. 

## Expected result
User should be able to sign and propose transaction from MetaMask mobile.

## Obtained result
Signature from MetaMask mobile and MetaMask browser extension appears to be different for the same EOA. 

## Screenshots
I'm attaching a link to the video with a full user flow:
https://drive.google.com/file/d/1-c8MOfiF09LYvo77bVMc4AaJ0yJwETnI/view?usp=sharing

**Comment by ElvisKrop** [comment]
Relevant issue on MetaMask mobile repository - https://github.com/MetaMask/metamask-mobile/issues/7792
Fix is expected in the next release 7.12.0

**Comment by liliya-soroka** [comment]
hmm, I have updated the mobile app to the 7.12.2 but the problem is not fixed. The wrong signature is sent from the MM mobile app

**Comment by ElvisKrop** [comment]
Hello folks!
I'm happy to share with you great news 🎈
MetaMask team has released a few days ago v7.12.5 of mobile app and it includes a desired fix 🎉

Important note: 
This version was released only for iOS and Android devices are still missing this fix. But if you have iOS device you can sign the transactions again💪 I have tested and it works well!
Have a nice day ahead!

cc @katspaugh @liliya-soroka

**Comment by katspaugh** [comment]
Thank you!
