### ISSUE TITLE
Hide iframe scrollbar by default 

### ISSUE THREAD

**Issue by hsk81** [safe-global/safe-wallet-web#2827]
## Bug description

If the Safe{WALLET} dapp integration contains an in-dapp scrollbar, then the outer iframe scrollbar is really irritating.

The latter should — by default — be switched off. Perhaps there should be a corresponding flag in the `manifest.json` configuration to show/hide the outer iframe scrollbar. 

## Environment
 - Browser: Brave
 - Wallet: MetaMask
 - Chain: Avalanche mainnet

## Steps to reproduce
 1. Go to https://app.safe.global/share/safe-app?appUrl=https%3A%2F%2Fsafe.xpowermine.com&chain=avax

2. Accept dapp and observe 

3. If only a single (outer) scrollbar of the iframe is visible, switch to e.g. the *about* tab.

## Expected result
Single *inner* scrollbar of the dapp (if it doesn't fit into the window height).

## Obtained result
Both the *inner* scrollbar of the dapp and the *outer* scrollbar of the iframe are visible. 

## Screenshots

Observed: ![Double Scrollbar.jpg](https://github.com/safe-global/safe-wallet-web/assets/1016709/2e4e7ad9-a96f-47b0-9ced-ae71ff2e86c2)

Expected: ![Single Scrollbar.jpg](https://github.com/safe-global/safe-wallet-web/assets/1016709/3ac4efb8-c4af-4f3e-83e5-7e4b32590366)

**Comment by katspaugh** [comment]
Thanks, fixed, it was just a small CSS bug.
