### ISSUE TITLE
Wallet icon colour doesn't match

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#2836]
## Bug description

The header icon shown when a wallet is not connected is grey, whereas all other icons are white/black.

## Steps to reproduce
 1. Open the Safe, ensuring a wallet is not connected and observe the colour of the icon.

## Expected result

Icon is white/black.

## Obtained result

Icon is grey.

## Screenshots

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/5763d9ca-51e5-4315-b1b4-61db5b272f9b)

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/8c1ca07a-bf0e-4c21-abaf-367d77d129f4)

**Comment by usame-algan** [comment]
This was done on purpose according to [Figma](https://www.figma.com/file/WSpulDIM1EoSCI6Ph9QdWq/Seedless-onboarding?node-id=1094%3A10957&mode=dev). Can we check how it looks like with a white/black icon? cc @TanyaEfremova

**Comment by iamacook** [comment]
> This was done on purpose according to [Figma](https://www.figma.com/file/WSpulDIM1EoSCI6Ph9QdWq/Seedless-onboarding?node-id=1094%3A10957&mode=dev). Can we check how it looks like with a white/black icon? cc @TanyaEfremova

It initially looked like a bug but if it should be so, feel free to close this.

**Comment by TanyaEfremova** [comment]
@iamacook @usame-algan The grey icon was selected, as it reflects 'empty state' like before, so the colors were expected. 
We can totally change the colors to the black/white pattern, if it does causes confusion
