### ISSUE TITLE
Add Energi Testnet and Mainnet to Safe Wallet webapp

### ISSUE THREAD

**Issue by zalam003** [safe-global/safe-wallet-web#2844]
## What is the feature about

Please add Energi Testnet and Energi Mainnet to Safe Wallet webapp so our community can create and manage their multisig wallet.

The factory address was deployed to the Energi chains: https://github.com/safe-global/safe-singleton-factory/pull/278

## The list of requirements

We would appreciate if you would add the following to Safe Wallet:

Energi Testnet:
```
RPC URL: https://nodeapi.test.energi.network
chain ID: 49797
currency symbol: NRG
explorer URL: https://explorer.test.energi.network/
```

Energi Mainnet:

```
RPC URL: https://nodeapi.energi.network
chain ID: 39797
currency symbol: NRG
explorer URL: https://explorer.energi.network/
```

## Designs/sketches

The hex color for Energi logo is: #00E676

[Energi - Brand Guidelines (v0.1.2).pdf](https://github.com/safe-global/safe-wallet-web/files/13430170/Energi.-.Brand.Guidelines.v0.1.2.pdf)

[Energi Logo](https://explorer.energi.network/images/EnergiLogoLight-6a94a198bcf372ac6bde6b842e8f1d33.png?vsn=d)

[NRG Token Logo](https://info.energiswap.exchange/static/media/NRG.292270a3.svg)

## Links

Energi website: https://energi.world

**Comment by katspaugh** [comment]
We cannot just add a new chain on the frontend. Apart from the contracts, our entire [offchain infrastructure](https://github.com/safe-global/safe-infrastructure) needs to be deployed for that chain.

Please feel free to add your deployments to this repo: https://github.com/safe-global/safe-deployments
