### ISSUE TITLE
Can not cancel "Processing" state 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2878]
## Bug description
In case when processing tx takes time on the chain side , there is no way to replace or cancel the tx 
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Gnosis chain

## Steps to reproduce
 1. Create tx on gnosis chain
 2. while the tx in the processing state try to replace or cancel it 
 3. wait for 20-30 min in case of issues with processing on the chain side
 Current result: the processing state is blocking the replacement tx for a long time
Seems that the user has to wait around 30 mins
<img width="226" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/3fec66d9-cf00-4f6d-b0ca-a2ff50fabfe0">

## Expected result
Check the time out for the processing state to reset it and allow the TX replacement 
We might need a notification that the tx still can be executed ( please check such a case as well)

**Comment by liliya-soroka** [comment]
cc @kirkkonen to check if the current message is ok

![Image](https://github.com/safe-global/safe-wallet-web/assets/338622/87a367f4-10fc-41bc-8ee7-83967f1fce71)

**Comment by usame-algan** [comment]
I suggest we parse the error message and display something more user-friendly like so:

<img width="865" alt="Screenshot 2024-01-10 at 10 20 41" src="https://github.com/safe-global/safe-wallet-web/assets/5880855/d7efd8d8-b3f9-4d1b-9833-3150660eebcb">
