### ISSUE TITLE
Unable to add Ledger or Trezor with custom derivation path to existing safe

### ISSUE THREAD

**Issue by jlopp** [safe-global/safe-wallet-web#2942]
## Environment
 - Browser: Chrome
 - Wallet: Ledger & Trezor
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Import an existing Safe wallet (2 of 3 in my case)
 2. Click "connect wallet" in upper right
 3. Select Ledger or Trezor
 4. Select "custom derivation" dropdown
 5. Note that input box does not allow anything to be typed

## Expected result
Custom derivation path should be typeable / pasteable.

## Obtained result
Can't proceed with adding hardware wallet.

Perhaps related to #1425 ?

**Comment by liliya-soroka** [comment]
Can not reproduce the issue. It's possible to type when the custom derivation path is selected:
<img width="821" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/d24be503-8290-47fa-82f6-72974eabf7f6">

**Comment by liliya-soroka** [comment]
Note: Make sure that all other wallets are fully disconnected .

I was able to enter custom path because connection to the ledger was the second one. I had active connection to MM at the same time
