### ISSUE TITLE
[Research] Migrate to web3modal

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#2953]
Research migrating from web3-onboard to web3modal (from WalletConnect).
List pros and cons and a possible migration path.

Criteria:
* Must support Ledger and Trezor
* Unit tests
* Customizable CSS

**Comment by usame-algan** [comment]
It needs to be able to support custom wallets such as social login.

I would also add [RainbowKit](https://www.rainbowkit.com/) to the list for research

**Comment by katspaugh** [comment]
Closing this, the outcome:
* ➕Web3modal has no issues that onboard has connecting to MetaMask
* ➕Web3modal has an imrpoved SiWE support, especially with WalletConnect
* ➕Better [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) support
* ➖ No direct Ledger/Trezor support, only via LedgerLive (but they'll have it once the new Ledger SDK is out)
