### ISSUE TITLE
Sepolia: safe creation with relay doesn't work

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#2977]
## Bug description
Sepolia: safe creation with relay doesn't work - 422 error
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Sepolia

## Steps to reproduce
 1. Try to create a new safe on Sepolia using Relay
Current result: 422 error and the safe can not be created
## Expected result
It should be possible to use relay on sepolia 
## Screenshots
<img width="354" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/7e991f8c-707b-400b-bbbc-1eb176cf1aa2">

**Comment by schmanu** [comment]
The transaction validation on the safe-gelato-relay service is causing this bug. The frontend request looks correct to me.

**Comment by usame-algan** [comment]
I am getting the same error when I try to use relaying on prod görli. I think it has to do with insufficient funds. Can we check that?

**Comment by schmanu** [comment]
For me it worked for a normal tx on Sepolia but not for Safe creation :/

**Comment by chris-downs** [comment]
I was having this issue and switched to paying for gas from my wallet instead of "Sponsored by Safe". I use a Trezor and it wouldn't work until I disabled safety checks- It was complaining about a "mismatched derivation path". I was able to create a Sepolia safe after temporarily disabling safety checks. Perhaps the relay is seeing that same validation error.

**Comment by usame-algan** [comment]
@francovenica the fix should be deployed to staging soon and can be tested against the staging relay service.

**Comment by francovenica** [comment]
Tried in Goerli just in case that is another network in the stg cgw that has relayer, but it seems it that it doesn't have funds for the relayer either. We will just have to wait for Johannes
