### ISSUE TITLE
Safe Wallet doesn't resolve when sign and execute are done apart

### ISSUE THREAD

**Issue by xaler5** [safe-global/safe-wallet-web#2990]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet / Sepolia

## Steps to reproduce

1 - Go to Uniswap and connect with WalletConnect to a Gnosis Safe (I'd done the test on Sepolia) 
2 -  Trade any amount of any token and submit the tx. This will open a modal in Uniswap that will wait for the tx to resolve (wallet connect to answer back)
3 -  Tx is received on the Safe, sign without executing
4 - Execute on a separate step (after signing)

Tx is executed but Uniswap just hangs there forever

## Expected result

Uniswap resolves then signing and execution are done separately

## Additional context

Notice that if sign and execution are done in one step then the wallet resolves correctly. I've [raised up] (https://github.com/WalletConnect/walletconnect-monorepo/issues/3942) the issue with WalletConnect but there's the suspect (not confirmed) that it just doesn't resolve tx hash in this case.

Such limitation blocks any attempt of using a safe through wallet connect. 

## Screenshots

![image](https://github.com/safe-global/safe-wallet-web/assets/20795374/fdd35499-7498-4f5e-becc-b4c614503680)

**Comment by katspaugh** [comment]
It's not a bug on either side. Until you fully sign and execute the transaction, it isn't submitted to the blockchain and there's no tx hash. So naturally Uniswap cannot immediately recieve a tx hash via WalletConnect.

#2875 potentially addresses this issue, along with alowing to batch several transactions.

**Comment by monokh** [comment]
> It's not a bug on either side. Until you fully sign and execute a transaction,

> 4 - Execute on a separate step (after signing)

The user did execute the transaction. This is the last in the steps. The issue is that safe wallet is resolving the transaction with the safe tx hash instead of waiting for execute and handing back the on chain transaction hash.
