### ISSUE TITLE
Tx list: wrong date labels due to client-side timezone conversion

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3001]
## Problem
There's a mismatch between DATE_LABEL dates and dates displayed in tx summaries/details.

This is due to the fact that the DATE_LABEL dates come in 00:00 format, while tx dates have an actual hour/minute.
So it can happen that the midnight one gets assigned to a different date due to a timezone shift.

## Solution
Pass a timezone_offset parameter to the backend to group by date in a consistent manner on the backend. This param should be sent to all endpoints returning a list of txs (i.e. history, filtered history, queue).

**Comment by katspaugh** [comment]
Adjusted the types here: https://github.com/safe-global/safe-gateway-typescript-sdk/pull/142

**Comment by katspaugh** [comment]
A blocker on the backend side: passing a timezone_offset not only affects the grouping by date, buy also shifts all timestamps according to the offset. This is not correct, the timestamps must remain in UTC.

**Comment by liliya-soroka** [comment]
discussion in progress between @katspaugh and wallet-infra

**Comment by katspaugh** [comment]
There's a remaining bug related to daylight-savings timezones. It will be filed as a separate issue on CGW's side but not a blocker for this issue as it's a relative edge case.
