### ISSUE TITLE
422 error during tx creation via Transaction builder on Sepolia

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3009]
Issue Category
Transaction execution issue

What happened?
User was trying to confirm a transaction (using transaction builder) but getting 422 error instead. Already tried basic troubleshooting steps but issue still persists. Safe address: https://app.safe.global/transactions/queue?safe=sep:0x4F97461eAc313CF7dE1d89128061dEfA39a01532

This is the screenshot of the console logs:
image

Date and time this happened or you first noticed this issue
13-12-2023

Network
Sepolia

support ticket - https://github.com/5afe/safe-support/issues/351
Safe Address
No response

Token Address
No response

Token Type
None

Transactions
Note: Chose Goerli for now since Sepolia is not on the choices

**Comment by usame-algan** [comment]
This is most likely related to https://github.com/safe-global/safe-wallet-web/issues/2977 and will be handled by the same fix.

**Comment by usame-algan** [comment]
This can be re-tested with staging CGW now

**Comment by liliya-soroka** [comment]
@usame-algan , I think that the error appears because of interaction with 0x0000000000000000000000000000000000000000. I am trying the same on Goerli and also getting 422.
Do you know if there are any limitations?

**Comment by usame-algan** [comment]
Ah true I didn't see it. Just tested as well and can confirm it fails with a 422 both with relaying and executing via EOA so it is unrelated to #2977. I am not sure yet why it fails for the zero address. Will have to investigate it further.

**Comment by usame-algan** [comment]
@liliya-soroka you are correct the zero address is not allowed as a recipient on our transaction service.
<img width="338" alt="Screenshot 2024-01-12 at 14 13 51" src="https://github.com/safe-global/safe-wallet-web/assets/5880855/cc0147cc-0759-411c-b43a-86f6c74ccd75">

Although the Tenderly simulation runs fine so it might confuse users. @moisses89 do you know why it is not allowed?

**Comment by moisses89** [comment]
> @liliya-soroka you are correct the zero address is not allowed as a recipient on our transaction service. <img alt="Screenshot 2024-01-12 at 14 13 51" width="338" src="https://private-user-images.githubusercontent.com/5880855/296250343-cc0147cc-0759-411c-b43a-86f6c74ccd75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzQxMjcsIm5iZiI6MTcwNTA3MzgyNywicGF0aCI6Ii81ODgwODU1LzI5NjI1MDM0My1jYzAxNDdjYy0wNzU5LTQxMWMtYjQzYS04NmY2Yzc0Y2NkNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTJUMTUzNzA3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmQwNzYwOGQ5NmI1NmQ1ZWE2MmE2MTRhNDE5YTc2OTEzNjUxY2NmYTJkMjk5MjliZjQxOTAzZGI5YmRiMzJiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BgDnvUaSFJEZHkyA_WOf3vgQRadci_G_tptxVFaUP30">
> 
> Although the Tenderly simulation runs fine so it might confuse users. @moisses89 do you know why it is not allowed?

We are using the following serializer in the `to` field, with default `allow_zero_address=False`  https://github.com/safe-global/safe-eth-py/blob/master/gnosis/eth/django/serializers.py#L34 
I don´t know the reason for that, should we accept Zero addresses in `to` field? Maybe to burn tokens?

**Comment by liliya-soroka** [comment]
Verified
