### ISSUE TITLE
Lazy-load Recovery

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3035]
The Recovery feature isn't something that you use every day but it gets bundled with the main app chunk and comes with a 1-megabyte dependency.

It would be good to isolate and lazy-load Recovery components, hooks and services. Ideally also put them all in one folder. Right now they are all over the codebase.

## Requirements
* The Recovery feature should have a single import point (an index.ts that re-exports individual modules)
* If the feature is disabled via the `RECOVERY` feature toggle, no related modules should be imported in runtime
* All Recovery-related components, hooks and other modules should be in the same folder

## Current bundle
<img width="921" alt="Screenshot 2023-12-19 at 14 13 29" src="https://github.com/safe-global/safe-wallet-web/assets/381895/b0aee233-1dac-48e0-a34e-10dce4d75073">

cc @iamacook

**Comment by francovenica** [comment]
The PR is closed and I cannot comment on it. Given Lily's comment I'll look deeper into it in dev since is already merged there.

**Comment by francovenica** [comment]
Re checked the feature once more and I didn't find any issues. I'll pass to done now. 
It will be rechecked during regression.
