### ISSUE TITLE
Add ability to simulate tx when not a signer

### ISSUE THREAD

**Issue by adamazad** [safe-global/safe-wallet-web#3043]
## What is the feature about

I am not a signer on a Safe, but would like to inspect the simulation for a tx, for example the following tx:

<img width="1546" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/1926216/89dfe532-c432-4709-a29b-61937d31803e">

## The list of requirements

- Add a link to simulate the transaction on Tenderly.

## Designs/sketches

Perhaps move the simulation button to the right-hand section of the tx details card.

## Links

n/a

**Comment by katspaugh** [comment]
It's a feature we're paying for, so I don't think it's wise to open it up for anyone.
That said, you can use impersonator.xyz to pretend to be a signer.

@johannesmoormann wdyt?
