### ISSUE TITLE
Could not detect network error while confirming transaction [BNB chain]

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3046]
Issue Category
Transaction execution issue

What happened?
User was not able to initiate transaction since he gets "could not detect" error while confirming the transaction:
image

Already did basic troubleshooting steps (and double checked it's the right account connected on metamask) but issue still persists. Safe address: https://app.safe.global/settings/setup?safe=bnb:0x4E2B8e08f725B8FEEAbd9be30dc811e979F30bA4

Date and time this happened or you first noticed this issue
15-12-2023

Network
Binance Smart Chain

Safe Address
bnb:0x4E2B8e08f725B8FEEAbd9be30dc811e979F30bA4

Token Address
No response

Token Type
None

Transactions
No response

**Comment by liliya-soroka** [comment]
support issue - https://github.com/5afe/safe-support/issues/352

**Comment by schmanu** [comment]
Seems like this issue is likely related to the ad blocker / RPC of the user. Will close this here.
