### ISSUE TITLE
Recovery - the safe itself can be set as owner

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3057]
## Environment
 - Browser: Any
 - Wallet: MetaMask
 - Chain: Any (tested in sepolia)
 - Env: Dev 1.25

## Steps to reproduce
 1. Go to a safe
 2. Set a user as a recover
 3. Start a recovery
 4. Add the current safe as owner in the recovery form

## Expected result
The safe itself shouldn't be allowed to even be selected in the form

## Obtained result
The safe can be selected and the tx can be proposed

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/25d3d568-6e8f-42da-9a79-c4b302dea61b)

**Comment by francovenica** [comment]
The issue is in the add/replace owner, so probably check this ticket first: https://github.com/safe-global/safe-wallet-web/issues/3058

Might fix this one as a side effect

**Comment by liliya-soroka** [comment]
Verified. The issue was fixed 
<img width="952" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/d4139403-08be-49ea-8664-70db4720aa6c">
