### ISSUE TITLE
Add owner - The owner field is not validating the safe itself as owner

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3058]
## Bug description

During add owner or replace owner, the field where you enter the address to be the new owner, the safe itself needs to be validated as a non-valid address
Currently when you add the safe itself no error is shown. The "Next" button is disabled, so there is no risk of adding the safe as owner, but still the field should show the error right away

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any (tested in sepolia originally)
 - Env: Dev 1.25.x

## Steps to reproduce
 1. Go to a safe as owner
 2. Start an Add owner from
 3. Copy the Safe's address
 4. Paste it as a new owner

## Expected result
The input should right away show an error indicating the safe cannot be owner of itself

## Obtained result
The error doesn't show up right away. If you click in the input again, clearing it, the error sudendly shows.

Note:The "Next" button remains disabled so right now there is no risk of an user accidentaly adding the safe as owner

## Screenshots
![3041](https://github.com/safe-global/safe-wallet-web/assets/4503659/0fe8bb02-2aed-482c-8d0e-99345d651a71)

**Comment by schmanu** [comment]
I realized that we do not run any validation when entering a Safe address from the addressbook list.
Through that I was able to even get to the next step (Sign and Execute) whilst adding the Safe itself as owner. 
The transaction fails of course but this should not be possible.

Steps to reproduce:
0. Add the currently open Safe to the addressbook if not present there
1. Enter a legit non-safe address and confirm that the Next button is enabled
2. Select the safe itself via the dropdown
3. Click Next
4. You can now sign / execute this faulty transaction
