### ISSUE TITLE
Color tokens: Bug fixes and improvements for Dark Mode

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-wallet-web#3066]
## Bug description
There are a few inconsistencies color bugs related to the color palette scheme and the dark mode styles. See some examples below in screenshots.
Some colors can use a replacement in the dark mode scheme to reflect on the colors of the light mode, some are just not following the existing color palette.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to Settings > Notifications and Settings > Modules to see alert banners;
 2. Go to Safe Apps, see the sliding component above;
 3. Go to any page, open the Safe Accounts sidebar;
 4. Open a Safe Accounts with pending notifications to trigger Info alert;
 5. Open the network switcher in the top navbar.

## Expected result 
The following color codes should be applied in the **dark mode**

- `success:background` is `#1f2920`
- `secondary:background` is `#1B2A22`
- Background of the info notification color should be: `#19252C`
- The selected network color in the network dropdown should be: `#303033`
- In the Safe accounts list the color of the addresses should be text:primary (currently it's green)
- In the Safe apps component` styles_content__TMlnS` needs to use `#12FF80` for the border and the arrow component (can we change the hex code for `secondary:main` in darkPalette.ts to `#12FF80`?)

## Screenshots
<img width="540" alt="1-success-background" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/4ef0307c-ef8e-4d1a-9cee-e8abda289767">
<img width="532" alt="1-secondary-background" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/4281896a-e25a-4d96-a2e1-8d21141f4055">
<img width="454" alt="safe-acc" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/cdb860a7-6a7a-4c1e-b316-a05d7251bfc9">
<img width="161" alt="network_color" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/9d50c13e-a8d4-4907-a819-abc653da1d69">
<img width="195" alt="Screenshot 2024-01-04 at 17 09 32" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/cba39d5c-07e0-4d20-abb6-7952d9d6e1d0">

**Comment by manoranjith-shankar** [comment]
@TanyaEfremova, can i work on this issue?

**Comment by katspaugh** [comment]
@manoranjith-shankar अच्छा है !

**Comment by manoranjith-shankar** [comment]
@katspaugh Danke!

**Comment by usame-algan** [comment]
> can we change the hex code for secondary:main in darkPalette.ts to #12FF80?

We are using `var(--color-secondary-main)` (css) and `secondary.main` (js) in a few places and need to check if they still look as preferred after this change. I suggest to open a new issue to align the colors with our design system similar to how we an issue to update the typography: https://github.com/safe-global/safe-wallet-web/issues/2363

**Comment by TanyaEfremova** [comment]
@usame-algan I will create a separate ticket for` var(--color-secondary-main)` and review the elements first, everything else is accordingly to the Design System :)
