### ISSUE TITLE
Dashboard overview widget UI fixes

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-wallet-web#3068]
## Bug description
Not a bug, but an update to the overview dashboard widget that shows balance.  

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to the Dashboard page of any Safe account.

## Expected result
- Change the text style of the amount of assets stored (better readability);
- Buttons should fill the container's width.  

[Design reference in Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=9249%3A65172&mode=design&t=omKO5xezFboyvYR6-1)

## Screenshots
<img width="589" alt="Screenshot 2024-01-04 at 17 57 27" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/ad0af356-7561-45c0-8ae0-4cd0403843ab">

**Comment by 000000armor** [comment]
can I work on this one? @TanyaEfremova @katspaugh

**Comment by katspaugh** [comment]
@000000armor go ahead! :)

**Comment by 000000armor** [comment]
@katspaugh can I get an access to figma mock ups? It seems like it's required to solve the issue. I sent a request (david.sevikian.work@gmail.com)

**Comment by katspaugh** [comment]
We can’t give you access to Figma, but @TanyaEfremova can upload a sketch file.

**Comment by 000000armor** [comment]
> We can’t give you access to Figma, but @TanyaEfremova can upload a sketch file.

alright👌🏼

**Comment by TanyaEfremova** [comment]
@000000armor how about a separate Figma file with the Dev Mode on, [try this link ](https://www.figma.com/file/gMjr6zy6VcM2RA4QtNKdsd/Dashboard?type=design&node-id=0%3A1&mode=dev)

**Comment by 000000armor** [comment]
@TanyaEfremova still have to get an access to this file

**Comment by 000000armor** [comment]
I'm currently facing a blocker due to a module resolution error. The specific error message is: Module not found: Can't resolve '@/types/contracts'. However, I've noticed that the types folder doesn't exist within our src directory, which adds to my confusion about the root cause of this issue.

Any insights or suggestions to resolve this would be greatly appreciated!

**Comment by katspaugh** [comment]
Try running `yarn` again, and if the postinstall script that generates types doesn't kick in for some reason, you can run `yarn postinstall` manually.
