### ISSUE TITLE
"Continue with MetaMask" blows up when wallet has ENS

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3073]
<img width="458" alt="Screenshot 2024-01-05 at 14 50 23" src="https://github.com/safe-global/safe-wallet-web/assets/381895/16752bf8-ab48-4782-89e3-e43f46f0a455">

Perhaps we shouldn't display an 0x address if the wallet has an ENS name.

**Comment by triggeredcode** [comment]
@katspaugh Can I take this? I am a beginner here, also it will help me if you can help me with some more context.
