### ISSUE TITLE
Add network name to the list of Safe apps

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3075]
Instead of "Explore the Safe Apps ecosystem" we could have a title like "Explore the Safe {networkName} ecosystem".
Also we might want to increase the subtitle tag length so it fits in 1 line.
 
More context: https://5afe.slack.com/archives/C03CQ5ABLQM/p1704450599107899

![Image](https://github.com/safe-global/safe-wallet-web/assets/5926677/d62d01dc-3d8a-416b-a899-29123eb2ad60)

**Comment by manoranjith-shankar** [comment]
Hi @katspaugh, can i work on this issue?

**Comment by katspaugh** [comment]
@manoranjith-shankar चलो ठीक है :)
