### ISSUE TITLE
[Fileverse Safe App] Relaying doesn't work with W3A

### ISSUE THREAD

**Issue by kirkkonen** [safe-global/safe-wallet-web#3079]
## Bug description

When relaying a Safe App transaction with a social wallet, nothing happens.

## Environment
 - Browser: Chrome
 - Wallet: W3A
 - Chain: Gnosis Chain

## Steps to reproduce
 1. Login with W3A/Google
 2. Go to a Safe App (e.g. Fileverse)
 3. Create a transaction
 4. Try executing the tx via the Relayer

## Expected result

Tx should be executed or at least some meaningful error shown

## Obtained result

Absolutely nothing happens

## Screenshots
https://www.loom.com/share/15d82c90928541d98acdd7316d07ca95?sid=7cf6666d-bd97-4f45-82ce-1e6d0a1593da

--- 

## Original report from Fileverse
Context can be found here: https://5afe.slack.com/archives/C03DAGWJCR5/p1700575086865789

1. Relayer Provider cancelling txns.
-> Loom: https://www.loom.com/share/15d82c90928541d98acdd7316d07ca95?sid=7cf6666d-bd97-4f45-82ce-1e6d0a1593da
-> Logjam with proper console logs & api calls: https://jam.dev/c/b2c2134f-3c8e-4a44-bdb2-94032accb649
4. UI becoming unusable by not allowing users to click.
Log jam to help you investigate: https://jam.dev/c/e3f93c77-4abb-4e17-b81c-2e54274a7839
Safe tx hash (failed):
0x71b7628233bdbc1163ce5eda9a0c83dfab62773c5b906edb20e995bd8c9f4d74
All the API calls are also recorded in the logjam link for you to debug if issue is on the API Level. For eg, go the request you want to check in bottom right on this link: https://jam.dev/c/b2c2134f-3c8e-4a44-bdb2-94032accb649

And a successful one (if the relayer is not used): https://gnosisscan.io/tx/0xb2f23c467a42bc397ea20b40b57a509937b3a0729623944b95c7897595a0b962/

**Comment by katspaugh** [comment]
@kirkkonen from reading this issue it’s not really clear what needs to be done.

Please write a more succinct problem description and paste all the necessary info in the issue so that we don’t have to dig on slack. M

**Comment by kirkkonen** [comment]
Just found this comment. Kinda weird to put it on ice because you have to make 1 click to get into the Slack thread but I'll copy the original message for you here. I don't have any other context. Added you to the Telegram chat either. @katspaugh 

Last week I got some more context on the bug reported by the Fileverse team. Quick facts:
They face relayer error on deploying a [Collaboration smart contract (portal)](https://portal.fileverse.io/#/create)
That's happening on Gnosis chain, not Goerli
It is definitely unrelated to Seedless as it happened and was reported way before the release
Some more details shared by Constantin from Fileverse:
(1) This is the Fileverse App on Safe: https://app.safe.global/share/safe-app?appUrl=https%3A%2F%2Fportal.fileverse.io&chain=gno
- Fileverse = collaboration smart contract deployed on Gnosis
- On the Safe App, it's also only available for Safe on Gnosis

(2) In both the above error messages / relayer transaction issues, the users clicked on the Fileverse App and when deploying it they faced this relayer specific issue
- To help, we tried to replicate from our side and we got the same issue for this flow: "google login". Here's a jam screenrecoding that I just did with my gmail and it shows you the screen + console errors directly: https://jam.dev/c/f628336d-5514-4f10-8d9d-6dd7cf185b79
- Check 0:51

**Comment by katspaugh** [comment]
It looks like an issue with the combination of relaying and W3A.

@liliya-soroka @francovenica it's not a known bug, is it? Can you reproduce any problems when relaying with the social login?

**Comment by liliya-soroka** [comment]
I can not reproduce the issue .
The portal was deployed successfully for my gnosis chain safe using Social Login + Relay

**Comment by usame-algan** [comment]
Can this issue be closed since social wallet was sunset?
