### ISSUE TITLE
How to request to add a new EVM chain

### ISSUE THREAD

**Issue by Pana** [safe-global/safe-wallet-web#3080]
## What is the feature about

Support EVM compatible chain Conflux eSpace

**Comment by katspaugh** [comment]
### Safe Contracts
Anyone is free to deploy the Safe contracts deterministically. i.e. you can deploy the deterministic deployment factory to the same address as other L2's. To add the contract support for a new network, follow the steps in https://github.com/safe-global/safe-contracts#deploy and create a PR in the Safe deployments repository (https://github.com/safe-global/safe-deployments). If you’re an L2, ENSURE you use the L2 version of our contracts. Not the mainnet version.

### Safe Infra + UI
Someone has to run this, and the Safe team can only evaluate and prioritise a small number of chains. If you want your chain to be evaluated, can you please share an email and we can send through a form?
Or alternatively, you run the infra+UI services yourselves, or work with a third party partner to deploy and maintain a fork of the services.

**Comment by Pana** [comment]
What do you mean by infra ?

**Comment by Pana** [comment]
@katspaugh

**Comment by katspaugh** [comment]
Server infrastructure.

Please understand I won't be able to elaborate on any further questions as this is the frontend repository, and the issues here are not intended for discussions outside of the wallet frontend topics. Cheers.
