### ISSUE TITLE
[WalletConnect] Can not scroll to the Approve button if the list of support networks is long on small resolutions

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3081]
## Bug description
[WalletConnect] Can not scroll to the Approve button if the list of support networks is long on small resolutions
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Sepolia

## Steps to reproduce
 1. Go to safe on Sepolia
 2. Try to connect to the snapshot 
 Current result: The connect dialog appears , but the approve button is not available for me , because there is no scroll

## Expected result
Make sure that users with small resolution ( Macbook 13") can approve or reject wc connection during dapp connection via WC v2

## Screenshots
https://github.com/safe-global/safe-wallet-web/assets/338622/4ad62725-041b-4017-809f-245d02f3ffdb

**Comment by katspaugh** [comment]
Tested, it scrolls now 👍
