### ISSUE TITLE
Make "Proceed and copy" button less prominent in "Before you copy" modal

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-wallet-web#3083]
## What is the feature about
Analytics show that 45% of users proceed to copy addresses from untrusted txs in our tx history.
While this might include false positive txs, we still see Safes falling for Address poisoning attacks.
We want to decrease this rate by making the "proceed and copy" button less prominent and adding a new primary button "Do not copy".

## The list of requirements
- Add "Do not copy" button
- Turn proceed and copy button  into text button / link.

## Links
- [Victim tx](https://etherscan.io/tx/0x84f7e211446291c62b2eb69908016078c5d0b8a9a0c339318fe160aa9154aa2d) after release of new copy warnings

**Comment by usame-algan** [comment]
Can you post a screenshot of the "Proceed and copy" button? I only remember the "Send again" button from the tx history.

**Comment by schmanu** [comment]
> Can you post a screenshot of the "Proceed and copy" button? I only remember the "Send again" button from the tx history.

![Screenshot 2024-01-08 at 13 32 58](https://github.com/safe-global/safe-wallet-web/assets/2670790/f8659676-1c4f-46f0-9a94-818f67a4fc28)

It appears when trying to copy the Sender or Receiver from a spam ERC20 Incoming or Outgoing tx.

**Comment by katspaugh** [comment]
![Screenshot 2024-01-08 at 13 32 58](https://github.com/safe-global/safe-wallet-web/assets/381895/fbfc74a1-1904-4a8a-9240-b8f0c713da95)
