### ISSUE TITLE
Signing a message fails on Sepolia

### ISSUE THREAD

**Issue by takadr** [safe-global/safe-wallet-web#3106]
## Bug description
Signing a message fails

## Environment
 - Browser: Chrome
 - Wallet: Wallet connect
 - Chain: Ethereum Sepolia

## Steps to reproduce

 1. Go to Opensea https://testnets.opensea.io/
 2. Open the login modal and select WalletConnect
 3. Copy & paste WalletConnect url to Safe UI and approve to connect with Opensea
 4. Sign the message

## Expected result
The message should be successfully signed and confirmed.

## Obtained result
Getting error that says failed to sign.

## Screenshots
<img width="689" alt="スクリーンショット 2024-01-14 12 38 53" src="https://github.com/safe-global/safe-wallet-web/assets/92980001/b64356f5-8b6c-407e-90ae-3d7a3b982d00">
<img width="352" alt="スクリーンショット 2024-01-13 17 08 42" src="https://github.com/safe-global/safe-wallet-web/assets/92980001/889ce1bc-077d-40dc-b9ee-d6353b8e3ff3">
<img width="759" alt="スクリーンショット 2024-01-13 17 09 29" src="https://github.com/safe-global/safe-wallet-web/assets/92980001/a9a9b65b-d354-456c-aca0-4f1c7cac457e">

## Additional information
I found that when signing the message, the browser is posting the payload "safeAppId":-1.
When I try to curl with "safeAppId": null from my terminal, it signed successfully.

The curl command which signed successfully was like below.

```bash
curl --location --request POST 'https://safe-client.safe.global/v1/chains/11155111/safes/0x123456789/messages' \
--header 'Accept: */*' \
--header 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
--header 'Connection: keep-alive' \
--header 'Origin: https://app.safe.global' \
--header 'Referer: https://app.safe.global/' \
--header 'Sec-Fetch-Dest: empty' \
--header 'Sec-Fetch-Mode: cors' \
--header 'Sec-Fetch-Site: same-site' \
--header 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36' \
--header 'content-type: application/json' \
--header 'sec-ch-ua: "Not.A/Brand";v="8", "Chromium";v="114", "Google Chrome";v="114"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "macOS"' \
--data '{"message":"Welcome to OpenSea!\n\nClick to sign in and accept the OpenSea Terms of Service (https://opensea.io/tos) and Privacy Policy (https://opensea.io/privacy).\n\nThis request will not trigger a blockchain transaction or cost any gas fees.\n\nWallet address:\n0x1234566789\n\nNonce:\n026b783f-e294-40b1-acb3-f7bbc9b47ff3","signature":"0x123456789","safeAppId":null}'
```

**Comment by schmanu** [comment]
We will list the WalletConnect Safe App on Sepolia to fix this for now.

Once we remove the Wallet Connect Safe app we have to find a better solution for this.
