### ISSUE TITLE
Speed-up pending transaction

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#3107]
## What is the feature about

Currently, when submitting a transaction it will just say "Processing" and there is no option to speed-up that transaction through the UI. Some wallets like MetaMask offer this option but others don't which can result in the transaction being stuck until it times out on our end.

## The list of requirements

- Offer a "speed-up" option when a transaction is processing that resubmits it with the same wallet nonce

## Designs/sketches

TBD

## Links

TBD

**Comment by schmanu** [comment]
Do we want to offer this speed up for transactions that reached the 1 minute timeout?
