### ISSUE TITLE
Tx history - Date tooltips don't show after using pagination

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3115]
## Bug description
In the tx history, if you hover the date a tooltip showing a more accurate date is displayed. This tooltip only works in the first page, if you start to scroll, the new items that show after using the pagination don't have that tooltip

## Environment
 - Browser: Chrome
 - Wallet: Any
 - Chain: Ethereum mainnet
 - Env: Current prod build

## Steps to reproduce
 1. Go to this safe that has a lot of tx's
 2. Hover the date on the first element and check the tooptip shows
 3. Scroll to load new elements on the list
 4. Hover the date in those new elements

## Expected result
The tooltip is displayed

## Obtained result
The Tooltip doesn't show up

## Screenshots
The ones that don't show the tooltip are elements loaded by pagination
![tooltips](https://github.com/safe-global/safe-wallet-web/assets/4503659/ff90e6a7-6053-4c28-8f59-4acd46ec947e)

**Comment by liliya-soroka** [comment]
still relevant - 14.02.2023
It seems not related to the pagination, but related to the time when the tx was executed.
The date tooltip is displayed only for the tv created within last 2 months
