### ISSUE TITLE
Rejecting network change when signing a message treats it as an error

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3126]
## Bug description
When signing a message, if your wallet is connected to another network it will request the network change when trying to sign it. 
The issue is that if the user reject the network change, an error notification pops up, and it shouldn't

## Environment
 - Browser: Chrome
 - Wallet: WC
 - Chain: Ethereum mainnet
 - Env: Seen in current RC 1.27.0

Linking this ticket to #3090 

## Steps to reproduce
 1. Go to safe app go to an ethereum safe
 2. Connect your wallet and set it to Sepolia network
 3. Go to Opensea and connect with wallet Connect
 4. After connecting a message to sign should show up
 5. Click on Sign
 6. When the popUp asks you to change network, reject it

## Expected result
Only a message in the form indicating "wrong network" should show up

## Obtained result
Besides the form message, an error message pop's up as notification that should not show up

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/114f43b3-df9c-4ad5-8d2a-f310299c7e1e)

**Comment by katspaugh** [comment]
There's no notification anymore, only an inline error message which is correct.

<img width="707" alt="Screenshot 2024-08-08 at 11 35 52" src="https://github.com/user-attachments/assets/4f99ab7d-7991-4d7c-8c72-b4a2bc7d4c69">
