### ISSUE TITLE
Safe creation - Addresses go out of bounds in the owner address inputs

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3129]
## Bug description
In safe creation a "read only" address goes out of bounds in the address input

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any
 - Env: Current prod 1.26 (and in current RC 1.27)

## Steps to reproduce
 1. **Have addresses added into the address book (at least 1)**
 2. Go to safe creation
 3. In the owner input, select an address from the dropdown

## Expected result
The address should fit in the entire input, or 
be properly cropped, or 
have the short address format (0x1234...abcd)

## Obtained result
The address goes out of bound

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/24e517d5-7843-44c3-8d1e-d24f9a2b4e5e)

**Comment by liliya-soroka** [comment]
still relevant for the addresses from the addressbook during safe creation 
15.02.2024
