### ISSUE TITLE
Not enough funds error shown for nested safes

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#3139]
## Bug description

When a safe is an owner of another safe and is connected to that safe and doesn't have enough funds we show a warning that the "connected wallet doesn't have enough funds to execute this transaction." even though the owner safe doesn't need to pay for it.

## Environment
Prod

## Steps to reproduce
 1. Go to child Safe C and connect to owner Safe P
 2. Make sure Safe P doesn't have any funds on it
 3. Create a transaction in C
 4. Observe the error in C

## Expected result

No such error should be visible if we can detect that a smart contract wallet is connected

## Obtained result

Error is visible for smart contract wallets

## Screenshots
<img width="704" alt="Screenshot 2024-01-22 at 15 24 27" src="https://github.com/safe-global/safe-wallet-web/assets/5880855/cc1cbde9-d560-4c0a-92f6-45cda9e850e6">

**Comment by schmanu** [comment]
This is a tricky one as some Smart account wallets do pay from their balance. 
With Safes this is possible too. So as soon as we enable that in our UI the warning would make sense again.

Probably we could tone it down to a warning (in every case) as this is not really an error.
A user might overwrite the gas costs with something very low for instance to circumvent this.

**Comment by katspaugh** [comment]
I'll close this as we have a separate epic to tackle Nested Safes holistically.
