### ISSUE TITLE
Polygon: the gas estimation from the site is too low

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3140]
## Bug description
Polygon: the gas estimation from the site is too low, as the result the user has to speed up manually and facing resubmit tx often
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Polygon

## Steps to reproduce
 1. try to execute any tx
 2. check the site gas estimation in MM
 Current result: 
<img width="438" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/f1856371-3793-4b57-bd3b-76886f73f082">

## Expected result
Could we check if the estimation can be more accurate on-site side

**Comment by francovenica** [comment]
I tried this again.

With just a regular send funds there is no issues, but when I tried with a batched tx (2 send funds and a owner removal) I got a timeout. So I still this needs to be checked by devs
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/15979fa8-50f4-40e4-81e1-5315d7b0404b)

**Comment by francovenica** [comment]
I tried again in prod, by doing several tx in batch and I didn't have any issues this time.
Still, it seems we are estimating the lowest gas fee possible.
I think it wouldn't hurt bump it by 20% or so so we reach the "medium" estimation of MM
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/b0a37bad-c0c7-45a6-9889-664379e1a5a2)
