### ISSUE TITLE
Network support of Base Sepolia 

### ISSUE THREAD

**Issue by johannesmoormann** [safe-global/safe-wallet-web#3144]
## What is the feature about

Base Testnet Sepolia is being added to the Safe deployments (https://github.com/safe-global/safe-deployments/pull/362) and should be supported by the interface. 

Timeline tbd 

## The list of requirements

- test safe creation and tx execution @liliya-soroka, testing will be carried out by @JagoFigueroa  
- add Base Sepolia to the network list
- activate Base Sepolia on Prod 9th of Feburary

**Comment by Uxio0** [comment]
There's a faucet on https://basefaucet.com/

**Comment by liliya-soroka** [comment]
@johannesmoormann , @JagoFigueroa will do only basic testing related to the core-api ( safe creation, tx execution to check indexing), I will overtake the task after and perform all other tests on our clients ( web and mobile)

**Comment by liliya-soroka** [comment]
Stabilisation board - https://www.notion.so/safe-global/ab81354a08f04c4ab720f47046167298?v=2af70a4d73b543baa40a15ea2f5b7d60

**Comment by liliya-soroka** [comment]
Verified for the web app
