### ISSUE TITLE
[Recovery] Delete an email address

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#3149]
## What is the feature about

Allow users to delete an already registered email address from their settings page.

This is blocked by #3145 

## The list of requirements

- [x] If an email address exists for the current connected signer, offer them the option to delete that email address
- [ ] This option should be visible even if they are not an owner of that safe anymore

## Designs/sketches

[Figma](https://www.figma.com/file/pO43pjVwR34Uy1ihMsY3OM/Recovery-Hub?type=design&node-id=1799-35143&mode=design&t=VMcmdYVJKhO9zV0P-0)

## Links

Tech spec: [Notion](https://www.notion.so/safe-global/As-a-Safe-owner-I-want-to-delete-my-email-address-so-that-I-stop-receiving-alert-notifications-8a3ba232942149d194aa1efae6772798)

**Comment by liliya-soroka** [comment]
@usame-algan ,  "This option should be visible even if they are not an owner of that safe anymore " is not available for the removed owner . Need to check , probably, unsubscribe in the email should be used in such case instead of our UI

**Comment by usame-algan** [comment]
I think it would be possible to also enable the Sign to view button for non-owners. We just need to handle possible errors then.

**Comment by liliya-soroka** [comment]
Verified, delete works.
Delete for non-owners will be handled separately
