### ISSUE TITLE
Getting Module not found: Can't resolve '@/types/contracts' when running yarn start

### ISSUE THREAD

**Issue by Moganesan** [safe-global/safe-wallet-web#3164]
## Environment
 - Browser: Brave
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Install all libraries using yarn install
 2. run yarn start

## Expected result
Should open the web app in localhost:3000

## Obtained result
Module not found: Can't resolve '@/types/contracts'

## Screenshots
![Uploading Screenshot 2024-01-29 at 11.22.34 PM.png…]()

**Comment by katspaugh** [comment]
You should run `yarn postinstall` manually.

**Comment by Moganesan** [comment]
thank you, got it.
