### ISSUE TITLE
web ui for bsc network is barely functional

### ISSUE THREAD

**Issue by mshakeg** [safe-global/safe-wallet-web#3169]
## Bug description

I've proposed transactions to the bsc transaction service using the safe sdk and the transaction only shows up on the UI many minutes later. Other members in the team report a similar experience. Also when they sign a transaction on the web ui it shows the following `signing` message for many minutes

![safe web signing forever](https://github.com/safe-global/safe-wallet-web/assets/40227090/e42b9552-41b3-4f5c-bc81-d89d5378d503)

It seems like this may be due to rate limits with the JSON RPC that the web ui is configured to use(I don't think it's using the wallet provider as I've configured a custom JSON RPC in Metamask that should work better than an open/public JSON RPC).

<img width="1512" alt="safe web error" src="https://github.com/safe-global/safe-wallet-web/assets/40227090/5f3e8798-0018-4fc6-b74b-6c63761d8a37">

Also when I finally manage to get the minimum signatures I am still unable to execute the transaction:

<img width="1271" alt="safe web execution error" src="https://github.com/safe-global/safe-wallet-web/assets/40227090/d3015e00-4b5c-4feb-a9f1-437a12bb621c">

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: BSC

## Steps to reproduce

1. Propose a transaction to the BSC transaction service and observe that the transaction only shows up many minutes later.
2. Have another owner/s attempt to sign the transaction and observe that signing takes many minutes.
3. Once the minimum signature threshold is finally reached observe that you still cannot execute the transaction.

**Comment by katspaugh** [comment]
@safe-global/safe-qa could you check this?

**Comment by liliya-soroka** [comment]
UI works for me as expected during tx execution with MM 
<img width="378" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/75884a8d-7d5c-4d8e-ac6d-61454d5f09a1">
https://github.com/safe-global/safe-wallet-web/assets/338622/3486d92a-5c4e-4d87-98a1-2b8af8343baa

**Comment by liliya-soroka** [comment]
@mshakeg , do you use safe-CLI to propose tx directly to the tx service without using UI ?

**Comment by JagoFigueroa** [comment]
Issue should be resolved now, let us know 😄

**Comment by mshakeg** [comment]
@liliya-soroka I'm using the `@safe-global/api-kit` package in a TS script to propose transactions

**Comment by mshakeg** [comment]
@JagoFigueroa could you please clarify how it was resolved? were any code changes made or was the cloud infra improved to handle higher loads?

**Comment by JagoFigueroa** [comment]
We had an issue with one of our services since yesterday afternoon that was causing delays on txs to pop on UI that was fixed earlier today 😄 buuuuuut I assumed you were transacting normally from UI so might be unrelated. Apologies if that is the case and you are still experiencing issues

**Comment by mshakeg** [comment]
@JagoFigueroa it seems fine today
