### ISSUE TITLE
1.1.1 Safes: Reject tx has safetxGas>0 and is not recognized as reject tx

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3171]
## Bug description
1.1.1 Safes: Reject tx has safetxGas>0 and is not recognized as reject tx - https://github.com/5afe/safe-support/issues/379
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Create tx in the 1.1.1 safe
2. Reject tx via UI using "Reject tx" option
Current result: contract interaction tx is created with safetxgas>0, as result it's not recognised as reject tx created via UI

3. reject the tx again using "reject tx"
Current result: New reject tx is created with safetxgas=0, so it's recognised as reject tx

## Expected result
Make sure that reject tx has safetxgas=0 for the 1.1.1 safe

**Comment by schmanu** [comment]
I think having safeTxGas > 0 is correct for Safes < 1.3.0.
At least according to the implementation in the [safe-core-sdk/protocol-kit](https://github.com/safe-global/safe-core-sdk/blob/main/packages/protocol-kit/src/utils/safeVersions.ts#L12)

It still should be shown correctly as Rejection instead of contract interaction. Investigating further :)

**Comment by schmanu** [comment]
I think this bug must be fixed on our backend side: 

Our CGW is incorrectly returning that this is not a cancellation transaction: https://safe-client.safe.global/v1/chains/1/transactions/multisig_0x4d71Bc00b22464b62C096e1caeAb3171e6148e9a_0x294b8ea85744ae2db8bfd5bd53383b12661e41e32857d3874fd9da4f64e0f32d

**Comment by schmanu** [comment]
After further investigation I moved this issue to the safe-core-sdk.
Apparently the safeTxGas has to be 0 only for Rejection txs.

**Comment by liliya-soroka** [comment]
The problem persists even after migration to ProtocolKit
