### ISSUE TITLE
App crash on tx creation using tx builder with "Custom data" when tx nonce=0

### ISSUE THREAD

**Issue by jalaziz** [safe-global/safe-wallet-web#3183]
## Bug description

When attempting to create and sign a Base mainnet transaction, the SDK fails to initialize with `Code 103: Error creating a SafeTransaction (The Safe SDK could not be initialized. Please be aware that we only support v1.0.0 Safe Accounts and up.)`.

Attempting the same transaction on Polygon mainnet works, so it appears to be a Base-specific issue. The Base Safe contract was deployed in the same way as the Polygon Safe contract, using the "Safe: Proxy Factory 1.3.0".

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Base mainnet

## Steps to reproduce
 1. Choose a Safe account on Base mainnet
 2. Click "New Transaction"
 3. Go to "Transaction Builder"
 4. Enter a contract address (e.g. `0x4e59b44847b379578588920cA78FbF26c0B4956C`).
 5. Toggle "Custom data" and enter call data
 6. Set an "ETH Value" of 0
 7. Click "Add Transaction"
 8. Click "Create Batch"
 9. Click "Send Batch"
 10. Observe the error

## Expected result

I should be able to sign the transaction.

## Obtained result

I receive an error indicating that the SDK failed to initialize.

## Screenshots

![Screenshot by Dropbox Capture](https://github.com/safe-global/safe-wallet-web/assets/247849/0c94e421-8182-42d6-bab2-817c473c97b7)

**Comment by katspaugh** [comment]
@safe-global/safe-qa can you reproduce this?

**Comment by liliya-soroka** [comment]
App crash 
<img width="1324" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/af6e8008-be64-4448-92b3-b9360a04579d">
