### ISSUE TITLE
Wrong color for tx indexing state

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3190]
It should be a neutral info or success color, not a red warning color.

<img width="927" alt="Screenshot 2024-02-01 at 14 59 56" src="https://github.com/safe-global/safe-wallet-web/assets/381895/e9367536-c079-4fcd-8497-cf0f7652533d">

**Comment by ravalkenil** [comment]
Can you assign me?

**Comment by katspaugh** [comment]
@ravalkenil ठीक है, चलो! 👍

**Comment by Pushkarmondal** [comment]
To generate this issue what we have to do?

**Comment by katspaugh** [comment]
Transaction करना चाहिए

**Comment by liliya-soroka** [comment]
The latest release 
<img width="907" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/3120fd3a-9358-44bc-a96e-860b13744cb5">

**Comment by katspaugh** [comment]
Hmm, looks like it fixed itself.
