### ISSUE TITLE
[Safari] Sidebar CSS is broken

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3194]
After expanding and collapsing the sidebar drawer, it looks broken in Safari:

<img width="427" alt="Screenshot 2024-02-05 at 09 08 07" src="https://github.com/safe-global/safe-wallet-web/assets/381895/6e9f210e-0bae-4a9c-abcb-5b910387a878">

**Comment by Moganesan** [comment]
Hi can i work on it?

**Comment by katspaugh** [comment]
Sure, go ahead!

**Comment by Moganesan** [comment]
Hi please check this PR #3235
