### ISSUE TITLE
Bottom items of sidebar are off screen on mobile

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#3196]
## Bug description

The bottom items of the sidebar are offscreen and a scrollbar is present on mobile Chrome.

## Steps to reproduce
 1. Open a Safe on mobile Chrome.

## Expected result
The bottom items of the sidebar are on screen.

## Obtained result
The botoom items of the sidebar are off screen and a scrollbar is present.

## Screenshots

https://github.com/safe-global/safe-wallet-web/assets/20442784/4279efb2-8103-4189-9841-4e7160377a26

**Comment by liliya-soroka** [comment]
@iamacook , I have tried ipad and iPhone view and don't see any issue with the bottom items ( also tried on a real iPhone 11)
<img width="387" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/830670ab-a8ec-4885-b0e6-22d3e3394b21">

**Comment by katspaugh** [comment]
This seems to have been fixed (tested on iOS).
