### ISSUE TITLE
Address overflows transaction details of transfers on mobile

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#3197]
## Bug description

Unlike other transaction details, asset transfer addresses overflow the transaction details container on mobile Chrome.

## Steps to reproduce
 1. Expand a transfer and observe the recipient address overflowing whereas those of other transaction types are cut off on mobile Chrome.

## Expected result

The recipient address in transaction 40 (see screenshot below) matches the style in transaction 39.

## Obtained result

The recipient address in transaction 40 overflows.

## Screenshots

![1000041641](https://github.com/safe-global/safe-wallet-web/assets/20442784/102f160d-450b-42ed-9eb3-a9940bc4c364)

**Comment by daniel0ar** [comment]
Hi! I believe this is a better approach (truncating text with ellipsis).
![image](https://github.com/safe-global/safe-wallet-web/assets/34529009/d13303df-5096-4048-ae13-650e7b5d080b)
If this is ok please assign this to me so I can send the PR.

**Comment by daniel0ar** [comment]
This way the copy, export and options buttons don't get hidden on overflow

**Comment by katspaugh** [comment]
Definitely, thanks @daniel0ar!

**Comment by daniel0ar** [comment]
PR submitted!

**Comment by francovenica** [comment]
This ticket was put in QA to have a second look. I've checked in dev and the addresses look fine in the history list in a iPad mini type of viewport
