### ISSUE TITLE
Safe creation titles repeated in human readable titles

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#3198]
## Bug description

Safe creation transaction titles repeat when human readable transactions are shown: "Safe account created Safe account created"

## Steps to reproduce
 1. Ensuring human readable transactions are enabled, observe the repeated tile of Safe creation transactions.

## Expected result

"Safe account created" is shown the once.

## Obtained result

"Safe account created" is repeated.

## Screenshots

![1000041642](https://github.com/safe-global/safe-wallet-web/assets/20442784/61471cf4-d653-42bf-86e3-646ded0ee3f9)

**Comment by katspaugh** [comment]
AFAIR, we don't use human-readable there, that string is coming from somewhere else.
