### ISSUE TITLE
How can connect DAPP in page

### ISSUE THREAD

**Issue by totom123** [safe-global/safe-wallet-web#3212]
HI, I am a junior developer
I am building a wallet
Can I have ur idea how to connect DAPP with walletconnect without open model and copy the code?

**Comment by katspaugh** [comment]
The only other option is to create a Safe App: https://github.com/safe-global/safe-apps-sdk/tree/main/packages/safe-apps-sdk

In future, for general questions like this, please post a question on StackExchange instead: https://ethereum.stackexchange.com/questions/tagged/safe
