### ISSUE TITLE
Wrong bulk execution tooltip in dark mode

### ISSUE THREAD

**Issue by compojoom** [safe-global/safe-wallet-web#3217]
## Bug description
Title says it all, but here is also a screenshot:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/c1ca72c6-85ab-4c1b-b6fe-a5aec05bc70d)

Either I am color-blind or the hover is not "light green"

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to the transaction page
 2. Have some queued txs
 3. hover over the "bulk execute" button

**Comment by 000000armor** [comment]
Hi guys, is it possible to get mockups with proper color-tokens? I'd like to work on this issue, but I have no access to figma mockups. Also it would be great to attach mockups in advance (if it's possible) for outside-contributors

**Comment by katspaugh** [comment]
I suggest we don't change any colors but just adjust the tooltip to say "All highlighted transactions" w/o mentioning light green.
