### ISSUE TITLE
AddressBook importing csv - The 50 character limit is not working

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3228]
## Bug description

You can upload a file with names with more than 50 characters and those are accepted by the Address book.

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any
 - Env: Current prod 1.29

## Steps to reproduce
 1. Have a csv with the columns address,name,chainID
 2. Add an entry with a valid address, a long name and the chainId you are currently on
 3. Upload the file in the Address book section

## Expected result
Cut the name to be only the first 50 characters. Do not invalidate the file uploading

## Obtained result
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/5b87d153-bef0-4dfe-976e-91373cdcd431)

**Comment by katspaugh** [comment]
Closing as won’t fix, not worth the effort.
