### ISSUE TITLE
Safe creation: The error about the same address used twice is missing 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3247]
## Bug description
The error about the same address used twice is missing 
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Sepolia

Precondition:
the owner address should be in the addressbook 

## Steps to reproduce
 1. Start safe creation flow 
 2. click add owner , as the same default owner ( I used addressbook and also copy/past same address as I have in addressbook)
 Current result: No validation and the user can go to the review step and try to execute safe creation 

## Expected result
Error message that the address is in use should be displayed to the user

## Screenshots
<img width="1427" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/16ee4ed6-b5cf-401b-9e8b-053deadbe799">

**Comment by usame-algan** [comment]
Fixed in #3427
