### ISSUE TITLE
No gas warning when connected with a safe-as-owner

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3259]
## Bug description
In the Tx form, when you are about to execute a tx, if the wallet you have connected has no funds it will show a warning message about it.
When you are connected with a safe-as-owner that has no funds the warning is shown, which is not correct because is not the safe the one that executes the tx at the end, is the owner of that safe.

## Environment
 - Browser: Any
 - Wallet: Any
 - Chain: Any
 - Env: Current prod 1.29

## Steps to reproduce
 1. Have 2 safes you own
 2. Connect to safeA, create a tx and leave it in queue ready to be executed
 3. Connect to that safeA with the other safeB as owner. Since the tx is fully signed, your safeB should have be able to execute the tx
 4. Attempt the execution and check the last step of the tx execution form

## Expected result
No warning message shown

## Obtained result
A warning message is shown that the current wallet has no funds

Note: the tx can be excuted just fine if the owner of SafeB has funds. The only issue is the warning message itself

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/a3723c7a-72bf-499e-bf64-23d5dac277f0)

**Comment by schmanu** [comment]
Currently we only check that a smart account is connected. 
I think it is still okay to show the error as it is not blocking the UI. We could consider toning it down to a warning though.
There are some smart account wallets that pay directly from the wallet's balance. 
Using Safe with 4337 also enables that so this warning would make sense again.

**Comment by liliya-soroka** [comment]
https://github.com/safe-global/safe-wallet-web/issues/3139 - duplication
