### ISSUE TITLE
Disable social login buttons for all chains but Gnosis

### ISSUE THREAD

**Issue by kirkkonen** [safe-global/safe-wallet-web#3266]
## The list of requirements

- remove the button from the welcome page
- replace the wallet connection dropdown in the header with a simple Connect button that opens onboard
- leave Gnosis implementation as it is now

## Designs/sketches

![Image](https://github.com/safe-global/safe-wallet-web/assets/5926677/7f39101a-cb6d-4c4d-99e3-115fc2c3a5f7)

![Image](https://github.com/safe-global/safe-wallet-web/assets/5926677/92e63175-0171-4972-a747-76f20895d91f)

## Links

More context: https://5afe.slack.com/archives/C03DAGWJCR5/p1707996092296879

**Comment by francovenica** [comment]
LGTM
