### ISSUE TITLE
[Nested Safes] Pending tx disappears after 1 min

### ISSUE THREAD

**Issue by compojoom** [safe-global/safe-wallet-web#3273]
## Bug description
Setup:
Child safe with 1/n threshold
Parent safe with 2+/n threshold that is owner of the child. 

Child is connected over walletconnect to parent. Child submits a tx:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/264e4633-f113-49d6-a68d-b6a6dcdee382)
parent confirms:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/e53cb9e2-4bbb-4840-a246-bc67657d9121)

Child shows:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/43c25a77-688d-4cbf-9858-b94d4342925c)

once the transaction from parent is processed, it shows in the queue of the parent safe and another owner of the parent can see it and execute it:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/a5351e66-0fbe-4918-a5e1-e3013eb51fd7)

![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/d75bbc43-4d5f-454d-929d-0142bf99393c)

by the time the second owner signs the tx in the child safe is shown as timed out:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/e3d0f439-df51-4036-9991-a81ec03e3de7)

I can still execute it:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/23464d5f-3fa5-4770-9759-08672761cfb5)

once I do and go to the child and view the "timed out tx"
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/a925e053-240d-438a-b68e-ed102491a045)

If I look at the "timed out tx" before confirming it with the second owner it is shown as:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/445ef7b8-4a87-444f-a607-fe2c0ac55ee3)

but it is not viewable under queue or transactions. Once approved with the other owner the tx state changes to executed.

## Environment
 - Browser: not relevant
 - Wallet: child safe, parent safe. Child connected to parent over walletconnect, parent needs multiple signatures to execute txs. 
 - Chain: not relevant

## Expected result
Users don't expect to see a timeout and this throws them off as the tx dissapears in the child safe (if you don't click on the tooltip) and it looks weird that there is a tx in the parent, but it is not in the child.

**Comment by schmanu** [comment]
This has been fixed by https://github.com/safe-global/safe-wallet-web/pull/3425
