### ISSUE TITLE
Can't subscribe to notifications for owned un-added safe

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3288]
## Bug description
can't subscribe to notifications for owned un-added safe

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: any

## Steps to reproduce
 1. Connect your owner that has a few safes on different networks ( watchlist is empty)
 2. go to the settings->notifications -> global preferences 
 Current result: there is no possibility to subscribe to notifications  for owned un-added safes

## Expected result
Make sure that it's possible to subscribe to notifications for all owned safes of connected owner

**Comment by katspaugh** [comment]
Also related: the notifications subscription popup pops up for any added safe, even for not owned ones.
