### ISSUE TITLE
Add meta robots noindex for dev/staging

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3297]
Apply a `<meta name="robots" content="noindex" />` tag in the staging and PR/dev deployments to keep those URLs from being indexed by web crawlers.

**Comment by Moganesan** [comment]
can i work on it

**Comment by katspaugh** [comment]
Absolutely, @Moganesan!

**Comment by Moganesan** [comment]
so which branch i have to work on its dev right?

**Comment by DiogoSoaress** [comment]
The staging environment https://safe-wallet-web.staging.5afe.dev/ is still being indexed because the `<meta name="robots" content="noindex">` present in that deployment.

**Comment by katspaugh** [comment]
That site is built with IS_PRODUCTION=true for pre-production testing, so the meta tag isn't inserted there. We might have to introduce another flag to differentialte this environment from both dev and prod.

**Comment by katspaugh** [comment]
It's fixed now.
