### ISSUE TITLE
[Ledger] Error message too long when rejecting a tx

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3303]
## Bug description
Reject tx on Ledger leads to confusing error on UI ( "could not coalesce error")

## Environment
 - Browser: Chrome
 - Wallet: Ledger
 - Chain: Any

## Steps to reproduce
 1. start signing or executing tx with Ledger owner
 2. reject action in the ledger
 
## Expected result
Could we show more user-friendly error 

## Screenshots
<img width="718" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/2780d8b7-70c9-4b85-913c-57ab6e352147">

**Comment by katspaugh** [comment]
Closing as wontfix. This error format is shown when Ethers cannot show a more user-friendly message, and it's expected.
