### ISSUE TITLE
Safes with a long singlestring name break the ui in the login page

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3313]
## Bug description

Is nish, but if somebody names their safe with a long string, it breaks the ui in the login page

## Environment
 - Browser: Chrome
 - Env: prod 1.30

## Steps to reproduce
 1. Name one of your safes with a long single string name
 2. Check the login page

## Obtained result
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/61b30694-425c-4ed1-895b-da1d42cb56a7)

**Comment by daniel0ar** [comment]
No worries, I have added this on PR #3315 (solves a similar issue with overflow) It now looks like this:
![image](https://github.com/safe-global/safe-wallet-web/assets/34529009/44deef70-91a6-448e-a37d-94f93ead9a38)
