### ISSUE TITLE
Upgrade Safe-Wallet-web version

### ISSUE THREAD

**Issue by happyleow** [safe-global/safe-wallet-web#3338]
## What is the feature about
Upgrade Safe-Wallet-web version based on new safe-deployment release publishment
## The list of requirements
I want `Safe-Wallet-web` to support `Safe-Deployment` v1.33.0 so i can run the safe-wallet-web for the new blockchain network(contracts are already included in `safe-deployment` v1.33.0).
## Links
Safe-Deployment: https://github.com/safe-global/safe-deployments/releases/tag/v1.33.0

**Comment by katspaugh** [comment]
Feel free to make a pull request. The protocol-kit package should be also updated, as it also depends on safe-deployments.

**Comment by katspaugh** [comment]
Approved, thanks! 🙏

**Comment by happyleow** [comment]
@katspaugh Thank you for your merging PR, could you please publish the new release version?

**Comment by katspaugh** [comment]
It will be likely released next Wednesday (06.03). Cheers!
