### ISSUE TITLE
ENS Safe App returns an error on domain management attempt

### ISSUE THREAD

**Issue by kirkkonen** [safe-global/safe-wallet-web#3340]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce

Pre-requisite: a Safe has to own an ENS domain.

 1. Go to Apps
 2. Open ENS Safe App
 3. Find your domain
 4. Try to change roles 

## Expected result

App creates a transaction to be signed in Safe

## Obtained result

Nothing happens for a few seconds, then an error is returned

## Screenshots

https://www.loom.com/share/291fcd7063ef435aba4adb39dc59cac7?sid=31658d47-4044-498d-b263-e74362a87c03

**Comment by katspaugh** [comment]
Closing because it's most likely a bug in the ENS Safe App, not the Wallet.
