### ISSUE TITLE
Migrate the Relay service to CGW

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3351]
Data for the new relay endpoints: safe address, safe version

Affected requests:

`POST /v1/relay/:chainId → /v1/chains/:chainId/relay`

`GET /v1/relay/:chainId/:safeAddress → /v1/chains/:chainId/relay/:safeAddress`

Updated data structures for the POST request:

```
type Request = {
  to: string;
  data: string;
  gasLimit?: string;
	// ⚠️ New
  version?: string; // Defaults to "1.3.0"
}
```

See the Gateway SDK PR: https://github.com/safe-global/safe-gateway-typescript-sdk/pull/152

**Comment by iamacook** [comment]
It would be preferable to always specify the `version` so that we can eventually remove the default.
