### ISSUE TITLE
Hamburger icon is not left padded

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#3372]
## Bug description

The hamburger icon in the header has none (or incorrect) `padding-left`.

## Environment
 - Browser: Firefox
 - Wallet: MetaMask
 - Chain: Polygon

## Steps to reproduce
 1. Reduce window size util sidebar is hidden.
 2. Observe incorrect padding.

## Expected result

Padding on left of hamburger icon matches that above and below it.

## Obtained result

No padding is seemingly set on the left.

## Screenshots

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/c2fb1b23-494a-406b-877a-aa69261b4c65)

**Comment by Dozie2001** [comment]
@iamacook I would like to be assigned to this issue

**Comment by Dozie2001** [comment]
Thank you

**Comment by Dozie2001** [comment]
Having issues getting the some of the environment variables

**Comment by katspaugh** [comment]
Add
```
NEXT_PUBLIC_INFURA_TOKEN=<your own api token>
```
To your .env file.

**Comment by puneetbagewadi** [comment]
@katspaugh @iamacook  if this issue is still open, I can fix this.

**Comment by katspaugh** [comment]
ठीक है भाई, धन्यवाद @puneetbagewadi!

**Comment by puneetbagewadi** [comment]
Hi @katspaugh looks like the issue is fixed. Raising a PR

**Comment by katspaugh** [comment]
Is repo mai push mat karo. Aapke fork se Pull Request karo.

**Comment by puneetbagewadi** [comment]
I accidentally closed the PR  https://github.com/safe-global/safe-wallet-web/pull/3453
now its locked and I can't comment anything on that. Please reopen the PR for me to contribute. @katspaugh @iamacook

**Comment by puneetbagewadi** [comment]
I have a solution for that. Let me know once you unlock the PR @katspaugh @iamacook

**Comment by katspaugh** [comment]
Ab vo khula hai. 👍
