### ISSUE TITLE
Load chain logos from CGW

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3379]
Chain logos in the NetworkSelector and ChainIndicator should be taken from the chains config from CGW/config-service.
They are currently hardcoded.

Unfortunately, CGW failed to implement SVG support, so we'll have to convert the existng SVG logos to PNGs.

## Requirements
* Covert all SVGs to 2x res PNGs
* Tinify them via tinypng.com
* Upload to config-service
* Replace hardcoded files with chainLogoUri field form the configs

**Comment by lance-web3** [comment]
@katspaugh instead of creating a new issue on this repo, can u help me on here?

https://ethereum.stackexchange.com/questions/165302/safe-ui-cant-find-cfg-chain-and-currency-logo

**Comment by katspaugh** [comment]
Someone will help you there, please don't ping me in an unrelated issue.
