### ISSUE TITLE
Execute and replace button look broken in an ipad mini viewPort

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3386]
## Bug description
Check the snapshot

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to a safe where tx are ready to be executed
 2. Change your browser to show an iPad mini viewport
 3. Check the execute and reject buttons

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/4c54c67a-76fd-4b54-b6d5-1657fe4c5fb7)

**Comment by daniel0ar** [comment]
Hi! I got this! Please assign it to me so I can send the PR. It now wraps nicely when shrinking like this:
![image](https://github.com/safe-global/safe-wallet-web/assets/34529009/9bed0690-7b35-4b31-8557-83189cd8f682)

**Comment by katspaugh** [comment]
Thanks, @daniel0ar!
