### ISSUE TITLE
Overlapping buttons when signing a transaction

### ISSUE THREAD

**Issue by jmealy** [safe-global/safe-wallet-web#3403]
## Bug description
For screens with width 900px+, when signing a transaction to execute later, there is overlap between the buttons `Back` and `Add to batch`.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Sepolia

## Steps to reproduce
 1. Create a new transaction. Under `Would you like to execute the transaction immediately?` click `no, later`.
 2. Resize the browser window to be around 900-1000px

## Expected result
You should see the smaller screen view without the sidebar.

## Obtained result
You see the layout for larger screens but with overlapping buttons.

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/17801424/565b369f-2eae-442c-804e-8bb6daadc430)

**Comment by TanyaEfremova** [comment]
Here's an [example](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=10654%3A33763&mode=design&t=unnRvYEJzi6vsfoE-1) of we can show stacked buttons in such cases

Would it be possible to show **Sign** first as a primary action?

**Comment by usame-algan** [comment]
![Image](https://github.com/safe-global/safe-wallet-web/assets/5880855/21d0a508-022b-43db-888a-aa2e895a9b25)

**Comment by Eshwarj** [comment]
Hi @katspaugh @jmealy, I would like to work on this issue. I know the fix for this. can you please assign this issue to me ?

**Comment by katspaugh** [comment]
Theek hai bhai, shukriya! @Eshwarj

**Comment by Eshwarj** [comment]
Hi @katspaugh, I have fixed the issue. Please check this PR https://github.com/safe-global/safe-wallet-web/pull/3471

**Comment by katspaugh** [comment]
@Eshwarj dhanyavaad sir!

**Comment by katspaugh** [comment]
@francovenica please test it on dev.
