### ISSUE TITLE
Cannot execute SignMessageLib.signMessage assembled from tx builder

### ISSUE THREAD

**Issue by chiefbiiko** [safe-global/safe-wallet-web#3406]
## Environment
 - Browser: Chromium
 - Wallet: MetaMask
 - Chain: Gnosis Chain

## Steps to reproduce
 1. Go to the tx builder and assemble a tx with:
    - address `0xd53cd0aB83D845Ac265BE939c57F53AD838012c9`
    - function `signMessage`
    - message `0x68616c6c6f63`
 2. Confirm the tx with $threshold signers
 3. Try execute the tx (will fail)

## Expected result
Executing a `SignMessageLib.signMessage` tx built from the tx builder ui should work.

For `SignMessageLib.signMessage` the tx builder should always use operation `delegatecall` instead of `call`. The latter will always fail as the library function is referring to Safe contract storage that is only available when executing the tx via `delegatecall`.

## Obtained result

The tx builder wrongfully sets operation `call` for `SignMessageLib.signMessage` invocations and there is no ui input to manually change it to `delegatecall`.

## Screenshots

Shows operation `call` wrongfully set for `SignMessageLib.signMessage`:

![safestucksignmsgviaui](https://github.com/safe-global/safe-wallet-web/assets/22937570/6ea99519-e45c-41e4-a1f4-59cb7bfb2900)

**Comment by katspaugh** [comment]
In the `safe-apps-sdk` (and Transaction Builder is using that SDK), we limit delegatecalls to arbitrary contracts on purpose because it entails a massive security risk. We're not looking to change that anytime soon. Delegatecalls to an arbitrary contract can only be performed via our other SDKs like the `safe-core-sdk`.

See https://github.com/safe-global/safe-apps-sdk/issues/65. Thanks!

**Comment by chiefbiiko** [comment]
@katspaugh Please reconsider the case where Safe signers want to perform a multisig message "signature" via the `SignMessageLib`, always deployed at [`0xd53cd0aB83D845Ac265BE939c57F53AD838012c9`](https://github.com/safe-global/safe-smart-account/blob/main/CHANGELOG.md#lib-contracts). I'm only asking to correct the operation to `delegatecall` for this particular static and known address.

For `SignMessageLib.signMessage(msg)` `delegatecall` must be used as the target contract is a library with the method referring to Safe storage (tx builder setting the `call` operation makes the tx unexecutable) AND that `delegatecall` is absolutely safe to use since we are calling into Safe's official [`SignMessageLib`](https://github.com/safe-global/safe-smart-account/blob/main/contracts/libraries/SignMessageLib.sol) - this is not an arbitrary contract.

In the current state, regular (no-code) users are not able to generate a multisig for a message, this limits the usage of Safe's ERC-1271 signature verification flow and multisig message signing in general.

**Comment by katspaugh** [comment]
Feel free to raise with the https://github.com/safe-global/safe-apps-sdk team. Cheers!
