### ISSUE TITLE
Safe as owner - Relayer is not offered as an option for create&execute 

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3412]
## Bug description
A safe as owner, can use the relayer only if the tx is already queued, but if the tx is being created and executed (in safes 1/x) then the option is not available

## Environment
 - Browser: Any
 - Wallet: WC (Safe as owner)
 - Chain: Seplia or GNO (A chain with relayer)
 - Env: current prod 1.30.0

## Steps to reproduce
 1. Have SafeA being owner of SafeB
 2. Have SafeB with a policy of 1/x. SafeA can also be just a 1/x safe
 3. Connect to SafeB with SafeA using WC
 4. Create a tx like send funds in SafeB and select yes, execute

## Expected result
The use or the relayer should be an option

## Obtained result
The option to use the relayer is not present

**Comment by katspaugh** [comment]
Closing because Nested Safes is now its own epic.
