### ISSUE TITLE
REQUEST - Add a how to add a Network Guide

### ISSUE THREAD

**Issue by nblogist** [safe-global/safe-wallet-web#3420]
There have been several changes in the last few months and, trying to add a network is difficult to do efficiently without the help of a guide. Doing so will not only make it easier for new networks to be added but also help grow the Safe{Wallet} project as a whole, making it defacto platform to have multisig on a network.

I think PRs for integrations with other network should also be included to widen the support for Safe{Wallet}; Increasing the support of various network on one URL!

Thank you!

**Comment by katspaugh** [comment]
Are you running your own fork of this app, or are you asking about adding a new chain to app.safe.global?

**Comment by nblogist** [comment]
I am running my own fork, but I think adding contributors' chains to app.safe.global can make it a go-to multisig platform for any chain. A "Guide to Add Networks" will not only broaden its usability but also simplify adding networks in forks, benefiting everyone involved. :)
