### ISSUE TITLE
Trust Wallet+WalletConnect: transaction execution doesn't work 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3434]
## Bug description
Trust Wallet+WalletConnect: transaction execution doesn't work 

## Environment
 - Browser: Chrome
 - Wallet: Trust wallet
 - Chain: Polygon

## Steps to reproduce
 1. Connect Trust wallet via WalletConnect to the web app as a signer
 2. try to sign or execute tx 
 Current result: 
<img width="640" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/7807cde5-b6ce-4bc5-bf6f-57fc71f3cce6">

 https://5afe.slack.com/archives/C0462F65CLD/p1710334244438369 - might be the same issue 
## Expected result
It should be possible to use Trust wallet as a signer for the safe via walletconnect . Also the error message should be changed to more user-friendly to explain the issue better for the user

**Comment by jmealy** [comment]
I wasn't able to reproduce the error here. I tried with creating a safe and adding an owner and both executed fine. Using Trust wallet mobile app as signer. @liliya-soroka can you check if it is still happening for you, and if there is extra context needed to reproduce?

**Comment by francovenica** [comment]
Used trust wallet with my phone, all in polygon

I tried proposing a tx then executing it and then sign&execute all in one action and I didn't have any issues.
