### ISSUE TITLE
Scroll bridge should not be blocked

### ISSUE THREAD

**Issue by ElvisKrop** [safe-global/safe-wallet-web#3435]
## Bug description
Right now scroll.io is included into the list of [BlockedBridges](https://github.com/safe-global/safe-wallet-web/blob/aa8b4249ab4e97ec24f713be387c38bbf55e2d54/src/features/walletconnect/constants.ts#L42) and user can only reject WalletConnect session with scroll.io. It is not correct since user can customize the recipient address. Please move this bridge to the list of [WarnedBridges](https://github.com/safe-global/safe-wallet-web/blob/aa8b4249ab4e97ec24f713be387c38bbf55e2d54/src/features/walletconnect/constants.ts#L67C14-L67C27).

https://github.com/safe-global/safe-wallet-web/assets/47831692/ac2dd007-55d7-441c-9bbe-a38e531c386c

## Environment
 - Browser: any
 - Wallet: any
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. open WalletConnect widget on app.safe.global
 2. open https://scroll.io/bridge
 3. try to establish a connection from Safe{Wallet} to Scroll Bridge 

## Expected result
Safe{Wallet} should warn the user about changing the recipient address.

## Obtained result
Safe{Wallet} allows only to reject WalletConnect session with scroll.io.

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/47831692/90fb6ed8-984f-483c-b421-a8471b1b9e98)

**Comment by katspaugh** [comment]
Thanks! A PR would be appreciated.
