### ISSUE TITLE
Unsupported mastercopy version has "Latest version" green mark

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3436]
## Bug description
Unsupported mastercopy version has "Latest version" green mark
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Polygon

## Steps to reproduce
 1. Go to the safe https://app.safe.global/settings/setup?safe=matic:0x68d231A531BcF34199a825AE568aa79b695f7965

## Screenshots
<img width="1152" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/03c4bccf-3fae-4275-b217-2f4836fce144">

**Comment by daniel0ar** [comment]
Hi! Is this the expected outcome?
![image](https://github.com/safe-global/safe-wallet-web/assets/34529009/10434606-81ab-4080-b0a5-a0bd5aed62f9)
I have added an additional check for safe.version  before showing green mark and label (If there is no version, it won't show that line).

**Comment by katspaugh** [comment]
Can be tested on dev.

**Comment by francovenica** [comment]
LGTM
