### ISSUE TITLE
Visually group multisend-executed txs in the history

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3443]
Currently, when you execute several Safe transacitons using the Bulk Execute button, they are displayed as separate transactions in the history.

However, they all share the same tx hash (because they were executed by the Multisend contract as one tx). And if you click on the Etherscan link in the tx details of these txs, they obviously lead to the same Etherscan page that shows them as a Multisend contract interaction.

Since this discrepancy can be confusing to users, we should probably somehow mark bulk-executed txs in the UI, perhaps visually group them like we do with conflicting nonce txs.

## Design
[Figma](https://www.figma.com/proto/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?page-id=5794%3A183021&type=design&node-id=10780-98066&viewport=-111%2C14953%2C0.88&t=N0YFEO05M4pwpkfQ-1&scaling=min-zoom&starting-point-node-id=10780%3A98066)

<img width="1212" alt="Screenshot 2024-04-26 at 08 07 07" src="https://github.com/safe-global/safe-wallet-web/assets/381895/137e99fc-270b-4192-97ab-5d2ae6d3867c">

**Comment by katspaugh** [comment]
@TanyaEfremova a low-prio low-key chill design request :)

**Comment by TanyaEfremova** [comment]
There were [some prototypes](https://www.figma.com/file/VyA38zUPbJ2zflzCIYR6Nu/Swap?type=design&node-id=5640%3A16797&mode=design&t=0hOJamCnhF2FvEdl-1) done for Swaps already, so I could iterate on them :)

**Comment by TanyaEfremova** [comment]
Designs are ready for review. [See Figma](https://www.figma.com/proto/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?page-id=5794%3A183021&type=design&node-id=10780-98066&viewport=-111%2C14953%2C0.88&t=N0YFEO05M4pwpkfQ-1&scaling=min-zoom&starting-point-node-id=10780%3A98066)

**Comment by liliya-soroka** [comment]
Verified
