### ISSUE TITLE
Add option to hide assets & balances from non-signers

### ISSUE THREAD

**Issue by SKYBITDev3** [safe-global/safe-wallet-web#3449]
Some users may want to keep their wealth as private as possible, including to recoverers.

The recoverer needs to be given the Safe address. When she loads it up at app.safe.global, she'll see all assets and balances. This may not be desirable to the owner of the assets.

e.g. if a gold-digger wife finds out that her husband has millions of dollars worth of assets stashed away then that introduces a number of risks to the husband.

So it'd be better if she only sees such sensitive information only after execution of the recovery, as the legal heir.

So please add an option in settings to hide assets and balances in the UI.

**Comment by katspaugh** [comment]
While it's easy to hide balances in the UI, this information is onchain and readily available if you paste the safe address on Etherscan or, e.g., Zerion. So I'll go ahead and close this issue, but we appreciate the suggestion.

**Comment by SKYBITDev3** [comment]
> this information is onchain and readily available if you paste the safe address on Etherscan

I know that and you all do too, but you need to be able to also think from the perspective of non-tech users.

Just because the information could be found elsewhere if one were to dig around, it doesn't mean we'd want it all to be explicitly shown, especially if the information is sensitive, like how much money you have in bank accounts or investments, medical history, residential address, or flight history.

You don't see Wikipedia displaying such information as where [Britney Spears](https://en.wikipedia.org/wiki/Britney_Spears) or other famous people live, even though many people already know where they live, probably out of respect for their privacy.

So just because the sensitive information can be found, it doesn't mean it's a great idea to show it.

Please **respect the privacy** of the users of your platform.
