### ISSUE TITLE
Recovery modal - Info text broken colors in dark mode

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3464]
## Bug description
An info text had it's colors changed and is broken, the text is hard to read.

## Environment
 - Browser: Chrome
 - Chain: any
 - Env: dev

## Steps to reproduce
 1. Go to a safe you own 
 2. Start a recovery setup
 3. Check the modal where you can set the recoverer in dark mode

## Expected result
This is how it looks in prod
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/d1fc81bd-d61e-4c8c-b464-6c892db3aa2b)

## Obtained result
Broken in dev:
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/ee23da29-250a-418c-8a14-1c8bf7f63649)

**Comment by usame-algan** [comment]
@TanyaEfremova should we switch back to `#2F2318` for the warning background color in dark mode or use a different hex?
