### ISSUE TITLE
Notification setting button makes the UI unclickable

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3465]
## Bug description
Clicking the Settings button in the Notifications top bar popUp (the one that displayes after cliking the bell icon) it takes you to the settings, but it sets a layer in the page that makes the UI impossible to click

## Environment
 - Browser: Chrome
 - Env: Prod 1.31
 
## Steps to reproduce
 1. Go to any safe
 2. Click the bell icon > Settings 
 3. Try to click anything in the screen

## Expected result
Should be able to use the UI as usual

## Obtained result
The entire app becomes unclickable

## Screenshots
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/92a8b16f-1b16-4eed-84fe-fb30ea7a46fe)
![image](https://github.com/safe-global/safe-wallet-web/assets/4503659/8f26c620-8491-417c-acc7-c1c6cc1f1899)

**Comment by katspaugh** [comment]
The MUI popup should be closed after the navigation. Somehow it you close it before it won’t properly disappear.

**Comment by Friedheilm** [comment]
FYI it's still stably reproduced, even after UI has been updated to 1.32.1.  With the same steps steps and result as author described.
