### ISSUE TITLE
Automation: Enable switching automation wallets inside Cypress tests

### ISSUE THREAD

**Issue by mike10ca** [safe-global/safe-wallet-web#3503]
Currently, upon starting Cypress tests, a single automation owner is being loaded and used across our tests.

As our tests coverage increases, we need to cover cases which include more than 1 automation owner. To do this we need to be able to switch between multiple automation owners directly inside our tests. 

We need to extract 2 addresses from the seed phrase instead of 1 and be able to navigate between them to cover 2/N policy

**Comment by katspaugh** [comment]
I've deployed the app. You can use this URL in tests:
https://safe-apps-test-app.pages.dev/

Repo: https://github.com/5afe/safe-apps-test-app

**Comment by liliya-soroka** [comment]
Verified. the task was implemented
