### ISSUE TITLE
Wrong connection to the wallet when there are a view wallet extensions in the Chrome

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3523]
## Bug description
Wrong connection to the wallet when there are a view wallet extensions in the Chrome

## Environment
 - Browser: Chrome
 - Wallet: MetaMask/OKX wallet extation
 - Chain: Ethereum mainnet/any

## Steps to reproduce
 1. Add a view wallet extations ( in my case it's MM, MM institution, OKX )
 2. connect to MM
 Current result: The app is connected to the OKX , but shows that it's connected to the MM
OKX is the latest installed extantion

## Expected result
The user should be connected to the selected extation.
The correct icon of the connected wallet should be shown always

## Screenshots

https://github.com/safe-global/safe-wallet-web/assets/338622/c913c440-b3c2-4fd3-a655-a6464dcb993a

**Comment by katspaugh** [comment]
I've just tested with MetaMask, Rabby and Zerion extensions installed and it connects to the right one every time.

<img width="854" alt="Screenshot 2024-08-08 at 12 12 59" src="https://github.com/user-attachments/assets/66ae7ab2-42dd-4356-abce-0eae07bbc28b">
