### ISSUE TITLE
Function  execTransaction is failing 

### ISSUE THREAD

**Issue by Malikrehman00107** [safe-global/safe-wallet-web#3533]
We create a safe and when we send the funds form safe.

` execTransaction( `  Is failing .

Here is Trx Hash: https://sepolia.etherscan.io/tx/0x02cbb2c32af0ae333d90e704a630d3638b53005ba9dbb3022028521b8fe9d71d

Safe Smart Contract : https://sepolia.etherscan.io/address/0x159bd467fafcfa348d2b5f357b23aa1d70e814a0

need your attention here please

**Comment by Malikrehman00107** [comment]
@katspaugh please! 

@faisal-anwar825 here you can follow up!

**Comment by katspaugh** [comment]
This is the wrong repo for this, please reach out in the SDK repo.

**Comment by Malikrehman00107** [comment]
@katspaugh  can you share the SDK repo please ?

**Comment by katspaugh** [comment]
https://github.com/safe-global/safe-core-sdk
