### ISSUE TITLE
Bug (Delete from the Queue)

### ISSUE THREAD

**Issue by benjileibo** [safe-global/safe-wallet-web#3549]
## Bug description

We used the Delete from the Queue function, but now cannot execute the transaction with the next nonce. Nor can we reject the transaction we deleted from the Queue. Our Safe is not non-functional. Link below. Please help. 

https://app.safe.global/transactions/queue?safe=eth:0x7CC7228EDe433a08F1e7989E0f1ff99474e12A0E

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to https://app.safe.global/transactions/queue?safe=eth:0x7CC7228EDe433a08F1e7989E0f1ff99474e12A0E
 2. Look at transaction queue
 3. 30 is unexecutable. 

## Expected result
Executing the transaction with Nonce 30 and cancellation of transaction with Nonce 29.

## Obtained result
Disappearance of transaction with Nonce 29 and transaction with nonce 30 is unexecutable. 

## Screenshots
![Screenshot 2024-04-11 at 12 23 40 PM](https://github.com/safe-global/safe-wallet-web/assets/99936302/2686d050-0b0e-4178-ae8a-36715df3bd0d)

**Comment by katspaugh** [comment]
Sorry to hear you encountered this bug. You can unfreeze your safe by creating a transaction with nonce 29 (set it manually when making the tx).

**Comment by katspaugh** [comment]
I'll close this issue since I assume your Safe is now unblocked. We'll solve the underlying cause in #3551.
Cheers!
