### ISSUE TITLE
Handle zero exchange rate situations in a sensible manner

### ISSUE THREAD

**Issue by svanegmond** [safe-global/safe-wallet-web#3557]
## What is the feature about

When an exchange rate is zero or unfindable, show the native token amount, or anything coherent, instead of $0.00

**Comment by svanegmond** [comment]
Our current safe implementation returns data like this when querying a balance. 
https://safe.shyft.network/cgw/v1/chains/7341/safes/0xCb29eD1fc2ce0d4403524D687Aa53B25e2648572/balances/usd?trusted=false

Since this is /usd is this a configuration issue on my end?  Even though our token is publically traded, we don't care about the $ equivalence for our Safe implementation.

**Comment by katspaugh** [comment]
Not sure I fully follow. This is the frontend repo. Where in the UI do you want to see native token amount instead of 0$?

If this feature request is for CGW, please file it in the [CGW repo](https://github.com/safe-global/safe-client-gateway).

**Comment by katspaugh** [comment]
I see. This seems to be somewhat of a special case for Shyft (which we don’t support officially). Normally if a Safe would have native tokens, it would also have a fiat balance as the native token would have a price.
We’re open to a pull request though.
