### ISSUE TITLE
Update the EIP-5792 implementation

### ISSUE THREAD

**Issue by katspaugh** [safe-global/safe-wallet-web#3576]
Our [implementation of 5792](https://github.com/safe-global/safe-wallet-web/blob/dev/src/services/safe-wallet-provider/index.ts#L128-L150) seems to be outdated, the calls have been renamed in the EIP: https://eips.ethereum.org/EIPS/eip-5792

## Requirements
* Update the RPC method names
* Check if the params stayed the same or also need to be updated

**Comment by liliya-soroka** [comment]
Verified
