### ISSUE TITLE
Enable Tenderly simulation to signers ahead of signing

### ISSUE THREAD

**Issue by tomislavmamic** [safe-global/safe-wallet-web#3592]
## What is the feature about

When using more complex tools, like Jumper Exchange, Safe doesn't show enough information to the signers. If they want to review where the money is actually going, they can't. Tenderly review shows this, albeit in a bit complex way. I propose you make it possible to simulate transaction if executed by any signer.

**Comment by katspaugh** [comment]
Not sure I follow. You can simulate with Ternderly when both signing and executing.

<img width="576" alt="Screenshot 2024-04-22 at 12 03 28" src="https://github.com/safe-global/safe-wallet-web/assets/381895/43c0dd43-0b01-44e8-a0ac-0374895f184d">

**Comment by tomislavmamic** [comment]
![CleanShot 2024-04-24 at 11 08 43@2x](https://github.com/safe-global/safe-wallet-web/assets/15949483/79549336-5aaa-422a-8b78-9a1029c0058b)
Aaah sorry, for some reason I missed this link

**Comment by katspaugh** [comment]
cc @TanyaEfremova maybe it make more sense to move that link to the Simulation block itself. It's just one line.

**Comment by TanyaEfremova** [comment]
@katspaugh Since both Redefine and Tenderly notifications are shown on the right side, I'll have to review both first to keep things consistent. Thanks for flagging!
