### ISSUE TITLE
[Safe creation] Improve the status screen

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#3612]
## What is the feature about

The status screen when creating a safe has multiple UX issues as documented [here](https://www.notion.so/safe-global/Better-handling-of-safe-creation-051abb7ffe8948da8bd638017af96d97) and #1484, #1871, [Slack](https://5afe.slack.com/archives/C04MQSC3R7Y/p1710951036300699)

## The list of requirements

- [ ] Only move to the status screen once the user has confirmed the transaction in their wallet
- [ ] Rework the Retry and Cancel button
- [ ] Retry should navigate the user back to the review screen with the previous setup filled out
- [ ] Cancel should take the user back to the welcome page
- [ ] Remove the stepper and instead only show the a "Check Status" link for the block explorer
- [ ] Show a clear pending state in the UI and inform the user about the status of their transaction

## Designs/sketches

- [Figma](https://www.figma.com/file/ptTs6lDBeUuLNySroJ5PiF/Web-Master-File?type=design&node-id=10822-4396&mode=design&t=WMKNizUHCrqhabci-0)

## Links

- [Notion](https://www.notion.so/safe-global/Better-handling-of-safe-creation-051abb7ffe8948da8bd638017af96d97)

**Comment by schmanu** [comment]
I think when tackling this we should also fix https://github.com/safe-global/safe-wallet-web/issues/1330

My best guess is that we wait for the safeTxHash. We should detect that it is a safeTxHash and poll that tx or always poll the SafeInfo additionally.

**Comment by usame-algan** [comment]
> I think when tackling this we should also fix #1330
> 
> My best guess is that we wait for the safeTxHash. We should detect that it is a safeTxHash and poll that tx or always poll the SafeInfo additionally.

I haven't tested it yet but I think with the changes implemented in #3778 the user would now simply wait on the status screen without a timeout until the safe has executed the creation. We use the same global hook to monitor the txHash as we do for counterfactual safes so we should become aware of the transaction being executed.

**Comment by usame-algan** [comment]
Just tested #1330 again on this PR and can confirm that it doesn't work when signing but not executing the transaction in the parent safe. The tx monitor is trying to poll for the txHash (which is actually the safeTxHash) which it can't find so it errors out after a while. We could detect this as @schmanu suggests and in that case poll for either the safe info or the safeTxHash through our services.
