### ISSUE TITLE
When sending tokens, the address dropdown suggests current safe for recipient address.

### ISSUE THREAD

**Issue by jmealy** [safe-global/safe-wallet-web#3663]
## Bug description
When choosing an address for a send transaction, it is possible to select the address of the safe you are currently using from the address book. [1]
An error will only be shown when the transaction is signed or executed, and is not specific (`unprocessible entity`) [2]

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: sepolia
 
## Steps to reproduce
 1. Make sure the safe you're using is added and in your address book.
 2. Go to `new transaction` -> `send tokens`
 3. After clicking on the address input, it will show suggestions from your address book, including your current safe.
 4. If you try to execute the tx it will show an error [2]

## Expected result
I would suggest showing an input error for the address input field when the selected address is the same as the current safe.

## Obtained result
An error only shows upon execution and it is not specific.

## Screenshots
[1]
<img width="795" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/17801424/3e43be5c-576a-401b-8dd3-21b59c07f9c2">

[2]
![image](https://github.com/safe-global/safe-wallet-web/assets/17801424/07ede8f4-fbcf-4bd8-84d0-66da4c1aae3a)

**Comment by usame-algan** [comment]
Is this the error when trying to execute the transaction via relay? Afaik we don't allow transactions from a safe to itself in our relayer config. Otherwise it usually works sending funds to myself and imo shouldn't be an issue.

**Comment by liliya-soroka** [comment]
the error is displayed because we blocked the sending tokens to themself via Relay, but it was decided to keep it in general .
I will close the issue as won't fix
