### ISSUE TITLE
Enable safe-test-app running for Cypress tests

### ISSUE THREAD

**Issue by mike10ca** [safe-global/safe-wallet-web#3695]
In order to provide extended coverage for safe messages, we need to have the [safe-test-app ](https://github.com/safe-global/safe-apps-sdk/tree/main/packages/safe-apps-test-app)running and be available for Cypress tests. As part of the tests, the app will be accessed through custom apps.

Available options:
1. Start the app in GutHub workflow each time the tests run. 
2. Run it permanents the same way as we run our other apps.

**Comment by katspaugh** [comment]
The easiest would be to copy the app to a new repo in the 5afe org, and deploy it using CloudFlare Pages.

**Comment by katspaugh** [comment]
I've deployed the app. You can use this URL in tests:
https://safe-apps-test-app.pages.dev/

Repo: https://github.com/5afe/safe-apps-test-app
