### ISSUE TITLE
Add Optimism Sepolia to Create Safe UI

### ISSUE THREAD

**Issue by blmalone** [safe-global/safe-wallet-web#3696]
## What is the feature about

When running the command below:
```bash
curl 'https://safe-client.safe.global/v1/chains'  -H 'accept: */*' 
```
Sepolia Optimism should be included. Lots of activity happens on this testnet and add this would help a lot for test flows that included Safes.
<img width="206" alt="Screenshot 2024-05-13 at 14 25 23" src="https://github.com/safe-global/safe-wallet-web/assets/15608778/151e5438-b5e9-4801-8388-b7ee78a331cc">

**Comment by johannesmoormann** [comment]
wrong repo for these kind of requests but our network team will reach out to you.
