### ISSUE TITLE
Send X ETH is included into "Interact with" filed and no action details for  Wrap ETH

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3714]
## Bug description
Send X ETH is included in the "Interact with" filed under (...... and no action details for  Wrap ETH

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Sepolia

## Steps to reproduce
 1. Start wrapping ETH to WETH ( any safe app or native Swap)
 2. check create tx screen 
 Current result: There is "Interact with (.....Contract_ Address" in the header and no details under deposit action in the tx details

3. create tx and check tx details in Queued
Current result: There is "deposit" as the action name but no more detailed information 

## Expected result
The information about sending eth + amount should be displayed for the user 

## Screenshots
<img width="852" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/9dfa6dac-89e4-4511-841f-7c6219e28a9f">
<img width="634" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/47672f2c-ce85-4d3f-b9f1-1e589b0a99ad">

**Comment by katspaugh** [comment]
WETH deposits are correctly displayed now.

<img width="874" alt="Screenshot 2024-08-08 at 12 16 01" src="https://github.com/user-attachments/assets/d7774a28-8f41-45c8-838f-386416b4b7dc">
