### ISSUE TITLE
Upgrade Safe-Wallet-web version

### ISSUE THREAD

**Issue by happyleow** [safe-global/safe-wallet-web#3720]
## What is the feature about
Upgrade Safe-Wallet-web version based on new safe-deployment(v1.36.0) release publishment.

## The list of requirements
I want Safe-Wallet-web to support Safe-Deployment v1.36.0 so i can operate the `safe-wallet-web` for the new blockchain network.

## Links
Safe-Deployment: https://github.com/safe-global/safe-deployments/releases/tag/v1.36.0
Safe-Core-SDK: https://github.com/safe-global/safe-core-sdk/releases/tag/r39

**Comment by happyleow** [comment]
Hello, my PR was merged already but not included in the latest release version.
Could you let me know the approximate timeframe for releasing the new version including my PR?
It's necessary to support the new blockchain network.

**Comment by katspaugh** [comment]
We generally release every two weeks.

**Comment by happyleow** [comment]
@katspaugh Thanks for your info.
This is a high-priority task for us, we want to operate the `safe-infrastructure` repo on our new chain asap, and upgrading `safe-wallet-web` is the last step.
Ideally, we'd like to expedite the timeframe, so please advise on any steps we can take to accelerate this integration.
Thank you for your support.

**Comment by katspaugh** [comment]
Not sure I understand how an official release on our domain would unblock you. Do you want the docker image published or something else?

**Comment by happyleow** [comment]
Yes, it is likely to publish the new docker image.
I am referring to the following issue in the `safe-infrastructure` repo.
https://github.com/safe-global/safe-infrastructure/issues/124#issuecomment-1877097932
UI version should be updated so I can specify the latest UI version(guess it's `safe-wallet-web`) in env file in the `safe-infrastructure` repo.
Please correct me if I am wrong.

**Comment by katspaugh** [comment]
I’ll see if I can publish the docker image separately, sooner.

**Comment by happyleow** [comment]
Hi @katspaugh Thank you, please update me when you publish the docker image.

**Comment by happyleow** [comment]
Hello @katspaugh how are you, i noticed there's a new release version published today but my PR is not included.
Do you have an estimation of the time for publishing a new release including my PR? Thanks a lot.

**Comment by katspaugh** [comment]
Actually your PR is included. The release notes aren’t complete. See the commit list here: https://github.com/safe-global/safe-wallet-web/pull/3737

**Comment by happyleow** [comment]
Ah okay, thanks for your info.
