### ISSUE TITLE
Misalignment of pending transactions on dashboard

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#3762]
## Bug description

If the name of the recipient/action is too wide in the list of pending transactions, the threshold indicator and arrow move to a newline that is not right aligned.

## Steps to reproduce
 1. Queue a transaction with a long-named recipient and observe the misaligned indicator.

## Expected result

Threshold indicator is aligned to the right.

## Obtained result

Threshold is aligned to the left.

## Screenshots

![image](https://github.com/safe-global/safe-wallet-web/assets/20442784/c011f8ad-b519-438e-9267-4bc5c3af57df)

**Comment by Khemmie-Ray** [comment]
Hi @iamacook is this issue still available, I will like to work on it?

**Comment by TanyaEfremova** [comment]
The long name can be truncated in this case, I don't think, it's critical to not see the full function name in this view.
