### ISSUE TITLE
Error decoding NFT approval transaction

### ISSUE THREAD

**Issue by solidoracle** [safe-global/safe-wallet-web#3774]
## Bug description
When executing a transaction that has within it an approval of erc721 to enable its transfer to another wallet, this error comes up:
`Error while decoding approval transaction`

![image (11)](https://github.com/safe-global/safe-wallet-web/assets/105349716/5e8d0254-a5de-450d-a19f-82cc94427a16)

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Sepolia testnet
 
## Steps to reproduce
 1. Setup a contract function that has a transfer of nft within it. While doing the multisend to the gnosis module, you must first execute the approval to transfer this nft to another wallet. Then this decoding error message comes up

**Comment by katspaugh** [comment]
cc @schmanu
