### ISSUE TITLE
After using a link in the notifications dropdown the page becomes unclickable

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#3810]
## Bug description
After using a link in the notifications that show up in the topbar (using the bell icon) to reach a tx, the page becomes unclickable
It has to be the links that are displayed from the notification topbar. if you use the link in the notifications card that pops up then it works fine

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Create a send funds tx
 2. Execute it
 3. Got to somewhere outside of that tx details page (assets, history, dashboard, etc)
 4. Open the notifications using the bell icon on the top
 5. Click on the notifications that takes to that tx
 6. Try to click anywhere in the page

## Obtained result
Nothing is clickable, like if there was an overlay on top of the whole page. The user has to reload the page

## Screenshots
![tx notifictaions](https://github.com/safe-global/safe-wallet-web/assets/4503659/02488c52-1c7d-4b9b-a301-d7f3f08793cb)

**Comment by compojoom** [comment]
Have you tried restarting your browser? I can't reproduce this on my end.

**Comment by francovenica** [comment]
It happens to me pretty often, but it seems that is not will all notifications. Try with that specific one that says "Validating"
