### ISSUE TITLE
Left Menu - Safe List Showing Invalid Balance & Pending Txns

### ISSUE THREAD

**Issue by bh2smith** [safe-global/safe-wallet-web#3813]
When a safe is deployed with the same address on multiple networks, the bar in the side is incorrectly showing pending transactions on networks that do not have any. It is also showing USD balances from other networks:

See this Example Safe: 0xD011a7e124181336ED417B737A495745F150d248
1. Has a pending TX on mainnet and no other pending transactions (showing up on other networks). 
2. Has a balance of 36.93 on mainnet, 38.43 on BNB and <0.01 on GNO but showing the mainnet balance everywhere in the left bar
3. Another weird point: both of the issues described here do not appear to affect the Polygon deployment of this safe. That is, neither the pending tx or incorrect USD balance appear there.

![telegram-cloud-photo-size-2-5413744485369764197-y](https://github.com/safe-global/safe-wallet-web/assets/11778116/e6ca8b46-90f1-4486-8ef7-5538f36135a5)

**Comment by katspaugh** [comment]
Thanks for the report Ben! This has been fixed and will be live next week.

**Comment by bh2smith** [comment]
Awesome news @katspaugh. Could you link the related PR?

**Comment by katspaugh** [comment]
Sure. https://github.com/safe-global/safe-wallet-web/pull/3795

**Comment by katspaugh** [comment]
@bh2smith FYI this is now fixed in prod.
