### ISSUE TITLE
Use Gateway instead of Transaction Service to fetch module ID

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#3815]
## What is the feature about

In order to get the module ID of a module-executed transaction, it is necessary to query using the transaction hash. However, the Gateway did not support this and the Transaction Service was [therefore being used directly](https://github.com/safe-global/safe-wallet-web/pull/3768#discussion_r1622213573). We have since implemented a `transaction_hash` query on the `module-transactions` endpoint of the Gateway to support this.

Fetching of the module ID from the Transaction Service should now be ported to the Gateway. The ID [can be retrieved from the `txId`](https://github.com/safe-global/safe-client-gateway/blob/8f90c03106c1ce48f7420522e6bad906bda3a67d/src/routes/transactions/transactions.service.ts#L59-L66).

Note: we will eventually [return the module ID in the response](https://github.com/safe-global/safe-client-gateway/issues/1613) meaning that it need not be destructure from the `txId`.

## The list of requirements

- Migrate fetch from Transaction Service to Gateway
- Destructure module ID from `txId`

(The SDK will need first be updated for type safety)

**Comment by katspaugh** [comment]
This is fixed in https://github.com/safe-global/safe-wallet-web/pull/3869/commits/4e61b3882819edc03cd5ed3c5b09dbd8a8409dc4
