### ISSUE TITLE
Align "Account" capitalization (1 min fix)

### ISSUE THREAD

**Issue by kirkkonen** [safe-global/safe-wallet-web#3825]
As agreed on the collab testing session, make the word "Account" capitalized:

![Image](https://github.com/safe-global/safe-wallet-web/assets/5926677/fa3d8905-a9eb-48da-baf8-9a9137d0f518)

**Comment by katspaugh** [comment]
It should be either "Safe Account" (a brand thing) or just "account" (a regular noun, lowercase).

**Comment by katspaugh** [comment]
@kirkkonen I suggest we close this w/o changing anything as the current spelling is consistent with what I wrote above.
