### ISSUE TITLE
Prepopulate the address on creating an address book entry

### ISSUE THREAD

**Issue by kirkkonen** [safe-global/safe-wallet-web#3826]
As agreed on the collab testing session, let's fix this one to smoothen adding addresses to the book (another way to battle address poisoning too):

![Image](https://github.com/safe-global/safe-wallet-web/assets/5926677/f2708bfa-1efd-4a29-9031-ad1c955c564a)

The form is currently empty, expected to get the address pre-filled:

![Image](https://github.com/safe-global/safe-wallet-web/assets/5926677/946e8cdd-42a1-48d8-b14a-2bdc8a150ef4)

**Comment by usame-algan** [comment]
I think this is actually a bug since the address in the screenshot is already added. If its an address thats not in the address book yet and a user presses the button it correctly pre-populates the input. We should instead hide this button if the address is already in the address book.
