### ISSUE TITLE
Web3onboard metamask

### ISSUE THREAD

**Issue by compojoom** [safe-global/safe-wallet-web#3841]
## What is the feature about
Adapt web3onboard/metamask: https://onboard.blocknative.com/docs/wallets/metamask

Benefits:
- Strong Connection Health: Persistent connections with MetaMask mobile app for up to 30 days via a new async communication layer.
- Natively supports EIP6963.

If we use it, in our connect modal users would see metamask:
![grafik](https://github.com/safe-global/safe-wallet-web/assets/693770/5ae1fe98-f9a0-4f43-8de4-6bb2f7e1ebde)

**Comment by katspaugh** [comment]
Closing due to bugs and UX issues with the new module.
