### ISSUE TITLE
Fix separators in different sections of interface

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-wallet-web#3870]
## Bug description
1. Modals: Decrease separator thickness to 1px (as we don't have 2px dividers anywhere else). This should be applied to all modals, not only modals shown below.
<img width="616" alt="Screenshot 2024-06-25 at 15 41 05" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/3e4aafad-1ab0-4048-b059-7a334a8573ca">
<img width="605" alt="Screenshot 2024-06-25 at 15 44 59" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/5fc18b0c-ba8e-4c47-9421-4c1e1373dd98">
<img width="617" alt="Screenshot 2024-06-25 at 15 44 32" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/2c561eb7-1669-44aa-a5c1-d25ba967510b">

3. Swaps: Remove a line above the order details in expanded transactions in history and queue (we don't have them in other transactions)
<img width="850" alt="Screenshot 2024-06-25 at 15 44 04" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/8011b97a-ff2f-4fda-a73c-f61a055cf029">

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to e.g. Address book and click Import or Export, see modal
 2. Make a swap and expand a transaction in history and/or queu

## Expected result
Described above.

**Comment by MHarisAshfaq** [comment]
Hi @TanyaEfremova, I hope you're doing well. I just wanted to ask a question
- How many modals require a separator thickness update to 1px?

**Comment by TanyaEfremova** [comment]
Hey @MHarisAshfaq , here is an overview of all the modals requiring adjusted separators.

In total, it is 5 modals.

<img width="597" alt="Screens
<img width="597" alt="Screenshot 2024-07-01 at 17 54 46" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/b389a69a-3332-4ff6-9351-242036277df6">
<img width="599" alt="Screenshot 2024-07-01 at 17 54 54" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/4d9f2b66-861b-4975-98a2-180194b7516f">
<img width="480" alt="Screenshot 2024-07-01 at 17 55 01" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/657920ab-0443-4af0-b381-1c4997e185cc">
hot 2024-07-01 at 17 53 51" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/e22870ca-0e41-4373-8352-bc3cda57d7a6">
<img width="484" alt="Screenshot 2024-07-01 at 17 54 40" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/8f0aa5d9-0184-405b-98ed-654c899433cb">

**Comment by MHarisAshfaq** [comment]
@TanyaEfremova Please assign this task to me. I want to do it.

**Comment by MHarisAshfaq** [comment]
@TanyaEfremova I have raised the [PR](https://github.com/safe-global/safe-wallet-web/pull/3893) for this issue. Please assign the relevant person for the review. Thank you for the guidance.
