### ISSUE TITLE
Remove border from message txs in History

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-wallet-web#3871]
## Bug description
Remove the border from the transactions in Messages tab, so that they are the same as other transaction cells in History.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to a Safe account with messages
 2. Open Messages tab in Transactions

## Expected result
No border shown, like on the screenshot below.
<img width="427" alt="Screenshot 2024-06-25 at 15 53 22" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/89f64d89-83f4-409c-91c7-218fee54c6d1">

## Screenshots
<img width="498" alt="Screenshot 2024-06-25 at 15 51 58" src="https://github.com/safe-global/safe-wallet-web/assets/93707525/477a1f40-1722-4291-8a97-448f1ee1cef3">

**Comment by MHarisAshfaq** [comment]
@TanyaEfremova I want to do this task. Please assign it to me.

**Comment by katspaugh** [comment]
Theek hai, chalo bhai sahab! Agar khuch savaal hai, to mujse puchiye :)

**Comment by MHarisAshfaq** [comment]
@katspaugh I encountered difficulties during the initial setup, specifically configuring the required environment variables. Despite following the instructions in the README file, I am struggling to correctly configure all the necessary variables.

Could you please provide a list of the required environment variables needed to run the UI? This information would greatly help me proceed with my contributions.

**Comment by MHarisAshfaq** [comment]
@katspaugh I have raised the [PR](https://github.com/safe-global/safe-wallet-web/pull/3874). Please have a look and let me know If anything further is required. Thanks for your guidance.
