### ISSUE TITLE
Messages: signing in 2/n safe doesn't work for the https://niftyfair.io/linea

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3934]
## Bug description
signing in 2/n safe doesn't work for the https://niftyfair.io/linea

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Linea

## Steps to reproduce
 1. Go to  https://niftyfair.io/linea
 2. open safe on Linea
 3. try to connect using WC 
 4. click sign in 
 5. sign message in Safe UI as 2 owners
 Current result: The safe is not connected to the dapp.
At the same time it works in case of signing message in 1/n safe

**Comment by katspaugh** [comment]
Likely due to that particular app not supporting EIP-1271.
