### ISSUE TITLE
 "could not coalesce error" error on UI is shown when balance=0 in the trezor wallet

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#3935]
## Bug description
 "could not coalesce error" error on UI is shown when balance=0 in the trezor wallet
## Environment
 - Browser: Chrome
 - Wallet: Trezor
 - Chain: any

## Steps to reproduce
 1. connect Trezor signer with balance=0
 2. try to execute tx using such signer
## Expected result
The user should be informed that the balance is 0 and this is the reason why execution is not possible 
## Obtained result
<img width="597" alt="image" src="https://github.com/safe-global/safe-wallet-web/assets/338622/19f52c8b-ddd3-4a07-9172-6f9c780d37de">

**Comment by katspaugh** [comment]
Although the red error details are quite cryptic, on your screenshot, it does show a blue warning about not enough funds.
