### ISSUE TITLE
Don't cache pages and resources on new deployment

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#3944]
## What is the problem

When deploying a new version of the app, old files are still referenced for some users e.g. if they kept the app open before deployment which can lead to unexpected behaviour.

## Steps to reproduce

Need to figure out the root cause of this issue. Some assumptions:

- Next PWA could cache old files
- The HTML files keep their filename between deployments and could reference old chunks

**Comment by katspaugh** [comment]
Closing this because it's not on the JS side, static file caching is configured on the server (CloudFront).
@usame-algan please feel free to start a notion doc outlining the problem and share it with devops.
