### ISSUE TITLE
What's new sidebar search and close are not working

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#3965]
## Bug description

The search and close buttons in the What's new sidebar are not functional

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Open the app
 2. Open the Whats new sidebar
 3. Press the search or close button

## Expected result

Search and Close should work OR be hidden

## Obtained result

Search and Close are not working

## Screenshots
<img width="453" alt="Screenshot 2024-07-17 at 15 44 10" src="https://github.com/user-attachments/assets/b5615725-9b6e-40cf-8d33-bd33f8a3acf9">

**Comment by usame-algan** [comment]
I can't reproduce this on desktop anymore and on mobile I am not able to open the Whats new sidebar 🤔 

@francovenica could you check this on mobile?

**Comment by katspaugh** [comment]
On mobile, the What's New link doesn't work at all. I'll close this one and make a new issue.
