### ISSUE TITLE
Account list item contents are misaligned for smaller screens

### ISSUE THREAD

**Issue by jmealy** [safe-global/safe-wallet-web#3970]
## Bug description
For smaller screens the Safe address and safe balance on the accounts screen become misaligned.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Sepolia

## Steps to reproduce
 1. Go to `/welcome/accounts`
 2. Change the screen width to around 500px

## Expected result
Contents of account list item are centered as they are for larger screens.

## Obtained result
The contents become misaligned.

## Screenshots
![image](https://github.com/user-attachments/assets/08cebddb-fc6d-407b-8d27-e91e4aeb57ae)

**Comment by katspaugh** [comment]
Oh snap.

**Comment by SebastianLF** [comment]
Can I work on this one ?

**Comment by katspaugh** [comment]
No, up for grabs.
