### ISSUE TITLE
Incomplete tx hash retrieval via WalletConnect with wagmi

### ISSUE THREAD

**Issue by JorisZierold** [safe-global/safe-wallet-web#3972]
## Bug description
We want to support Gnosis Safe multi-signature wallets in our application using wagmi and WalletConnect.

When a user connected through WalletConnect signs a tx requiring multiple confirmations (e.g., 2 out of 3 signers), the returned data from the tx is safeTxHash instead of the actual tx hash. The documentation at Gnosis Safe Help clarifies that safeTxHash is specific to the Safe and not the Ethereum tx hash (https://help.safe.global/en/articles/40814-what-is-the-safe-transaction-hash-safetxhash). This behavior complicates monitoring the on-chain tx that might be triggered from the Gnosis Safe tx.

## Environment
 - Browser: Chrome
 - Wallet: Safe with MetaMask as Signer
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Connect to dApp via WalletConnect 
 2. Prompt user to sign tx via writeContract
 3. Sign tx with Signer 1
 4. onSuccess gets executed with safeTxHash as data
 5. Sign tx with Signer 2, dApp is unaware

## Expected result
We expect to receive the Ethereum tx hash upon the transaction's execution so that we can monitor and confirm its status on the blockchain.

The onSuccess callback from useWriteContract provides a safeTxHash which does not allow us to monitor the Ethereum network directly.

Code Example:
```

  const { writeContract } = useWriteContract(
    {
      mutation: {
        onSuccess(data) {
          setHash(data);
          showToast({ title: 'Transaction Pending', txHash: data });
        },
        onSettled() {
          closeWaitForSignatureModal();
        },
      },
    }
  );
```

**Comment by JorisZierold** [comment]
Can you provide guidance or a workaround on how to obtain the actual Ethereum transaction hash in scenarios involving multi-signature confirmations via WalletConnect with Gnosis Safe? Is this a limitation with the current integration, or are there additional steps we should take to achieve the desired functionality?

**Comment by katspaugh** [comment]
This a known issue, and we recommend using the new [EIP-5792](https://www.eip5792.xyz/introduction) which we support over WalletConnect.

It basically allows you to send a tx (or a bunch of txs at the same time!), and get a safeTxHash in return.
Then there's another RPC call that tells you the status of that tx by safeTxHash. You can poll that. Once it returns success, you get an actual tx hash.

Alternatively, you could make a Safe App. See https://github.com/safe-global/safe-apps-sdk/

**Comment by monokh** [comment]
The behaviour is unexpected and really looks like a bug. It's already waiting for transaction to be sent, but after it is, returning safeTxHash through a `eth_sendTransaction` call
this means apps cannot detect the tx.

**Comment by monokh** [comment]
> This a known issue, and we recommend using the new [EIP-5792](https://www.eip5792.xyz/introduction) which we support over WalletConnect.
> 
> It basically allows you to send a tx (or a bunch of txs at the same time!), and get a safeTxHash in return. Then there's another RPC call that tells you the status of that tx by safeTxHash. You can poll that. Once it returns success, you get an actual tx hash.
> 
> Alternatively, you could make a Safe App. See https://github.com/safe-global/safe-apps-sdk/

Tested using safe app within the safe web wallet and same issue presents.
