### ISSUE TITLE
Balance change preview shows incorrect decimals when sending USDC; does not match Send 

### ISSUE THREAD

**Issue by john-packel** [safe-global/safe-wallet-web#3974]
## Bug description

When sending USDC, the preview before clicking send shows the correct value at the top in the Send field but incorrect below in the Balance change field (it is shifted 3 decimals to the left). 

E.g. in the screenshot queuing a 1 USDC transfer, Balance change preview shows 0.001 USDC. 

The simulation and transaction execution work correctly, but the preview bug causes confusion. 

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce

New transaction > Send tokens > enter an address > select 1 USDC (or any amount)

## Expected result

Balance change should say 1 USDC 

## Obtained result

Instead shows 0.001 USDC

## Screenshots

<img width="642" alt="Screen Shot 2024-07-19 at 11 14 38 PM" src="https://github.com/user-attachments/assets/9c92c969-3a57-47e6-a69b-aef975f767e6">

**Comment by katspaugh** [comment]
This was on Redefine's side and they've now fixed it ✅ 

![image (5)](https://github.com/user-attachments/assets/400d5ed4-08be-4d22-bec1-2b2ae9a9939c)

**Comment by john-packel** [comment]
Excellent, thank you!
