### ISSUE TITLE
Tx execution and safe creation cannot be done with Ledger Nano S

### ISSUE THREAD

**Issue by francovenica** [safe-global/safe-wallet-web#4041]
## Bug description
Trying to create a tx shows an error when trying to sign
Trying to execute a tx shows an error regarding enabling blind signing, but the blind signing is enabled. Tried with adding an owner, sending funds, trying to execute a spending limit usage

There is NO issue signing tx, proposing tx or signing messages
None of this issues happen with a Ledger X

## Environment
 - Browser: Chrome
 - Wallet: native ledger nano S
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Try to create a safe with "Pay now" option using a ledger Nano S
 2. Try to execute a tx in a safe with a ledger nano S 

## Expected result
Safe creation and execution should be possible like any other wallet

## Screenshots
![image](https://github.com/user-attachments/assets/429231db-a968-4638-a12c-bc8cb0ba1f34)
![image](https://github.com/user-attachments/assets/a6138fbb-0478-48ea-8e9f-d0db2cd6de4d)

**Comment by schmanu** [comment]
I just tried Safe creation with my ledger imported through metamask without any issues.
So we can def. suggest that as a workaround. 

@francovenica you put MetaMask into the environment of this ticket. But I guess you are not actually using Ledger through Metamask here? Could you put the correct environment to reproduce?

**Comment by schmanu** [comment]
@francovenica 
Even when using Ledger directly without MetaMask I was able to create a Safe, sign and execute transactions.
Which version are you running in your Ledger including the version of your Ethereum Application.
I am running Ethereum version 1.10.2

**Comment by schmanu** [comment]
@francovenica 
this is an issue with the new ledger firmware.
There are other users reporting similar errors for other txs: e.g. https://github.com/LedgerHQ/app-ethereum/issues/311

I found this workaround that seems to fix it for some users: https://community.metamask.io/t/ledger-issue-please-enable-contract-data-but-its-already-enabled-and-enabling-debug-data-fixes-it/9679/3
Could you try that?
I think its not an issue with Safe{Wallet} though.

**Comment by francovenica** [comment]
@schmanu Sorry for taking so long to get back to this.

I tried with debug enabled and even with that still fails:
I get this error when trying to do a "Send funds".
I also get an error when I'm tryin got create a safe

![image](https://github.com/user-attachments/assets/36d832c9-e111-44a2-8469-565a669ec719)

**Comment by schmanu** [comment]
We have to wait for a new firmware version. I think this is a bug in the ledger firmware.

**Comment by liliya-soroka** [comment]
Verified with the latest firmware version : execution and safe creation via Ledger Nano S direct connection work as expected
