### ISSUE TITLE
No contract interaction / transaction builder button

### ISSUE THREAD

**Issue by lance-web3** [safe-global/safe-wallet-web#4047]
## Bug description
no contract interaction / transaction builder button on the UI

## Environment
```
safe-transaction-service - v5.7.0
safe-client-gateway - v1.52.0
safe-config-service - v2.83.0
safe-wallet-web - v1.40.1
## Steps to reproduce
```

 1. [Using safe-infrastructure repo](https://github.com/safe-global/safe-infrastructure/)

## Expected result
![image](https://github.com/user-attachments/assets/56a03f49-5140-4a10-b662-de7b4498c8f2)

## Obtained result
![image](https://github.com/user-attachments/assets/b72e33f2-73d5-4f95-8c0c-8639b5fbf368)

## Screenshots
![image](https://github.com/user-attachments/assets/b72e33f2-73d5-4f95-8c0c-8639b5fbf368)

**Comment by katspaugh** [comment]
It’s not a bug. The Transaction Builder app has to be enabled for that chain in the config service.

**Comment by lance-web3** [comment]
> Transaction Builder

@katspaugh where?

**Comment by katspaugh** [comment]
> in the config service.

<img width="1299" alt="Screenshot 2024-08-07 at 11 03 00" src="https://github.com/user-attachments/assets/332760aa-c71f-4426-b712-20ee766b5c3a">

**Comment by lance-web3** [comment]
@katspaugh 

> > in the config service.
> 
> <img alt="Screenshot 2024-08-07 at 11 03 53" width="1234" src="https://private-user-images.githubusercontent.com/381895/355749514-512a9431-8d2e-494d-aa0f-b8a681212643.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMjE3NDQsIm5iZiI6MTcyMzAyMTQ0NCwicGF0aCI6Ii8zODE4OTUvMzU1NzQ5NTE0LTUxMmE5NDMxLThkMmUtNDk0ZC1hYTBmLWI4YTY4MTIxMjY0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwN1QwOTA0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYmQ0NDM0MWFhOTg5MWMxZDJiNGMzMDA0OGU5MjgxNmE3OTRkZTEwMDQyYzVkZTgzZjZhODU4MjczZjliNDQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VTYOpLiKFjVgz334nbGEiSXPFqSALqqeik2TjhyL-Ic">

did not solve though, I fill up Url, Name, Chain ids, and restarted the UI, the button did not appear. What did I miss?

**Comment by lance-web3** [comment]
ok the button appear after adding the tag, but when I click the transaction builder button, it goes to 404, it is separate component to start or what?

**Comment by lance-web3** [comment]
if we configure the official safe transaction builder url it will work

if configure to our own it will 404 because indeed it did not exist (what is our transaction builder url? separate component to start?)

**Comment by katspaugh** [comment]
You can use the official one. If you have any further questions, please use https://ethereum.stackexchange.com with a Safe tag.
