### ISSUE TITLE
Error Creating Safe with Trust Wallet Extension - "Cannot Create, Try Again Later"

### ISSUE THREAD

**Issue by ru513** [safe-global/safe-wallet-web#4165]
## Environment
 - Browser: Chrome
 - Wallet: Trust Wallet
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Create a Safe with three owners (ETH)
 2. Execute with Trust wallet Chrome extension 
 
## Expected result

Safe is created

## Obtained result

Error message received saying "cannot create, try again later"

## Additional notes
After retrying at the point of each error message, I am still unable to move past the create screen. However the transactions did go through;

https://etherscan.io/tx/0x075e17a8d2b47d5ac388e9467a1adab759773c48c280871206324f8decbf4b11
https://etherscan.io/tx/0x9b2a81c8c0244b79afe386a6b38d358a556ac7b28594462bb76bc966b172ae62

While not related to _creating_ a safe , similar behaviour is shown on this ticket also involving Trust Wallet;
https://github.com/5afe/safe-support/issues/512

Where a transaction fails at UI level but goes through on-chain

**Comment by case-hub** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@ru513

**Comment by liliya-soroka** [comment]
can not reproduce. As soon as the balance of the connected signer was updated in the Trusted wallet extantion , I was able to create a safe and execute a send tx
