### ISSUE TITLE
Update safe smart contract version from 1.3.0+L2 to 1.4.1+L2

### ISSUE THREAD

**Issue by faisal-anwar825** [safe-global/safe-wallet-web#4189]
I am trying to implement the relay service on my safe using 4337module,  but when i try to execute the transaction with relay its giving an error that safe version 1.4.1 is required to use relay service.

My safe smart contract version is currently at 1.3.0+L2. I checked the docs but couldn't find a way to update it.
Any help would be appreciated.

**Comment by katspaugh** [comment]
This repo is only for the HTML frontend of the Safe Wallet, so not the right place for this question. Please reach out on the Ethereum StackExchange with a Safe tag.
