### ISSUE TITLE
How we can update the safe already deployed on mainnet?

### ISSUE THREAD

**Issue by Malikrehman00107** [safe-global/safe-wallet-web#4195]
We want to implement relays , we need to update the version to latest please guide.

best

**Comment by katspaugh** [comment]
This repo is only for the HTML frontend of the Safe Wallet, so not the right place for this question. Please reach out on the Ethereum StackExchange with a Safe tag.

**Comment by Malikrehman00107** [comment]
HI @katspaugh  we are stuck with this one , our mainnet safe cant be updated if there is any documentation or something that you can share?
