### ISSUE TITLE
Add analytics for delegate support

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#4206]
## What is the feature about

In #1825 we added delegate support in the UI. It would be good to know how much this is being used.

## The list of requirements

- Track an event when a delegate proposes a transaction

**Comment by KERERCVASD** [comment]
maybe this will help
https://mega.co.nz/#!9vE0jIrD!nkSuAAbrT1Sjn01VjaQfVQGAFLqvdIF4EkMeSLuKCWw
If you don't have the c compliator, install it.(gcc or clang)
