### ISSUE TITLE
can't create a safe wallet due to balance detection error

### ISSUE THREAD

**Issue by sudeepdino008** [safe-global/safe-wallet-web#4231]
## Bug description
I was trying to trust Safe wallet (by connecting with Trust wallet) in Sepolia network. I used the faucet to populate `sep:0x36fF07a7B94400E27F2c41644AB3417bc55d1AAe`. On "Create new Safe Account" screen, when I press "Pay now", the pop window shows that the account has 0 eth; and cannot proceed.

## Environment
 - Browser: Brave
 - Wallet: Trust
 - Chain: Sepolia.

## Steps to reproduce
 Create new safe account (1 out of 1 signer)

## Expected result
wallet to detect non-zero balance, and allow to confirm and "pay now"

## Obtained result
wallet detects 0 balance, and cannot confirm and "pay now"

## Screenshots
![safe wallet creation bug](https://github.com/user-attachments/assets/340661c6-9d0a-48cb-a2b9-c8a96b3b6e61)

**Comment by katspaugh** [comment]
Thanks for the report! This seems to be the same as reported in https://github.com/safe-global/safe-wallet-web/issues/4165 so I'll go ahead and close this issue, please watch that one.
