### ISSUE TITLE
No block explorer button visible for transaction guards

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#4256]
## Bug description

Transaction guards only show a copy button but no block explorer button

## Steps to reproduce
 1. Go to the settings page on a safe with a transaction guard
 2. Observe the transaction guard has a block explorer button

## Screenshots
![Screenshot 2024-09-26 at 12 46 15](https://github.com/user-attachments/assets/7c6303c2-4538-4241-8e71-1a2cdc68b416)

**Comment by liliya-soroka** [comment]
Verified
