### ISSUE TITLE
UI: Chain prefix toggle should reflect the address display

### ISSUE THREAD

**Issue by TanyaEfremova** [safe-global/safe-wallet-web#4261]
## Bug description
When clicked on _Receive_, as a user I can disbale chain prefix being pre-pended to the address. But when disabled, the prefix is still there in UI.

## Environment
 - Browser: Chrome
 - Wallet: Any
 - Chain: Any

## Steps to reproduce
 1. Go to any Safe account
 2. Click on QR icon to trigger Receive modal with the QR code
 3. See that the chain prefix is still there

## Expected result
The chain prefix should disappear from the UI, when the toggle is off.
## Screenshots
<img width="637" alt="Screenshot 2024-09-26 at 16 30 55" src="https://github.com/user-attachments/assets/1e4022a4-be78-4cdc-8c69-49de21c6d1eb">

**Comment by Arya-A-Nair** [comment]
Hey, can you assign me this. I would love to work on it

**Comment by usame-algan** [comment]
@Arya-A-Nair yes sure, go for it!

**Comment by Arya-A-Nair** [comment]
hey @usame-algan, I have raised a PR for the same over PR [#4271 ](https://github.com/safe-global/safe-wallet-web/pull/4271)

**Comment by usame-algan** [comment]
Thanks @Arya-A-Nair!
