### ISSUE TITLE
Transaction didnt sign by safe but appear in the Transaction history 

### ISSUE THREAD

**Issue by Malikrehman00107** [safe-global/safe-wallet-web#4328]
Our Safe Deployed on mainnet BSC.

https://bscscan.com/address/0xb86b48Cfa46B3Bdf8f584B8A78B4fEEd1B54AC19

We notice that there is traction made which is fake USDT seems our safe ( we don't have these token ) neither we sign can you please tell me what it is and it is showing that it is sended from our safe.

https://bscscan.com/tx/0x4e871cd77cb8ec80123f1a59b85b09dc5c74e6b13dd5b6c4d7fff255f29432b4

**Comment by liliya-soroka** [comment]
There are malicious transactions- https://help.safe.global/en/articles/180783-what-is-address-poisoning-and-how-does-safe-wallet-battle-it
<img width="790" alt="image" src="https://github.com/user-attachments/assets/b48e868a-3a7a-4dce-92c7-a2ad72ce5efd">
You can use "Hide suspicious "
<img width="214" alt="image" src="https://github.com/user-attachments/assets/4e6bd699-45ca-4ffc-b223-76467529d564">
