### ISSUE TITLE
Chains are missing if more than 20 are configured on the config service

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-wallet-web#4336]
## Bug description
If our config service has more than 20 visible chain configs we only display the first 20.

We need to fetch all pages of chain infos from the endpoint.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Activate >20 chains
 2. Observe missing chains in the network selector

## Expected result
All chains are loaded and available

## Obtained result
Only 20 chains are available

**Comment by liliya-soroka** [comment]
Verified
