### ISSUE TITLE
SafeWallet Disconnects from Wallet After Page Refresh

### ISSUE THREAD

**Issue by lance-web3** [safe-global/safe-wallet-web#4354]
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: fxcore mainnet

## Steps to Reproduce
1. Navigate to the SafeWallet page and connect a wallet.
2. Once connected, refresh the browser.
3. Observe that the wallet is disconnected and the user is prompted to reconnect.

## Obtained Result
The wallet disconnects after a page refresh, requiring the user to manually reconnect.

## Expected Result
The wallet should remain connected after a page refresh, allowing the user to continue their session without needing to reconnect.

## Videos
https://drive.google.com/file/d/1lU7ztQsgvXYvOCBJgc2DN34mfjTV4P2l/view?usp=drive_link

**Comment by lance-web3** [comment]
> what wallet do you use ? MM is connected automatically after the browser refresh
> 
>  Screen.Recording.2024-11-18.at.13.53.24.mov

Metamask, maybe check our video again

**Comment by ChristianGunawanX** [comment]
after try with the same evidence, it won't disconnect, can closed this bug

https://drive.google.com/file/d/1V358jftdq5VKagUr-9ZgALCcAqQ8AMsf/view?usp=drive_link

**Comment by lance-web3** [comment]
issue not appearing anymore as per Christian

**Comment by liliya-soroka** [comment]
@lance-web3 , I have a small question about the prefix of the network (the prefix you see on the UI before the address ). Is it expected to have such a long prefix ( short name of the network) : "dhobyghaut" for the fxCore testnet network
<img width="158" alt="image" src="https://github.com/user-attachments/assets/1bdd0cc0-816a-49b0-9386-96f2e5966d9f">

**Comment by lance-web3** [comment]
> @lance-web3 , I have a small question about the prefix of the network (the prefix you see on the UI before the address ). Is it expected to have such a long prefix ( short name of the network) : "dhobyghaut" for the fxCore testnet network <img alt="image" width="158" src="https://private-user-images.githubusercontent.com/338622/388508378-1bdd0cc0-816a-49b0-9386-96f2e5966d9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2NzQ1NzksIm5iZiI6MTczMjY3NDI3OSwicGF0aCI6Ii8zMzg2MjIvMzg4NTA4Mzc4LTFiZGQwY2MwLTgxNmEtNDliMC05Mzg2LTk2ZjJlNTk2NmQ5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyN1QwMjI0MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2M3NDI0MzgwZTlhYTQ5OTkxNGE1YTcwMzA4ZWFkNTkzNTRhMjcxYWUyM2NmODBhMmI5MjA5MjIwMTc0ZDNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zFU7WpPb4s_vjXT-xDSnekx8fT3hMZmWuil81qWPM1A">

@liliya-soroka yes, shortname for our mainnet: fxcore, testnet: dhobyghaut

same here as well https://github.com/safe-global/safe-core-sdk/pull/910/files
