### ISSUE TITLE
Worldchain icon is not seen in dark 

### ISSUE THREAD

**Issue by liliya-soroka** [safe-global/safe-wallet-web#4381]
## Bug description
Worldchain icon is not seen in dark 
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Go to safe creation flow
 2. add all networks and check tooltip with list of networks 

## Expected result
add a new icon for worldchain for the dark themes
## Screenshots
<img width="170" alt="image" src="https://github.com/user-attachments/assets/5bcbd21a-9283-4047-89e2-33d2fc22d605">

**Comment by TanyaEfremova** [comment]
Let's replace the logo with the correct one that uses a background color 
![logo_worldchain](https://github.com/user-attachments/assets/ef0b6e15-89ea-47c6-8558-bf4e0a466df1)

**Comment by liliya-soroka** [comment]
Verified, the icon was fixed
