### ISSUE TITLE
Disable add to batch for safeApps

### ISSUE THREAD

**Issue by compojoom** [safe-global/safe-wallet-web#4392]
When doing a transaction from a safe App the user is able to sign/execute the tx or "add to batch". When the user signs the tx, we return the txId to the dapp. The Dapp is able to follow on their end what happens with the transaction. That's not the case when a user ads a tx to a batch. If that happens we just close the "transaction sign/execute" flow without retuning any hash to the dapp. The Problem is that we cannot return the hash of the transaction that was added to batch. The safeTX hash we have won't be for the tx that is later going to be executed on chain. The batch execution tx would have a different txId. 
Because of this I think that it would be good to disable the "add to batch" button for 3rd party dapps.

**Comment by francovenica** [comment]
This PR's fixes this. https://github.com/safe-global/safe-wallet-web/pull/4623
