### ISSUE TITLE
No Safe Deployment found

### ISSUE THREAD

**Issue by molecula451** [safe-global/safe-wallet-web#4415]
![image](https://github.com/user-attachments/assets/2a92a46f-5101-49df-9894-4d76e73221b0)

the chain was added at https://github.com/safe-global/safe-deployments/releases/tag/v1.37.12 chainID 970

**Comment by dasanra** [comment]
@molecula451 could you share more details about where do you get this?

How are you running the web interface? Are you building this repo locally? Or are you running it through [safe-infrastructure](https://github.com/safe-global/safe-infrastructure/tree/main)

When do you get this error? When doing some specific action? Did you set any specific Safe version or are you relaying in the interface defaults?

**Comment by molecula451** [comment]
> @molecula451 could you share more details about where do you get this?
> 
> How are you running the web interface? Are you building this repo locally? Or are you running it through [safe-infrastructure](https://github.com/safe-global/safe-infrastructure/tree/main)
> 
> When do you get this error? When doing some specific action? Did you set any specific Safe version or are you relaying in the interface defaults?

no, im not building this repo locally, im relyiging on the safe-infrastructure, this happen when trying to create a wallet using the network

**Comment by molecula451** [comment]
> @molecula451 - can you please give a detailed step by step example? chainID 970 is not something that our interface supports.

I am setting up the using https://github.com/safe-global/safe-infrastructure/tree/main

which in turns pull the container from docker https://hub.docker.com/r/safeglobal/safe-wallet-web/tags

I add chain at http://localhost:8080/cfg/admin/chains/chain/add/ and still get the error when trying to create a "safe"

**Comment by molecula451** [comment]
https://github.com/safe-global/safe-wallet-web/blob/ce95e2d52e04b6b60df563f5584fb06e8c71e581/src/features/recovery/services/transaction-list.ts#L19

this conditional is the error

**Comment by compojoom** [comment]
Can you re-download the images? We released [v1.45.2](https://github.com/safe-global/safe-wallet-web/releases/tag/v1.45.2) and it is first there that we added safe-deployments 1.37.12

**Comment by molecula451** [comment]
> Can you re-download the images? We released [v1.45.2](https://github.com/safe-global/safe-wallet-web/releases/tag/v1.45.2) and it is first there that we added safe-deployments 1.37.12

the images Im using area "latest" so its v1.45.2 and itis using safe-deployments 1.37.12 

![pkgimage](https://github.com/user-attachments/assets/91e49b8b-1714-4cab-b008-7302ca977e8e)

i think part of the issue is the image still  has api-kit at 2.4.6 and protocol kit its still a 4.1.1

![fdimage](https://github.com/user-attachments/assets/b8b698ce-8be0-4265-81bf-06cb04d9344f)


@dasanra update it yesterday, but the image still pull old versions

**Comment by molecula451** [comment]
its because of the packages, there is no doubt, too many abstracts object requestes the types from protocol-kit as chainId  and it was just added at v5.0.3 can we have a bump on it?

**Comment by molecula451** [comment]
also when it upgrades 
![image](https://github.com/user-attachments/assets/823a3bcd-2033-4b64-bf96-c6241f2c0c2a)
the build breaks due to no matching the protocol-kit version

https://www.npmjs.com/package/@safe-global/safe-core-sdk-types

**Comment by molecula451** [comment]
![image](https://github.com/user-attachments/assets/3fa1c8b6-eb51-4fc7-9af3-bfda38641006)

**Comment by dasanra** [comment]
Hey @molecula451 if you run the interface from the `safe-wallet-web` repo instead from docker it should be a matter of deleting from the `yarn.lock` the entry for the older `safe-deployments` v1.37.9 [here](https://github.com/safe-global/safe-wallet-web/blob/9620abded8c93697c8ceadb67ab9a5fec9e17407/yarn.lock#L4226) and running yarn again so the protocol-kit also relies on v1.37.12

That should do the trick for your test and eventually this will be already upgraded in the web interface too.

**Comment by molecula451** [comment]
> Hey @molecula451 if you run the interface from the `safe-wallet-web` repo instead from docker it should be a matter of deleting from the `yarn.lock` the entry for the older `safe-deployments` v1.37.9 [here](https://github.com/safe-global/safe-wallet-web/blob/9620abded8c93697c8ceadb67ab9a5fec9e17407/yarn.lock#L4226) and running yarn again so the protocol-kit also relies on v1.37.12
> 
> That should do the trick for your test and eventually this will be already upgraded in the web interface too.

that is not an issue sir, Im running from docker and still get No  Safe Deployment

**Comment by molecula451** [comment]
why sepolia is detected? and no chainId 970? 
![image](https://github.com/user-attachments/assets/5f76462e-88c3-42a4-9970-ec2bbf31c3e4)

**Comment by molecula451** [comment]
this is a local instance on docker, im not running this web by cloning the repo

**Comment by molecula451** [comment]
i wrote a script to test:
[Screencast from 28-10-24 16:17:06.webm](https://github.com/user-attachments/assets/3a610715-47d3-42e0-926d-fcae615c1003)

chainId: 1 returns data, chainId: 970 isn't

**Comment by molecula451** [comment]
https://github.com/safe-global/safe-deployments/releases/tag/v1.37.13

![Screenshot from 2024-10-28 16-20-21](https://github.com/user-attachments/assets/8bc0788b-0eb7-43a6-8276-78802905062e)

its finally returning data

**Comment by molecula451** [comment]
but then the container breaks with

https://nextjs.org/docs/messages/next-config-error
