### ISSUE TITLE
Could not determine the Safe creation parameters

### ISSUE THREAD

**Issue by gionn** [safe-global/safe-wallet-web#4428]
## Environment
 - Browser: Firefox
 - Wallet: MetaMask
 - Chain: N/A

## Steps to reproduce
 1. Create a safe wallet on Base
 2. Add another network (Optimism) - using gasless/sponsored transaction
 3. Add another network

## Expected result

It should allow me to create a 3rd safe on any supported network

## Obtained result

I get a fatal error immediately after clicking `Add another network`:

```
Code 816: Error computing replay Safe creation data (The Safe creation information for this Safe could not be found or is incomplete.)
```

## Screenshots

![Screenshot from 2024-10-25 21-39-22](https://github.com/user-attachments/assets/8251fabe-28cc-4f62-90e6-4afc747a57f4)

**Comment by gionn** [comment]
I managed to create a new safe on Ethereum using the top-right contextual menu after entering the Optimism safe, and now also the issue to add another network from the safe selection page is gone.

So it really looks like that if the first listed safe has been created with a sponsored transaction then the network add feature when initiated from the safe selection page is broken.

**Comment by liliya-soroka** [comment]
It cannot reproduce; the add network works for the safes created via relay. The error can also be displayed if there is a temporary problem with the network RPC
15.11.24
