### ISSUE TITLE
Upgrade to Material UI v6

### ISSUE THREAD

**Issue by usame-algan** [safe-global/safe-wallet-web#4448]
## What is the feature about

Material UI v6 is out and has a few new features that we built ourselves in the past. Notably, generating css variables for colors etc. and adding better light/dark theme support with a new hook.

## The list of requirements

- [ ] Upgrade MUI to v6
- [ ] Check if we can remove `scripts/css-vars.ts`
- [ ] Check if we can remove `useDarkMode`

## Links

https://mui.com/blog/material-ui-v6-is-out/

**Comment by katspaugh** [comment]
Resolved by #4485.
