### ISSUE TITLE
Add WalletConnect support for dApp to Safe Wallet connection

### ISSUE THREAD

**Issue by junha-ahn** [safe-global/safe-wallet-web#4453]
## What is the feature about

I want an env-variable that can enable wallet-connect for `dapp <=> safeWallet`

The feature shown in the image below is what I want

<img width="1899" alt="image" src="https://github.com/user-attachments/assets/11775247-c4f7-4086-ae50-c6ace1cabce7">

When I run safe-wallet-web with [safe-infrastructure](https://github.com/safe-global/safe-infrastructure/blob/main/docs/running_locally.md) there is no feature to do it
<img width="1915" alt="image" src="https://github.com/user-attachments/assets/1c76e32d-8de2-49f1-bd49-7556e0f84ff8">

I already created a question for it [Is it possible to use Wallet connect with "self-hosted safe infrastructure(safe-wallet-web)"](https://ethereum.stackexchange.com/questions/166507/is-it-possible-to-use-wallet-connect-with-self-hosted-safe-infrastructuresafe)

but I think there is no feature (or at least no env variable for this in the [README.md](https://github.com/safe-global/safe-wallet-web/blob/dev/README.md#getting-started-with-local-development)) so I create a git issue.

## [NEXT_PUBLIC_WC_PROJECT_ID](https://github.com/safe-global/safe-wallet-web/blob/dev/README.md?plain=1#L32)

`NEXT_PUBLIC_WC_PROJECT_ID` is only for the connection to Safe-Wallet, I dont need it

<img width="658" alt="image" src="https://github.com/user-attachments/assets/0ca272dd-9f67-402e-a384-4b89a3ae85fa">

**Comment by liliya-soroka** [comment]
To add "connect dapp via wallet connect feature" on UI , NATIVE_WALLETCONNECT feature should be enabled in the config service 
<img width="437" alt="image" src="https://github.com/user-attachments/assets/b5c54415-ebec-4bba-ac81-609b4cb84866">
<img width="405" alt="image" src="https://github.com/user-attachments/assets/566e044e-9a4d-4527-971f-128b2d4228be">
