### ISSUE TITLE
Aggregated Multichain balances are wrong for networks without default tokenlists

### ISSUE THREAD

**Issue by schmanu** [safe-global/safe-wallet-web#4479]
## Bug description
When requesting the Safe overviews to display fiat balances in the network selector and sidebar we always pass `trusted=true` regardless of the default tokenlist setting and feature flag.

This leads to always 0$ balance for e.g. Base Safes.

## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Open a Base safe with non zero fiat balance.
 2. Observe that the sidebar and network selector always shows 0$ while the assets list and dashboard shows the actual value.

## Expected result
The same fiat value as shown on the dashboard.

## Obtained result
Always a 0$ value

## Screenshots
![Screenshot 2024-11-05 at 14 48 30](https://github.com/user-attachments/assets/e30cd65c-07e8-44cb-b28c-b2b64ac6eff3)

**Comment by liliya-soroka** [comment]
Verified
