### ISSUE TITLE
ConfirmationRequired always 1

### ISSUE THREAD

**Issue by molecula451** [safe-global/safe-wallet-web#4517]
Account threshold is 3, confirmationRequired is always 1 when sending a transaction within the UI

![Screenshot from 2024-11-11 15-30-30](https://github.com/user-attachments/assets/c1db92c3-fe43-4c63-a4e3-ca776ff93cad)

**Comment by usame-algan** [comment]
Hi @molecula451, please provide more information:

- Network
- Safe address
- Does it happen on app.safe.global?

**Comment by molecula451** [comment]
> Hi @molecula451, please provide more information:
> 
>     * Network
> 
>     * Safe address
> 
>     * Does it happen on app.safe.global?

Hey its a custom network, with deterministic Safe deployment using the Safe Insfracture repo latest UI version
