### ISSUE TITLE
Can't create new Super Account on "New Super Account page

### ISSUE THREAD

**Issue by icarionan** [safe-global/safe-wallet-web#4639]
## Bug description
Can't create new Super Account on "New Super Account page. Botton for the next step doesn't work.
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: Ethereum mainnet

## Steps to reproduce
 1. Main connect wallet page.
 2. Connect wallet.
 3. Go to Create new Super Account page 
## Expected result
Gpint for the next step of new Super Account creation
## Obtained result
"Next" button doesn't react.
## Screenshots
<img width="780" alt="Снимок экрана 2024-12-11 в 18 56 36" src="https://github.com/user-attachments/assets/7eac0a12-8297-489c-bf94-b03ebdb5563a" />

**Comment by StanleyMorgan** [comment]
Same issue

**Comment by katspaugh** [comment]
This seems to be a bug request for a Safe fork. Please reach out to that fork's team for support. Thanks!

**Comment by icarionan** [comment]
Oh sorry. I thought that it was a for repo.
