### ISSUE TITLE
Improved pairing connector usage

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#563]
## What is the feature about

Safe Mobile wallet pairing improvements.

## The list of requirements

Now we have a separate WC `connector` and module, we should only interface with the `connector` events until the wallet is connected, e.g.

- `'connect'` connects wallet to module
- `'disconnect'` creates a new session
- `'display_uri'` updates URI

The current workaround relies on a manual refresh of the WC session. The following needs to be either removed or updated:

- `PairingDetails` should not attach a listener to the `connector`. We should remove the manual refresh workaround from the QR code.
- If the `hasInitialized` flag is required, we should set it to `true` after `connectWallet` is called instead of a subscription.

**Comment by katspaugh** [comment]
Wait until WC2.

**Comment by katspaugh** [comment]
Closing because the future of this feature is unclear given its low usage.
