### ISSUE TITLE
Display `safeTxHash` when signing

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#704]
## Overview
When signing, the `safeTxHash` is not displayed and it is therefore not possible to verify the validity of it. Currently, you would either have to calculate it yourself or call `getTransactionHash` directly from the contract. Therefore, it would be beneficial to display it in the UI when requesting a signature.

## Notes

- Although it would be nice to display this in the transaction list and used from there as reference, immediately executed transactions do not appear there.
- This is helpful for hardware wallets/wallets which do not support the signing of typed data.

## Requirements
- Emit `safeTxHash` from `TxSender` alongisde a signature request.
- Display it in the UI (likely in the "Please sign the transaction" notification.
- Show the hash in bold if possible

## Designs

Preliminary mock, awaiting final design from @liliiaorlenko

![image](https://user-images.githubusercontent.com/20442784/152506421-c880c92f-53cc-4560-9507-363665b6da8e.png)

## Links
- [Post initial implementation discussion thread](https://5afe.slack.com/archives/C03DAGWJCR5/p1668503195855029)

**Comment by francovenica** [comment]
LGTM
checked for both signing and execution
![image](https://user-images.githubusercontent.com/4503659/200962788-408f2cbc-acee-4ccc-b242-61f61085156c.png)

![image](https://user-images.githubusercontent.com/4503659/200962810-6efa9759-b3d6-49a6-9e89-138b9ab64ed6.png)

**Comment by liliya-soroka** [comment]
Confusing cases( in progress):
1. "Please sign with your wallet" is displayed after the tx was signed using MM and the tx was created
<img width="380" alt="image" src="https://user-images.githubusercontent.com/338622/201893159-b15e66e8-6b88-4025-881c-4b46767b1629.png">

**Comment by katspaugh** [comment]
The PR linked above is rolled back.
