### ISSUE TITLE
Remove "legacy" wallet module names from wallet config.

### ISSUE THREAD

**Issue by iamacook** [safe-global/safe-wallet-web#713]
## Description

We currently [map "legacy" wallet modules names to new ones](https://github.com/safe-global/web-core/blob/main/src/hooks/wallets/wallets.ts) due migrating from `onboard` to `@web3-onboard`. After we release `web-core`, we should remove all references to the old names and add the new ones to the gateway

## Requirements

- [ ] Update the wallet keys to remove all references to old gateway names. We will have to keep the "legacy" names for continued support of the `safe-react` deployment.
- [ ] Add new module/provider names to gateway
- [ ] Update `disabledWallets` with new names

**Comment by katspaugh** [comment]
The legacy desktop app will not work if we remove them. Need to align on its potential deprecation.
